### ISSUE TITLE
Docs use undefined includes function

### ISSUE THREAD

**Issue by moltar** [danger/danger-js#1001]
Docs use `includes` function that isn't defined anywhere.

https://danger.systems/js/

In the "What does this Look like?" section.

```js
const hasChangelog = includes(danger.git.modified_files, "changelog.md")
const isTrivial = contains((danger.github.pr.body + danger.github.pr.title), "#trivial")

if (!hasChangelog && !isTrivial) {
  warn("Please add a changelog entry for your changes.")
}
```

And other examples also.

A more correct way would be to just use `includes` array method:

```js
danger.git.modified_files.includes('package.json')
```

**Comment by orta** [comment]
Yeah, that's a bug 👍

**Comment by moltar** [comment]
Where are these files stored? Not seeing it in the docs dir. Thanks.

**Comment by orta** [comment]
GitLab! https://gitlab.com/danger-systems/danger.systems

**Comment by moltar** [comment]
https://gitlab.com/danger-systems/danger.systems/-/merge_requests/194

**Comment by orta** [comment]
Shipped - thanks!
