### ISSUE TITLE
GitLab hijacking other Providers? Issue in Danger's Compiled Output?

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#1012]
Our CI, Nevercode.io -- supported by a [Provider that I added 2 years ago](https://github.com/danger/danger-js/blob/174f8e18bc794af8d2d54f518ae347d95cefd335/source/ci_source/providers/Nevercode.ts) is running DangerJS to announce when builds are complete.

Today it started throwing Errors that include problems in the Gitlab Provider -- maybe in Global Scope?

<details>
  <summary>Error Output - Looks like compilation issue?</summary>

```shell
$ /Users/greenhouse/tmpz7zloigw/node_modules/.bin/danger ci --id nevercode-announcer --dangerfile ./scripts/danger/nevercode-announcer.ts
/Users/greenhouse/tmpz7zloigw/node_modules/gitlab/dist/index.js:1
"use strict";function _interopDefault(e){return e&&"object"==typeof e&&"default"in e?e.default:e}Object.defineProperty(exports,"__esModule",{value:!0});var universalUrl=require("universal-url"),Li=_interopDefault(require("li")),humps=require("humps"),Ky=_interopDefault(require("ky-universal")),FormData=_interopDefault(require("form-data")),queryString=require("query-string"),randomstring=_interopDefault(require("randomstring")),extendStatics=function(e,t){return(extendStatics=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var r in t)t.hasOwnProperty(r)&&(e[r]=t[r])})(e,t)};function __extends(e,t){function r(){this.constructor=e}extendStatics(e,t),e.prototype=null===t?Object.create(t):(r.prototype=t.prototype,new r)}var __assign=function(){return(__assign=Object.assign||function(e){for(var t,r=1,n=arguments.length;r<n;r++)for(var o in t=arguments[r])Object.prototype.hasOwnProperty.call(t,

TypeError: global$1.XMLHttpRequest is not a constructor
    at checkTypeSupport (/Users/greenhouse/tmpz7zloigw/node_modules/gitlab/dist/index.js:1:31955)
    at Object.<anonymous> (/Users/greenhouse/tmpz7zloigw/node_modules/gitlab/dist/index.js:1:32279)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/greenhouse/tmpz7zloigw/node_modules/danger/distribution/platforms/gitlab/GitLabAPI.js:39:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

</details>

I'm not sure what to do here, as A. we're not using Gitlab, B. I don't think `XMLHttpRequest` is the recommended API for node?

This issue seems related: https://github.com/jdalrymple/gitbeaker/issues/377 but from July of last year.

**Comment by Soyn** [comment]
@fbartho Is there a stable public env for us to debug? It's hard to check this problem by your description.

**Comment by fbartho** [comment]
@Soyn no, unfortunately this is our company's private codebase.

I'll be investigating today to try to eliminate things. Do you have any thoughts as to what context I could share that might make this more useful?

**Comment by fbartho** [comment]
I was on Danger 8.0, and that branch was doing a big upgrade, so maybe there's a conflict somewhere between Danger 8.0 and the other dependencies we updated. Will try to narrow it down.

**Comment by fbartho** [comment]
Nevercode is gone, this ticket is irrelevant now. Closing.
