### ISSUE TITLE
Bug: Markdown Message Ordering got shuffled?

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#1014]
Example code:

```typescript
	markdown(assembleTable(recentBuildHeaders, recentBuildLinks));
	markdown(
		makeDisclosableBlock(
			`All commits with builds for ${currentBranchName}`,
			assembleTable(allBuildHeaders, allBuildLinks),
		),
	);
	markdown(
		"#### Latest Build Status Pages\n" +
			assembleTable(buildBadgeTableHeaders, [buildBadgeTableValues]),
	);
```

This code hasn't been changed since 2019-03-29

Expected Rendering (from last week): 
<img width="755" alt="screenshot of danger comment in expected layout" src="https://user-images.githubusercontent.com/209712/76113083-4d9ca280-5f98-11ea-8f87-93f10e1d5542.png">

Yesterday's Rendering:
<img width="752" alt="screenshot of danger comment with some of the markdown messages out of order" src="https://user-images.githubusercontent.com/209712/76113154-73c24280-5f98-11ea-9fde-47b6e5220373.png">

If you compare the code, to the renderings, the "Latest Build Status Pages" table is expected to be last.

It appears we're using `danger@8.0.0` -- will try updating, to see what happens.

**Comment by fbartho** [comment]
Updating to `danger@9.2.10` did not resolve this issue. It appears that markdown entries are being flipped in order when rendering to a comment.

**Comment by orta** [comment]
It should be deterministic - so maybe it's just deterministically reversed.

**Comment by fbartho** [comment]
The problem I see is that based on the code, it’s not deterministic - otherwise I could fix this! The top entry of 3 (in code) is shuffled to the bottom (in screenshot 2)

**Comment by orta** [comment]
Ah, fair - I guess it's not unreasonable to record the order when a violation is created to ensure it's consistent on both sides. 

I'm pretty sure there are some tests which might fail if it's indeterminate, but it's been a while since I've looked at this codebase

**Comment by fbartho** [comment]
I could rewrite my code, to combine these markdown messages into one call, so I have a workaround for myself. Not sure if this is valuable to try to track down?

**Comment by orta** [comment]
Looks like it's been around while https://github.com/danger/danger-js/issues/845 - so if no-one else has also thought it important enough to work on, that's fine IMO

**Comment by falkenhawk** [comment]
Is there a possibility to fix this issue? 🙏

**Comment by falkenhawk** [comment]
my code looks like this:
```typescript
function doStuff(n) {
  return Promise.all([...]).then(res => {
     markdown(`message ${n}`);
  });
}

schedule(async () => {
  await doStuff(1);
  await doStuff(2);
  await doStuff(3);
});
```
and testing locally with `danger pr` always yields: (maybe i was just lucky to get the correct order in all test runs 🤔)
```
## Markdowns
message 1
message 2
message 3
```

while running this in github workflow, the resulting order of the markdown strings are indeterministic. Sometimes it's in correct order, sometimes it's shuffled.

ofc my real `doStuff` function is much more complex

**Comment by orta** [comment]
You're welcome to fix it 👍 

Maybe add a creation date to the Violations and then sort it at the end

**Comment by falkenhawk** [comment]
> You're welcome to fix it 👍

#1336 @orta
