### ISSUE TITLE
[BUG] Danger pr incorrectly constructs a GitLab API URL

### ISSUE THREAD

**Issue by AnthonyMastrean** [danger/danger-js#1028]
**Describe the bug**
The GitLab API URL is incorrectly constructed from a gitlab.com website URL. Specifically, danger-js is retaining the extra `/-/` from the gitlab.com website URL when constructing the API URL and that's incorrect per the [docs](https://docs.gitlab.com/ee/api/projects.html#get-single-project) and [encoding rules](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding).

**To Reproduce**
1. Run `danger pr` with a gitlab.com MR URL.
```
> danger pr https://gitlab.com/vaeit/danger-examples/-/merge_requests/1
```
 2. Observe the HTTP error.
```
Starting Danger PR on vaeit/danger-examples/-#1
Error:  HTTPError: Not Found
    at fn (C:\Users\anthony\Work\gitlab.com\vaeit\danger-examples\node_modules\ky\umd.js:266:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Ky._retry (C:\Users\anthony\Work\gitlab.com\vaeit\danger-examples\node_modules\ky\umd.js:334:12) {
  name: 'HTTPError',
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples%2F-/merge_requests/1/changes',
      status: 404,
      statusText: 'Not Found',
      headers: [Headers],
      counter: 0
    }
  },
  description: '404 Project Not Found'
}
```
 3. Observe the strangely constructed API URL (the `/-/` is retained from the website URL and partially HTTP encoded as `%2F-`).
```
https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples%2F-/merge_requests/1/changes
                                                          ^---^
```

**Expected behavior**

Danger should construct the API URL as

```
https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples/merge_requests/1/changes
```

**Screenshots**

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.0.0
| node             | 13.5.0
| npm              | 6.13.4
| Operating System | Windows 10 Pro x64 1909

**Additional context**

Here is a request (using PowerShell's curl equivalent) against the correctly constructed API URL.

```
PS> (Invoke-RestMethod `
>>     -Headers @{'Private-Token'=$ENV:DANGER_GITLAB_API_TOKEN} `
>>     -Uri "https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples/merge_requests/1/changes") | Format-Table -Property id,iid,title,web_url

      id iid title      web_url
      -- --- -----      -------
54210468   1 Dangerfile https://gitlab.com/vaeit/danger-examples/-/merge_requests/1
```

And here is a request using the API URL that danger-js put together with the extra `%2F-`.

```
PS> (Invoke-RestMethod `
>>     -Headers @{'Private-Token'=$ENV:DANGER_GITLAB_API_TOKEN} `
>>     -Uri "https://gitlab.com/api/v4/projects/vaeit%2Fdanger-examples%2F-/merge_requests/1/changes") | Format-Table -Property id,iid,title,web_url
Invoke-RestMethod : {"message":"404 Project Not Found"}
At line:1 char:2
+ (Invoke-RestMethod `
+  ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by AnthonyMastrean** [comment]
I don't know if `/-/` in a URL is some kind of spooky convention, but the gitlab.com website URL redirects if I strip it out...

```
https://gitlab.com/vaeit/danger-examples/merge_requests/1
```

I tried passing that URL into danger and it worked?!

```
> danger pr https://gitlab.com/vaeit/danger-examples/merge_requests/1

Starting Danger PR on vaeit/sandbox/danger-examples#1

Danger: ✓ passed, found only messages.
```

**Comment by orta** [comment]
Probably a regex for pulling out the metadata from a PR needs updating to handle this case
