### ISSUE TITLE
Run danger for failed PRs

### ISSUE THREAD

**Issue by agnivade** [danger/danger-js#103]
Hi there,

This seems like a great project ! 

My use-case is to update failed PRs with a comment containing the text from the failed travis test that was run. This is so that I can automate asking users to take a look at the errors. And also one does not have to manually click the travis link to look what the error was.

How can I write a Dangerfile to achieve this ?

**Comment by kwonoj** [comment]
Simplest way I can think of is write stdout into file, then message it into dnager if test exit with non zero exit code. Or either let dangerfile runs test script by spawning process synchronously and collect stdout / exitcode directly.

**Comment by agnivade** [comment]
Yea, I was doing a similar thing already at @tldr-pages, but the problem I faced was for PRs coming from external repos(which is the normal use-case), github prevented auth token credentials to be read(https://github.com/travis-ci/travis-ci/issues/1301). So the bot I wrote to comment on a PR failed to do the job. How does Danger circumvent around this ?

**Comment by orta** [comment]
For [OSS projects](http://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use) we recommend not giving any access rights to the user used for danger (this is how Jest/Styled-Components do it for example ) 

This means there is no problem with others seeing your token. The pattern that you're talking about is something we do on the Ruby Danger ( Rspec outputs Junit style XML, then this [plugin reads it](http://danger.systems/plugins/junit.html) )

If it's a private repo then the account needs repo access, but at that point it's not a problem to support forks

**Comment by orta** [comment]
I know none of this is strictly in the JS docs yet, but I don't want to write comprehensive docs while Danger is not at v1 - still seeing lots of interesting ideas that make me want to change things

**Comment by agnivade** [comment]
> we recommend not giving any access rights to the user used for danger 

but in that case, will the user be able to comment on a PR ?

**Comment by orta** [comment]
Yep 👍

**Comment by agnivade** [comment]
Awesome ! Well, then I think I will revert back to my code :) . Thanks for the help !

**Comment by agnivade** [comment]
> Yep :+1:

Sorry @orta, that does not seem to be the case. I tried and it didn't work. See https://github.com/tldr-pages/tldr/pull/1261

**Comment by orta** [comment]
You should verify your [bot is not shadow banned](http://danger.systems/guides/faq.html#danger-is-not-posting-to-github-prs-but-everything-looks-fine)

This is what [we recommend for OSS projects](http://danger.systems/guides/getting_started.html#setting-up-an-access-token):

> We recommend giving the token the smallest scope possible. This means just public_repo, this scopes limits Danger’s abilities to just writing comments on OSS projects. Because the token can be quite easily be extracted from the CI environment, this minimizes the chance for bad actors to cause chaos with it.

If it was wrong, we'd have a lot of reports I'd expect
