### ISSUE TITLE
[BUG] GitHub action integration currently broken

### ISSUE THREAD

**Issue by mokagio** [danger/danger-js#1042]
**Describe the bug**
Between the 16th of May and the 13th of May, I noticed that running Danger via GitHub Actions didn't work anymore.

[This build](https://github.com/wordpress-mobile/WordPress-iOS/actions/runs/103546983) on the 13th of May passed while [this build](https://github.com/wordpress-mobile/WordPress-iOS/actions/runs/106523830), triggered on the same code, failed.

**To Reproduce**
Run Danger on GitHub Actions. Note, that's not the Danger GitHub Action, but Danger _on_ GitHub Action, i.e. `yarn run danger ci` from within a workflow in `.github/workflows/`.

Other than on the builds linked above, you can see the behavior in [this standalone repo](https://github.com/mokagio/danger-github-actions-examples/pull/2), where there's nothing but Danger set up.

**Cause**
Danger's code [uses the value of `GITHUB_URL` to build up the URL to use for the requests](https://github.com/danger/danger-js/blob/bb1e13587d207849943f02655148719741f74eb8/source/platforms/github/GitHubAPI.ts#L420): 

```ts
const baseUrl = process.env["DANGER_GITHUB_API_BASE_URL"] || process.env["GITHUB_URL"] || "https://api.github.com"
```

If the `GITHUB_URL` value is `https://github.com`, the request will 404.

- [`https://github.com/repos/mokagio/danger-github-actions-examples/pulls/1/commits`](https://github.com/repos/mokagio/danger-github-actions-examples/pulls/1/commits) 404s
- [`https://api.github.com/repos/mokagio/danger-github-actions-examples/pulls/1/commits`](https://api.github.com/repos/mokagio/danger-github-actions-examples/pulls/1/commits) succeeds

I think the cause is that the GitHub Actions environment changed the `GITHUB_URL` value from `https://api.github.com` to `https://github.com` recently. This can be verified by `echo $GITHUB_URL`, [like here](https://github.com/mokagio/danger-github-actions-examples/runs/687944250?check_suite_focus=true#step:8:7).

Looking at the [GitHub Actions changelog](https://github.blog/changelog/), I believe it might be due to the [14th of May deploy of the runner v2.262.1](https://github.blog/changelog/2020-05-14-github-actions-new-runner-release-v2-262-1).

I can't find an exact commit, but in [this PR](https://github.com/actions/runner/pull/482) @TingluoHuang and @ericsciple are discussing something along those lines. The PR got merged after the deploy 14th of May, so can't be the culprit.

**Workaround**
We can leverage the `DANGER_GITHUB_API_BASE_URL` to bypass the new value of `GITHUB_URL`. It works, as you can see [here](https://github.com/mokagio/danger-github-actions-examples/commit/dd6ef5be5ea8b8c0bb297096d78bdda9ae3ccf6b).

**Fix**
I'm tempted to say we should remove the `GITHUB_URL` check, but I'm not sure what other code or consumers depend on it.

Any input?

**Comment by orta** [comment]
Seems reasonable to switch - we don't tell people to use those env vars ourselves

**Comment by TingluoHuang** [comment]
@mokagio thanks for letting us know. We have noticed the new GITHUB_URL is causing a problem to customers and working on change the env to be GITHUB_SERVER_URL.  https://github.com/actions/runner/pull/482

@ericsciple FYI.

**Comment by mokagio** [comment]
Thanks for the feedback @TingluoHuang.

Gosh, isn't it awesome to be working in the open? Where you can see the code behind the tools you use and even get in touch with the people that build them showing them the code that interfaces with those tools and that's playing up? 

Love it ✨

**Comment by fbartho** [comment]
I'm going to close this ticket as I'm 90% sure it's resolved :) -- feel free to comment back if I was wrong!
