### ISSUE TITLE
[Feature] New message reporter type: "comment"

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#1055]
<details>
<summary>Recently, we did a big folder move in preparation for having monorepo. -- Expand for Context</summary>

A consequence of this was that *every file* in the repo was tagged as having been modified. -- This then caused danger-plugin-eslint to execute on *every file* -- but due to a configuration error, this caused DangerJS to hang until terminated by Github Actions (20mins later) as each file individually did a lot of processing before throwing errors.

</details>

This gave me a feature idea:

It would be neat if various plugins could add a message of type `comment` that would be clustered in a table just like our other messages. The key detail is that comments would be wrapped in an html comment `<!-- … -->` tag

I would use this to report how long each of my phases of my dangerfile were taking, that way I can either bump up limits, or focus on the right thing to optimize.

Would people be interested in this feature? @orta or somebody else?

**Comment by fbartho** [comment]
Related: #1056

**Comment by orta** [comment]
I'm very hesitant at expanding the messaging APIs. In part, this seems like something which can already be done via the `markdown` API. 

Yes, it wouldn't get sorted into a neat table, but I don't think that's enough to warrant the user-API scope expansion when you could throw in arbitrary JSON into a markdown comment.

**Comment by fbartho** [comment]
Sure! I guess this seemed like a nice expansion because hypothetically, this could be used to extract some metrics from Danger / Other plugins in a canonical way.

Also things like the version of Danger that was used etc.

But I see your point! -- Closing this feature request.
