### ISSUE TITLE
[BUG] Example Dangerfile does not parse with a vue-cli app

### ISSUE THREAD

**Issue by unikitty37** [danger/danger-js#1065]
**Describe the bug**
When using Danger with an app generated with vue-cli, the example Dangerfile from the documentation fails to parse with `SyntaxError: cannot use import statement outside a module`.

The output in the GitLab CI log:

```
$ yarn run danger ci --failOnErrors
yarn run v1.22.5
$ /builds/unikitty37/danger-demo/node_modules/.bin/danger ci --failOnErrors
Unable to evaluate the Dangerfile
 dangerfile.js:1
import "core-js/modules/es.array.join";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Object.requireFromString [as default] (/builds/unikitty37/danger-demo/node_modules/require-from-string/index.js:28:4)
    at Object.<anonymous> (/builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:144:63)
    at step (/builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at Object.exports.runDangerfileEnvironment (/builds/unikitty37/danger-demo/node_modules/danger/distribution/runner/runners/inline.js:105:136)
Failing the build, there is 1 fail.
Feedback: https://gitlab.com/unikitty37/danger-demo/merge_requests/1#note_404292895
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Fork https://gitlab.com/unikitty37/danger-demo, which uses the Dangerfile from https://danger.systems/js/guides/getting_started.html#creating-a-dangerfile
2. Configure the DANGER_GITLAB_API_TOKEN variable in the CI settings
3. Create an MR on the fork

**Expected behaviour**

The Dangerfile runs, and attaches a comment containing a list of the modified files.

**Screenshots**
n/a

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.4.0
| node             | 14.5.0
| yarn              | 1.22.4
| Operating System | Docker container `node:14-alpine`

**Additional context**
I'm not sure if Danger is transpiling correctly — vue-cli sets up projects with Babel by default, but https://danger.systems/js/tutorials/transpilation.html doesn't really give me much of a clue on how to debug this…

**Comment by orta** [comment]
In order for transpiration to not happen, all of this has to fail: https://github.com/danger/danger-js/blob/master/source/runner/runners/utils/transpiler.ts#L25-L74

Which I guess means it can't find the node_modules on your CI somehow - it does  look like you do a `yarn install` on the CI but maybe the order is important?

**Comment by YasiOnFire** [comment]
Same problem, similar setup (vue). Dind't work either in CI or locally. I've tried to debug the source provided by @orta, but with no luck. However just changed dangerfile to typescript and everything works in CI as well as locally.

**Comment by unikitty37** [comment]
Thanks, @YasiOnFire — I can confirm that renaming `dangerfile.js` to `dangerfile.ts` fixes the problem (see https://gitlab.com/unikitty37/danger-demo/-/merge_requests/2)

Still not sure why it's complaining about not being in a module when using a .js extension. I wonder if this is the same issue I'm seeing on other projects, which require Node 11 or earlier in order to avoid running into the same thing?

**Comment by unikitty37** [comment]
> In order for transpiration to not happen, all of this has to fail: https://github.com/danger/danger-js/blob/master/source/runner/runners/utils/transpiler.ts#L25-L74
> 
> Which I guess means it can't find the node_modules on your CI somehow - it does look like you do a `yarn install` on the CI but maybe the order is important?

I've enabled debug output, and it seems to be transpiling: https://gitlab.com/unikitty37/danger-demo/-/jobs/738460385

It still complains that it can't import outside a module, though.

**Comment by orta** [comment]
Are you expecting to be running danger through node with esmodules enabled? Typically people transpile the `import` to be a `require` in their babel setups.

**Comment by unikitty37** [comment]
I'm using the Babel config that was generated by vue-cli, which I assume doesn't do that: `babel.config.js` is just

```js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset',
  ],
}
```

`import` works fine in Vue components, so I assumed it was already being transpiled. What would I need to do to make it work?

**Comment by orta** [comment]
The "easy" answer is to switch the `import "xyz"` to a `require`, so that it runs in node without transpilation. Another answer is to find a way to make node [support the `import`](https://nodejs.org/api/esm.html#esm_modules_ecmascript_modules)s, perhaps there is a flag to enable it?

IMO, you shouldn't really mess with your babel config for Danger here. But, your babel config isn't set up to run in node out of the box, and so Danger re-using it doesn't work for you. Which is why folks using TypeScript work above.

**Comment by unikitty37** [comment]
Thanks — I couldn't work out the syntax for `require`, though. I ended up building a Docker container with the `danger` and `gitlab` gems installed, and switched to using the Ruby version…

**Comment by themojilla** [comment]
While the issue is already being closed if anyone struggles with this issue just add the join polyfills in the babel.config.js. this will do the trick.

`
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {
      polyfills: [
        'es.array.flat',
        'es.array.join',
      ],
    }],
  ],
};

`
