### ISSUE TITLE
tsconfig.json lookup issue

### ISSUE THREAD

**Issue by Igorbek** [danger/danger-js#1067]
Hi there,

It is sometimes problematic to have a dangerfile written in TS and maintain a `tsconfig.json` file that works with it when it is actually used for the project sources. The problem is that `danger` always looks for this file when `typescript` is present and does it from the current directory. In projects where tsconfigs must be different from dangerfile, there's no way to specify which one to use.

My proposal is to add two modifications:
- by default, look for `tsconfig.json` file from the directory where the dangerfile is located
  - if the current directory is not the same where the dangerfile, it climbs up to the current directory
- ability to specify `tsconfig.json` file location with `--typescript-project` CLI parameter

**Comment by orta** [comment]
Yeah, I like that first option, should need editing here: https://github.com/danger/danger-js/blob/master/source/runner/runners/utils/transpiler.ts#L83-L92 and a few tests 👍🏻

**Comment by Igorbek** [comment]
PR is up #1068
