### ISSUE TITLE
[BUG] CODEBUILD_SOURCE_VERSION is not a reliable way to check if the build is for a pull request

### ISSUE THREAD

**Issue by alexandermendes** [danger/danger-js#1077]
**Describe the bug**
This isn't exactly a danger bug, more CodeBuild weirdness. Having used CodeBuild quite a lot recently I have come across this issue before where the `CODEBUILD_SOURCE_VERSION` sometimes contains a reference to the PR in the format `pr/1` but actually not always. I don't really get the internal details of how it works, but basically CodeBuild seems to be a bit flaky with all things git.

I have had to get around this before by first checking if the `CODEBUILD_SOURCE_VERSION` contains a reference to the PR and if not doing a GitHub API search for the first PR containing the commit. This happens to be in Python, but I have it to hand so to give you an idea of wha I mean:

```python
def get_pull_request_number(api_repo_url, source_version):
    """Check if the build was triggered by a pull request.
    Note that sometimes the source version returned from CodeBuild contains the
    PR number in the format pr/123, but not always. Other times it may contain
    a commit hash. If we have the PR number, use that, otherwise try searching
    for the first PR that was opened containing the commit hash.
    """
    matches = re.findall(r'(?<=pr/)\d+', source_version)
    if len(matches):
        return matches[0]

    endpoint = '{0}/search/issues?q={1}'.format(api_repo_url.split('/repos/')[0], source_version)
    pull_requests = get(endpoint)

    items = pull_requests['items']
    return items[0]['number'] if len(items) else None
```

**To Reproduce**
I don't really know, I guess there must be a pattern but it currently seems pretty random to me 😅 Some build contain the right reference, some don't.

**Expected behavior**
Some consistent method of identifying whether or not the build is indeed for a PR. 

**Possible solutions**
- Make some kind of API request to check, as above. But then that probably isn't feasible with all of the possible version control providers.
- Add some kind of CLI flag to just force a run anyway. It could be up to the person implementing how to handle this for their env.
- Find some more reliable AWS method for identifying PRs...

I can try to help figure this out, but if anyone has any ideas that would be great too.

**Comment by orta** [comment]
We've had to do these kind of API looks before for different services too, so that could be the right answer
