### ISSUE TITLE
[BUG] There's no documentation on printing out the branch name

### ISSUE THREAD

**Issue by brandonjmckay** [danger/danger-js#1078]
**Describe the bug**
I've been trying to read through the reference and can't find any information on how to print out the PR's current branch name.
I know it's in there somewhere, but I can't for the life of me find it.
I've been trying to dig in to each branch of utils off the `danger` object, printing out the keys for each level in search of where this info is kept.

Apologies if this is the wrong venue, but I tried looking for a discord or something and I couldn't find anything.

**Expected behavior**
I'd expect to be able to search for `branch name` or `branchName` on the reference page to be able to find this info

**Comment by orta** [comment]
Looks like the `GitHubMergeRef` doesn't show in the JS reference '

You want the PR metadata which has a head ref: https://github.com/danger/danger-js/blob/master/source/danger.d.ts#L1350

**Comment by brandonjmckay** [comment]
Why doesn't the `GitHubMergeRef` show in the reference?

**Comment by brandonjmckay** [comment]
I also can't find any information on how to get the labels associated with the Github PR.
Isn't that available somewhere on the GithubDSL?

**Comment by stropho** [comment]
Just came across this. Maybe it will make it a bit easier for someone in the future.

```
const sourceBranch = danger.github.pr.head.ref;
const targetBranch = danger.github.pr.base.ref;
```
