### ISSUE TITLE
danger.git.head && danger.git.base

### ISSUE THREAD

**Issue by jamiebuilds** [danger/danger-js#1085]
It'd be super helpful if danger could report the commits that it is comparing against

This would allow you to shell out to `git` with the same information danger itself has

```js
execSync(`git show ${danger.git.head}:package.json`).toString()
execSync(`git show ${danger.git.base}:package.json`).toString()
```

Right now I tried to implement this with `danger.git.commits` and at least within `danger local` its not enough to do this correctly so I'm left to parse danger's argv myself

**Comment by orta** [comment]
I agree, this info _should_ already be available inside the PR metadata (as git is _not_ used to generate the diffs, the GH API is) - this info is definitely rattling around inside the system.
