### ISSUE TITLE
Natural language responses

### ISSUE THREAD

**Issue by mxstbr** [danger/danger-js#109]
I really like the style of the eslint bot, which responds like this:

<img width="722" alt="screen shot 2017-01-21 at 08 26 11" src="https://cloud.githubusercontent.com/assets/7525670/22172908/4acbb978-dfb3-11e6-8011-b8108c63f395.png">

I've noticed that with the "tabular" robotic style people sometimes ignore the bot. Making it respond in natural language would help with that, as we could make it seem like a normal user on the first glance.

Not sure what the API for this would look like, thought I'd kick off a discussion!

**Comment by KrauseFx** [comment]
Interesting idea, definitely something that could easily be achieved, you'd need an easy way to configure a `before` and `after` block. For the user it's also important that it's clear that it's a bot (just having bot in the name isn't enough in my experience)

For now, you can easily start using that kind of responses using the `markdown` method in your `Dangerfile`

**Comment by mxstbr** [comment]
So `markdown` is brilliant, there's only one tiny problem. If one solely uses `markdown`, one cannot make the build fail.

Calling `fail()` without a message renders the table above the markdown, and shows "Undefined" as the message, which is not optimal 😊

If `fail()` without a message failed the build but didn't output any table that'd be epic and would totally suffice for my use case!

**Comment by macklinu** [comment]
@mxstbr your changes from #116 have been published in `danger@0.11.1`. If you are able to update and let us know if using `markdown()` achieves your desired behavior, that'd be wonderful. 😃  

Are we interested in `before` and `after` blocks as suggested by @KrauseFx in https://github.com/danger/danger-js/issues/109#issuecomment-274298803?

**Comment by macklinu** [comment]
Closing this issue, but please let us know if you have suggestions on an API change that would help creating natural language responses. 😊
