### ISSUE TITLE
[Meta] Change Danger-JS's default branch from master-to-main

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#1102]
Danger-JS's default branch is `master` and many communities have moved away from that naming.

[Github has a whole repo with some of the rationale & instructions on how to make this change](https://github.com/github/renaming)

I know as danger-js is itself CI tooling, this might affect *lots* of automation scripts as well as Peril (https://github.com/danger/peril) so I'm not expecting this to take zero effort.

I just think it's our duty to do this, I propose `main` to stay aligned with Github's default, and identifying embedded assumptions about git's `default branch` name is probably valuable to DangerJS and etc.

Thoughts?

**Comment by orta** [comment]
I mean I guess, it's a pretty performative move so I'm not particularly pumped to deal with breakages from it.  Now that GitHub has official tooling we can try it, see what breaks and decide to revery or not.

**Comment by fbartho** [comment]
I totally understand the frustration about breakages from it. And I'd be happy to help in whatever way seems reasonable / you'd prefer.

That said, I sincerely think it's an important inclusive move, and I'd argue that while it might be conceptually a "big deal" for some people, I'd disagree that it's performative. It's not my place to judge what other people are harmed by, and particularly given the macro trends, that this is a good time to make this change.

Separately, I think that breakages triggered by this change were already an open weakness in Danger (and co.) repos, as the `default branch name` is a configurable property in git, so it's still worth it to discover these breakages.
