### ISSUE TITLE
[Support request] Is there support for getting Draft PR status?

### ISSUE THREAD

**Issue by arhont375** [danger/danger-js#1117]
How can I retrieve in danger information if current PR in `draft` state or not. Seems currently there is no such state in the `GitHubPRDSL`?

**Comment by orta** [comment]
`danger.pr` is the full JSON object for a PR, and only partially typed:

>  An exact copy of the PR's reference JSON. This interface has type'd the majority of it for tooling's sake, but any extra metadata which GitHub send will still be inside the JS object.

It should be in there, just check how you would do it with the rest API

**Comment by arhont375** [comment]
Oh, I see. Thank you for quick reply!
