### ISSUE TITLE
[QUESTION] Can I programmatically access the current DangerResults from my dangerfile?

### ISSUE THREAD

**Issue by TheENGR** [danger/danger-js#1147]
I want to be able to see at the end of the dangerfile if there were failures reported. I use a LOT of libraries and having them bubble it all up is unlikely.

**Comment by orta** [comment]
I don't think it's exposed in the user-facing API, but I wouldn't be against a function which gives a fresh copy of the danger results to the Dangerfile. I don't want to give access in a way which gives the ability to edit it.

**Comment by TheENGR** [comment]
I assume the "You Can Do This" is a request for a PR. 

Any chance you could point me generally in a good place to start?

**Comment by orta** [comment]
Took and looks and  I think it's already exposed: https://github.com/danger/danger-js/blob/main/source/runner/Dangerfile.ts#L91-L96

**Comment by TheENGR** [comment]
Sweet! So I can just call that like I would fail or warn to get the results?

**Comment by orta** [comment]
Yep
