### ISSUE TITLE
Compiled binary included in releases is incorrect

### ISSUE THREAD

**Issue by majd** [danger/danger-js#1170]
It seems that starting from version `10.1.0`, the binary that is included in all releases is not the most recent one and it's just the same compiled binary from version `10.1.0`.

Below is comparison between the binary downloaded from the latest release and version `10.1.0`

```zsh
$ ./danger-10_1_0 --version
10.1.0
$ ./danger-10_7_0 --version
10.1.0
$ sha1sum ./danger-10_1_0
3463f62125f6e1b1eb70d88e96e694d45a457968  ./danger-10_1_0
$ sha1sum ./danger-10_7_0
3463f62125f6e1b1eb70d88e96e694d45a457968  ./danger-10_7_0
```

**Comment by orta** [comment]
Agreed, no idea what's up there - I don't think I've changed anything

**Comment by erikkerber** [comment]
One more vote for this one 🙏🏼

**Comment by orta** [comment]
Maybe the Travis CI was doing some of the work which made this work?

**Comment by orta** [comment]
I think the package command wasn't running during deploys, I've manually added it now and checked the 11.0.2 release

```
> '/Users/ortatherox/Downloads/danger' --version
11.0.1
```

It did give me a gatekeeper error but I assume if folks are grabbing through brew that's handled for you

**Comment by majd** [comment]
Latest release marked as version 11.0.2 on GitHub shows version 11.0.1 when running `danger --version`.

**Comment by orta** [comment]
hah, I bet that's because it's in `before:bump` - https://github.com/danger/danger-js/blob/main/.release-it.json#L8

**Comment by majd** [comment]
I think #1206 should fix it.
