### ISSUE TITLE
[BUG] Danger in Github Actions marketplace is stuck on version 9.1.8 

### ISSUE THREAD

**Issue by DenisPalnitsky** [danger/danger-js#1172]
Github actions marketplace shows version 9.1.8 as the most recent one however version 10.7.0 is already available 
![image](https://user-images.githubusercontent.com/154290/139456778-50e5960c-f7f9-4041-b958-f8db86133904.png)

I ran into an issue with using 'danger.github.api.issues.get`  API on the old version so I believe there could be an incompatibility with Github API.

**Comment by orta** [comment]
Ah, yeah, our deploy automation doesn't do whatever is required for this. I'll do this manually now but I'm open to someone who uses this improving the deploy automation.

**Comment by orta** [comment]
I can't find a button for it, maybe their semver is bad and 9 comes after 10?

**Comment by fbartho** [comment]
I believe we pulled the Marketplace action for DangerJS in this ticket: https://github.com/danger/danger-js/issues/1038#issuecomment-1026632059
