### ISSUE TITLE
Fix failing Appveyor builds

### ISSUE THREAD

**Issue by macklinu** [danger/danger-js#118]
We've been noticing a lot of queued Appveyor builds that won't build when PRs are opened. All of the failing builds in the screenshot are due to Appveyor builds being cancelled when PRs are merged.

<img width="540" alt="screen shot 2017-01-29 at 9 21 04 pm" src="https://cloud.githubusercontent.com/assets/2344137/22410662/2d739730-e669-11e6-9c87-27deeb2240ae.png">

Is this an issue with our Appveyor config, or is this something we need to communicate to Appveyor? Either way, here's an issue for checking it out.

**Comment by orta** [comment]
I've been seeing this on Danger-rb too

**Comment by orta** [comment]
That spam you all just saw is me cancelling any queued up build

![screen shot 2017-01-30 at 3 02 29 pm](https://cloud.githubusercontent.com/assets/49038/22439344/40bd06fc-e6fd-11e6-9bd6-5b988effa57a.png)

https://twitter.com/_raghavrv/status/821816648697073664
https://twitter.com/appveyor/status/821821238192410624

**Comment by orta** [comment]
It's now building builds 
![screen shot 2017-01-30 at 3 05 39 pm](https://cloud.githubusercontent.com/assets/49038/22439431/92609726-e6fd-11e6-937f-8a2140ba73ca.png)

**Comment by macklinu** [comment]
Thanks for taking care of this, @orta! I opened #128 and Appveyor built successfully. Closing this.
