### ISSUE TITLE
[BUG] Body can apparently be null

### ISSUE THREAD

**Issue by G-Rath** [danger/danger-js#1185]
**Describe the bug**

I'm still looking into this myself, but it looks like `body` can be `null` at least for github PRs?

https://github.com/jest-community/eslint-plugin-jest/pull/1001

**To Reproduce**
1. Create a pull request with no body

**Expected behavior**

It to not error, since the types don't mark `body` as being nullable.

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 10.7.1
| node             | unsure
| npm              | unsure
| Operating System | `ubuntu-latest`

**Additional context**

https://github.com/jest-community/eslint-plugin-jest/blob/main/.github/workflows/lint.yml#L16-L23

**Comment by orta** [comment]
Sure, happy to have the types updated

**Comment by G-Rath** [comment]
Closing since this is fixed by #1191
