### ISSUE TITLE
[Maintenance][Github] @octokit/rest is on version 18, but DangerJS is on 16

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#1202]
**Describe the bug**
@octokit/rest is on version 18.12.0, but DangerJS is referencing Octokit 16

**Expected behavior**
For maintenance reasons, we should upgrade DangerJS to the 18.x API line, but this is a breaking change for DangerJS consumers, and potentially for plugins

@orta is this something we're ready to do, or do we need to hold off for some reason?

**Comment by fbartho** [comment]
https://github.com/octokit/rest.js/

**Comment by orta** [comment]
I don't go out of my way to update this sort of thing, other folks are welcome to do it 👍🏻
