### ISSUE TITLE
[BUG][BitBucket] danger with -d path/to/dangerfile.ts not removing previous comments 

### ISSUE THREAD

**Issue by felipeuematsu** [danger/danger-js#1208]
**Describe the bug**

When using the danger command with the -d argument, the resulting comments doesn't edit or delete the previous comments, even with the --remove-previous-comment argument

**To Reproduce**
1. have your repository in bitbucket cloud
2. have your dangerfile in some subdir
3. run danger with the -d path/to/dangerfile.ts command 

**Expected behavior**

The previous comments on bitbucket PRs should be edited or removed when adding a new comment

**Screenshots**
![image](https://user-images.githubusercontent.com/51753940/154317229-37ded6e4-6d4f-4978-99de-3a4c5b9f523c.png)
command used: yarn danger ci --remove-previous-comments -d danger-git/dangerfile.ts
**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | danger@11.0.2
| node             | v14.17.5
| Operating System | [docker image](http://docker.io/atlassian/default-image@sha256:edf4bd880adf9e7f7677094f7a1d944524c7f98e939550bc152523c5cf6080ff)

**Additional context**
Not working in two repositories in bitbucket cloud, not sure about github

**Comment by fbartho** [comment]
I have the latest DangerJS configured to use multiple paths on Github, and have no problem updating/removing comments.

I recommend investigating this source-file: https://github.com/danger/danger-js/blob/main/source/platforms/BitBucketCloud.ts (Or the imported files)

**Comment by felipeuematsu** [comment]
Found the issue, the UUID had a typo at the repos where the issue was happening and had the -d param
