### ISSUE TITLE
[BUG] Bitbucket cloud fails to get DSL in 1 second

### ISSUE THREAD

**Issue by OJPARKINSON** [danger/danger-js#1276]
**Describe the bug**
Bitbucket is hitting the 1 secound timeout before it is able to get the DSL, the timeout is there so the CI doesn't hang if broken.

**To Reproduce**
1. Setup for bitbucket cloud and codebuild 
2. run danger ci
3. recieve "Timeout: Failed to get the Danger DSL after 1 second"

**Expected behavior**
After upping the timout to 2000ms it gives enough time to get the DSL.

`source/commands/danger-runner.ts:86`

The easy fix is to just up the timeout but I'm not sure how that will effect other danger setups. Could possibly pass the timeout as config?

**Comment by orta** [comment]
Yeah, 1 second seems actually really low to me - I'd happily take a PR making that something like 10s

**Comment by OJPARKINSON** [comment]
Great, I'll get one in this afternoon.

**Comment by orta** [comment]
This shipped!
