### ISSUE TITLE
[Feature] Create arm64 binary for Homebrew

### ISSUE THREAD

**Issue by 417-72KI** [danger/danger-js#1282]
danger-js binaries installed via Homebrew are built in x86_64 architecture.

It causes https://github.com/danger/swift/issues/464.

We need arm64 binary for M1 macs.

**Comment by fbartho** [comment]
I admit I’m not entirely sure I understand.

Do we pre-build DangerJS binaries? (Why?) Can’t they be built on the end-user’s system, using their local processor architecture?

**Comment by 417-72KI** [comment]
[Danger-Swift in Homebrew requires Danger-JS as dependency](https://github.com/danger/homebrew-tap/blob/master/danger-swift.rb#L12), and [it seems to install pre-built binary](https://github.com/danger/homebrew-tap/blob/master/danger-js.rb).

I'm not familiar with npm, and don't know how to build binary from npm package even if there are other ways to install😔

**Comment by orta** [comment]
Happy to have someone move the build infra into github actions and making it builds both binaries, right now it's effort enough to boot up an old mac to even make the x86 ones

**Comment by jesus-mg-ios** [comment]
Any update?

**Comment by 417-72KI** [comment]
Resolved by https://github.com/danger/danger-js/pull/1342 !
