### ISSUE TITLE
How to remove build status from PR build?

### ISSUE THREAD

**Issue by jayveersolanki** [danger/danger-js#1293]
Hello,

I don't want PR build status in PR so how to remove build status from PR?
I have attached screenshot below kindly refer that.

![image](https://user-images.githubusercontent.com/11172341/181497028-7b02bb84-c65a-4e72-9843-3b184662b18f.png)

**Comment by orta** [comment]
There might be an env var for this which someone may have added, but it's not really something I think we need an exposed option for. You're welcome to check the code to see.

**Comment by jayveersolanki** [comment]
> There might be an env var for this which someone may have added, but it's not really something I think we need an exposed option for. You're welcome to check the code to see.

Thank you for your response.

Perhaps I have tried **BB_KEY=***** npm run danger ci -f --no-publish-check** with this command to remove the build status from the bitbucket server but it didn't work.

Can you please help me to resolve this issue?

**Comment by jayveersolanki** [comment]
> BB_KEY=*** npm run danger ci -f --no-publish-check

Issu

> > There might be an env var for this which someone may have added, but it's not really something I think we need an exposed option for. You're welcome to check the code to see.
> 
> Thank you for your response.
> 
> Perhaps I have tried `BB_KEY=*** npm run danger ci -f --no-publish-check` command to remove the build status from the bitbucket server while running ci build but it didn't work.
> 
> Can you please help me to resolve this issue?

Issue resolved using `npx danger ci -f --no-publish-check` command.
