### ISSUE TITLE
Why DangerJS comments not showing on top of the PR?

### ISSUE THREAD

**Issue by jayveersolanki** [danger/danger-js#1294]
Hello,

I have faced issues while running the CI/CD pipeline with dangerJS implementation.

**Issue1:**
When I run pipeline danger js not put comments on top of all comments.

**Issue2:**
DangerJS does not update commits in comments(See below in attached screenshot)

**Issue3:**
If the build running multiple times for the same commit then why dangerJS do not update the same comments again with latest date and time.

![image](https://user-images.githubusercontent.com/11172341/181503343-9bb0dcbf-7629-42fd-acba-f1c7397a8cc2.png)

**Comment by orta** [comment]
Perhaps your API key does not have permission too edit it's own posts? I think all implementations should be editing their own comments but maybe that's a constrain specific to whatever platform you're using

**Comment by jayveersolanki** [comment]
> Perhaps your API key does not have permission too edit it's own posts? I think all implementations should be editing their own comments but maybe that's a constrain specific to whatever platform you're using

Thank you for your response.

I have created admin-level API key and every time I change something and later on create a build then I am able to modify my own comment using dangerJS

**Comment by jayveersolanki** [comment]
> Hello,
> 
> I have faced issues while running the CI/CD pipeline with dangerJS implementation.
> 
> **Issue1:** When I run pipeline danger js not put comments on top of all comments.
> 
> **Issue2:** DangerJS does not update commits in comments(See below in attached screenshot)
> 
> **Issue3:** If the build running multiple times for the same commit then why dangerJS do not update the same comments again with latest date and time.
> 
> ![image](https://user-images.githubusercontent.com/11172341/181503343-9bb0dcbf-7629-42fd-acba-f1c7397a8cc2.png)

Issue resolve using `--removePreviousComments` param.
