### ISSUE TITLE
[BUG] Unable to run danger locally zsh: permission denied: danger

### ISSUE THREAD

**Issue by theScud** [danger/danger-js#1300]
**Describe the bug**
Installed Danger globally  using both YARN and npm. unable to run the danger command and Danger swift says DangerJS not installed.

Not an NPM issue as i am able run other global packages like commitzen etc 

**To Reproduce**
1. install danger via npm/yarn 
2. run command danger in terminal

**Expected behavior**
danger js must run with any output - not permissions denied

**Screenshots**
Danger js permission denied
<img width="752" alt="Screenshot 2022-08-08 at 1 05 47 PM" src="https://user-images.githubusercontent.com/1806148/183364624-b49b4bdf-0478-4add-b3fb-f6624d1cc9c6.png">
Commitzen working as expected
<img width="1028" alt="Screenshot 2022-08-08 at 1 13 59 PM" src="https://user-images.githubusercontent.com/1806148/183366031-aab844d8-c8e0-4b8e-9641-712fdc22b051.png">

**Your Environment**
M1 Pro mac Book Pro 
macOS  Monterey 12.4
nvm , yarn installed 
global modules are under a separate user folder User/Uesr.Name/.npm

 | software         | version
| ---------------- | -------
| danger.js          | 11.1.1
| node             | 18.7.0,  system
| npm              | 8.15.0
| yarn              | 1.22.19
| Operating System | macOS 

**Additional context**

could someone help with issue?

**Comment by orta** [comment]
No idea, sounds like your terminal setup seems off - try looking at commands like `which` to figure out what is going on. That said, outside of yarn/pnpm etc, I'd never recommend installing tools globally, you should be scoping them to the project you are working on.

**Comment by theScud** [comment]
Looks like it was a zsh issue. completely flushed my node installation and reinstalled its working right as rain.
