### ISSUE TITLE
[BUG] Gitlab Package Warning

### ISSUE THREAD

**Issue by uchihamalolan** [danger/danger-js#1301]
**Describe the bug**
When I do `pnpm install danger`, I get the following warning about "gitlab" package

```bash
WARN  deprecated gitlab@10.2.1: The gitlab package has found a new home in the @gitbeaker organization. For the latest gitlab node library, check out @gitbeaker/node. A full list of the features can be found here: https://github.com/jdalrymple/gitbeaker#readme
```

| software         | version
| ---------------- | -------
| danger.js        | 11.1.1
| node             | 16.15.1
| pnpm             | 7.9.0
| Operating System | MacOS Montrey (12.5)

**Comment by orta** [comment]
Thanks, you're welcome to port us over 👍🏻

**Comment by glensc** [comment]
this is done via https://github.com/danger/danger-js/pull/1318
