### ISSUE TITLE
[BUG] git missing when using Github Action

### ISSUE THREAD

**Issue by lucascurti** [danger/danger-js#1308]
**Describe the bug**
We were using the `danger` package to run some checks in the CI and recently migrated to using the Github Action. Everything is working as it should except for a check that's using `simple-git` that was working before migration to the action. The problem is that `simple-git` is failing because it can't find the `git` command in the system. Note this is not a problem with `simple-git` and `danger` is also throwing when trying to use other system commands such as `which`.

Any workaround to make `git` from the OS available for `danger` in the github action?

**To Reproduce**
1. Setup danger as a Github Action
2. In danger, try to run any `simple-git` action or use `execa` to run a system command (`execa("which", ["git"])`)

`which-git` is running `which git`.
```
Error:  Error: Command failed with exit code 1: yarn which-git
    at makeError (/github/workspace/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/github/workspace/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  shortMessage: 'Command failed with exit code 1: yarn which-git',
  command: 'yarn which-git',
  escapedCommand: 'yarn which-git',
  exitCode: 1,
  signal: ,
  signalDescription: ,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Expected behavior**
system commands should be available when using danger github action.

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.1.1
| node             | 16.13.0
| npm              | 8.3.1
| Operating System | Linux

**Comment by orta** [comment]
Personally would recommend against using the github action version of Danger, and run it like a normal command on your CI

**Comment by lucascurti** [comment]
Thanks @orta 🙌  I'll close the issue and we will go back to using it as a normal command.
