### ISSUE TITLE
[BUG] Please please please follow semver practices

### ISSUE THREAD

**Issue by airtonix** [danger/danger-js#1309]
First off, I love DangerJs, it's amazing. I do appreciate all the work the contributors have put into it. I get that this is open source software and if we want effective change we should contribute with PRs and Sponsorship.

Can we please practice more strict approaches to patch bumps and breaking changes?

Going from 11.0.2 to 11.0.4 involved what I would consider to be breaking changes. Specifically : https://github.com/danger/danger-js/compare/11.0.2...11.0.4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R88-R90 changing the required nodejs version from something to 14.x.

Yes I understand you're doing your duty to drag us mouth breathing peasants into the future etc etc.

But I would have expected breaking changes to not be released on a patch bump.

I have projects out there that right now are on 11.0.2 but need a fix in 11.0.4, but can't upgrade their nodejs version due to prohibitive cost of required time to do so.

So yeah, my options are now (in order): 

- raise the issue here
- fork dangerjs at v11.0.2 and cherry pick https://github.com/danger/danger-js/pull/1272
- publish it to npm under some heretical name

![image](https://user-images.githubusercontent.com/61225/187559272-e62ef900-4a79-46bc-bc5b-e8a4c866cc4c.png)

**Comment by orta** [comment]
It's usually the transitive dependencies, I have no intention of adding new things to danger which require newer node versions, but that said this is largely not actionable and so I'm gonna close it. I'm not precious about semver majors (which is why we're at v11)

**Comment by fbartho** [comment]
@airtonix In addition to @orta’s comments — DangerJS was already NodeJS `>14.x-only`, it just wasn’t tagged as such in the `package.json::engines` field.  Like @orta said, transitive dependencies control much of that decision.

If your stuff was working with <14 at that time _it was only working by accident, or you weren’t using certain features that would have exploded_

**Comment by airtonix** [comment]
Ok.

I guess that now you have the engines field, that you'll bump to a new major version when that field changes.
