### ISSUE TITLE
[BUG] addLabels not a function

### ISSUE THREAD

**Issue by ivankatliarchuk** [danger/danger-js#1314]
**Describe the bug**

Probably not a bug, I might be missing something.
According to this [PR](https://github.com/danger/danger-js/pull/1139), following should just work
```
// Add labels
danger.gitlab.api.addLabels('Label 1', 'Label 2');
```

However its not a case.

**To Reproduce**
```js
const { danger } = require('danger');
danger.gitlab.api.addLabels('Label 1', 'Label 2');
```

`TypeError: addLabels is not a function at beforeCompletion (dangerfile.js:2:9)`

For ts, same result
```ts
import { danger } from "danger";
danger.gitlab.api.addLabels('Label 1', 'Label 2');
```

`TypeError: addLabels is not a function`

**Expected behavior**
It should update labels.

Current approach
```js
const addLabels = async (prId, input) => {
  const mrLabels = danger.gitlab.mr.labels
  const changes = [...mrLabels, ...input.filter(el => !mrLabels.includes(el, 0))];
  if (mrLabels.length != changes.length) {
    const mr = await danger.gitlab.api.MergeRequests.edit(repo, prId, { labels: [...mrLabels, ...input] })
    console.log(`updated labels '${changes}' for mr '${prId}'`)
  }
}
```

Labels updated.

**Screenshots**
![Screenshot 2022-09-25 at 13 21 41](https://user-images.githubusercontent.com/5395690/192148400-a3bf87c7-df8c-4ce0-a4b7-91a409e89dd3.png)

**Your Environment**

 | software      | version
| -------------| -------
| danger.js      | 11.1.2
| node             | v14.16.1) and v18.9.0 
| npm              | (npm@6.14.12 and (npm v8.19.1)
| Operating System | Macos and Ubuntu(Docker)

**Comment by orta** [comment]
I don't think those are on that object (I think the PR had the wrong text) try without the `.api` (or check the typescript types

**Comment by ivankatliarchuk** [comment]
I went through the code. 
`danger.gitlab.api` actually returns `InstanceType<typeof Gitlab>`. Not sure if was it intentional or not, but as a result, functions `addLabels` and `removeLabels` not used anywhere in the library, would assume not in use outide of it too.

Does it sound allright if I make them available through `danger.gitlab.uits.addLabels` ?

**Comment by orta** [comment]
I think it is available as `danger.gitlab.addLabels` judging on the code

**Comment by ivankatliarchuk** [comment]
```
console.log(Object.getOwnPropertyNames(danger.gitlab).filter(function (p) {
  return typeof danger.gitlab[p] === 'function';
}));
```

output 

```
[ 'metadata', 'mr', 'commits', 'approvals', 'utils', 'api' ]
```

Not the end of the world

**Comment by stillborn333** [comment]
/_matrix/client/r0/auth/<auth type>/fallback/web?session=<session

**Comment by ivankatliarchuk** [comment]
Looks like there is an inconstitency in the code e.g. Github https://github.com/danger/danger-js/issues/1008 
```
danger.github.utils.createOrAddLabel
```

While Gitlab does not have anything like `danger.gitlab.uits.createOrAddLabel`

**Comment by glensc** [comment]
This should add the two methods under utils:
- https://github.com/danger/danger-js/pull/1353

but imho, this is a mess, why need to map, why not expose the whole "api"?

**Comment by glensc** [comment]
The actual breakage was from this commit by @orta:
- e8d20521270e283df8572c103eb330d622ab04bd

Find `source/platforms/GitLab.ts` file in the diff because the commit is huge

**Comment by glensc** [comment]
That commit links to https://github.com/danger/danger-js/pull/1192 that has no context, at all, but 250 commits spanning multiple releases and merges. or what the "improper" was. imho **now** the dsl exposed is improper raw GitLab class `import { Gitlab } from "@gitbeaker/node"` rather danger-js GitLabAPI class

**Comment by glensc** [comment]
Changelog is recorded in such way that the same person added addLabels/removeLabels and broke them in subsequent pr?

```
# 10.6.6
Fix for supporting Bitbucket Server personal repositories
GitLab: Added GitLabApi to danger.gitlab.api. - [@shyim]
GitLab: Added label helper functions to danger.gitlab.api.addLabels and danger.gitlab.api.removeLabels. - [@shyim]
```

cc @shyim
