### ISSUE TITLE
[BUG] Inspect danger local

### ISSUE THREAD

**Issue by MarceloPrado** [danger/danger-js#1316]
**Describe the bug**
For the past day, I've been trying to find a way to hook a Node debugger into `danger local` child process. Reading [this](https://github.com/danger/danger-js/blob/main/source/commands/utils/runDangerSubprocess.ts#L54) line, my initial reaction was to simply add the node `--inspect flag` when invoking the CLI: `yarn danger local --inspect`. 

However, this adds the flag at the wrong position. Debugger flags such as `--inspect` and `--inspect-brk` need to be added right after `node`, and before the arguments. My first attempt caused Danger to spawn a process with:
```
node ~/[...path]/node_modules/danger/distribution/commands/danger-local.js --inspect
```

Clearly, this didn't work. I then tried adding a CLI flag that injects the `--inspect` param in the right position. Here's an early [draft of the implementation](https://github.com/danger/danger-js/compare/main...MarceloPrado:danger-js:node-debugger?expand=1). With these changes, I'm able to add breakpoints and debug danger-js code. However, it still doesn't enable me to debug my local dangerfile (the Node debugger doesn't stop at my breakpoints).

Am I missing something? Would love some assistance 🙂. Digging through old issues and PRs, I saw danger-js once had a `--repl` flag that did something similar. #452 had to remove it, but @orta mentioned it was possible to use `--inspect` as an alternative. I'm curious on how to make this work.

Thanks for the great project! 
And a random comment: I love the design of your website, it's very unique. A quick quality of life win would be adding a search bar - you could leverage the free Algolia's [DocSearch](https://docsearch.algolia.com/).

**Comment by orta** [comment]
I think the solution would be in `dangerRunToRunnerCLI` as you were looking (you can see my comments in there where I give an example of how I was doing it manually. I think the way you were going is probably the right way to do it. 

Personally though, I'd run it in VS Code via the JS inspector console ( https://code.visualstudio.com/docs/nodejs/nodejs-debugging )  and add ` debugger` to the first line of the dangerfile

**Comment by MarceloPrado** [comment]
Thanks orta, I wasn't familiar with the JS Debug Terminal! This is everything I need for now.
