### ISSUE TITLE
[Feature Request]: GitHub check run annotations

### ISSUE THREAD

**Issue by moltar** [danger/danger-js#1328]
Right now, passing the filename and line number opens a discussion on GitHub for the specific line. I think this is a really cool feature and certainly has some uses.

But I am also thinking that there might be times when you don't want a discussion, and simply want to highlight certain problem areas of the code with a note.

GitHub has a feature called "annotations" ([announced in 2018](https://github.blog/2018-12-14-introducing-check-runs-and-annotations/)) that is already popular with tools like ESLint and Jest that can leave notes on your PR in specific locations.

I think this would be great feature to add!

**Comment by moltar** [comment]
> it's _barely_ in scope for Danger

Could you please elaborate on this point? I am a light danger user, so I might be missing some context.

I thought convenience functions such as `fail` and `warn` do exactly that, but they use a GitHub comment functionality.

How about `annotate` function? Or perhaps, an optional enum as the last positional arg to `warn` that can specify the type of message?

```ts
enum MessageType {
  COMMENT,
  ANNOTATION
}

warn('foo', file, 123, MessageType.ANNOTATION)
```

**Comment by orta** [comment]
Ah, you linked to a specific VS extension - we support github checks as an output on github PRs. It's available as a CLI toggle - https://github.com/danger/danger-js/blob/main/CHANGELOG.md#701

Wouldn't recommend it though FWIW, but you can figure if it works well for you 👍🏻

**Comment by moltar** [comment]
> you linked to a specific VS extension

Ah oopsy, that was from a quick google result. Sorry for the confusion. Indeed meant just the GH feature of annotations nothing to do with VSC.

> Wouldn't recommend it though 

Do you mind elaborating as to why?

Thank you!
