### ISSUE TITLE
[Bug]: Blank issue template links to `spectrum.chat`

### ISSUE THREAD

**Issue by moltar** [danger/danger-js#1329]
Start a new issue: https://github.com/danger/danger-js/issues/new

The issue placeholder contains the following text:

```
Hello there, thanks for the issue.

If this is a support request, e.g:

* How do I ...?
* Does Danger support ...?
* Is there a plugin for ...?

Please use https://spectrum.chat/danger
```

The link to `https://spectrum.chat/danger` no longer exists, as spectrum had shut down a while ago.

**Comment by orta** [comment]
thanks, dropped them
