### ISSUE TITLE
[BUG] Can't skip `Found no issues or messages from Danger. Removing any existing messages on Gitlab.`

### ISSUE THREAD

**Issue by ivankatliarchuk** [danger/danger-js#1330]
**Describe the bug**

***Current setup***
We are running code reviews at a scale. Single repository with Danger job running. The job is triggered through a webhook on merge requests create/update and etc across the whole organisation.
Hope the diagrams express/explain it clearly. 
To speed up our review, and do not waist time if review was already given, our danger file looks like this

```js
const { danger, message, warn, fail, markdow } = require('danger');

if (isNotToSkipReview()) {
  ... danger magic ...
}
```

`skipReview` function does quick checks, they not relevant to a current problem. We are running code reviews at a scale. Basically there are rules to decide where or not to run a code review check

The issue is [here]()
```js
if (!hasMessages || this.options.removePreviousComments) {
  if (!hasMessages) {
    this.log(`Found no issues or messages from Danger. Removing any existing messages on ${this.platform.name}.`)
  } else {
    this.log(`'removePreviousComments' option specified. Removing any existing messages on ${this.platform.name}.`)
  }
  await this.platform.deleteMainComment(dangerID)
  const previousComments = await this.platform.getInlineComments(dangerID)
  for (const comment of previousComments) {
    if (comment && comment.ownedByDanger) {
      await this.deleteInlineComment(comment)
    }
  }
}
```

Basically when we skip a review, there are no messages, and previous comment is deleted.
`Found no issues or messages from Danger. Removing any existing messages on Gitlab.`

I understand a behaviour. Would it be possible to add an extra flag e.g. `skipCommentDeleetion`, `reuseCurrentComment` or something along this lines?

***How its currently solved***

 Two jobs running. First check whether or not we should skip a review, and next job commence a review.
Would be nice to have a way to skip a removal too, probably even from within a danger at runtime

**To Reproduce**

Can provide some information on requeset. Gitlab and Gitlab CI access is required.

**Expected behavior**

Command `danger ci` does not remove previous Danger comments if there are no issues or messages.

**Screenshots**

Architecture 
![Automate Code Review](https://user-images.githubusercontent.com/5395690/197199570-ec61c279-60ba-4556-8255-77b2c9eb6bb5.jpg)

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js        | 11.1.4
| node             | 18
| npm              | 8.19.1
| Operating System | Alpine(Docker)

**Additional context**

If there is a benefit, happy to create a documentation on hove to bake `Danger+Gitlab+WebHooks` at scale when issue resolved

**Comment by orta** [comment]
Looks like you're [re-creating Peril](https://github.com/danger/peril/) but have you considered setting a unique danger id per run? I'd imagine it would have the effect you want

**Comment by ivankatliarchuk** [comment]
I tested it, its solves a problem, it kind of does, but creates a new one. As of now, no deletion of comments happens, but it creates every time a new Danger comment and there is no way to keep single comment

**Comment by orta** [comment]
Fair, I think I'd be OK with this as an environment variable and tests to make sure it doesn't break - it's such a niche case that I don't think anyone else has any use for it
