### ISSUE TITLE
[BUG] Error:  undefined  when running using Docker

### ISSUE THREAD

**Issue by oleghalin** [danger/danger-js#1333]
**Describe the bug**
I run danger in docker container inside of Teamcity. When i trying to run it locally everything works well, but when i run on CI i see this error

```
Error:  undefined 
```

**To Reproduce**
1.  Setup Danger 
2. Run Locally
4.  Run in Teamcity agent

**Expected behavior**
Review commented

**Screenshots**
<img width="615" alt="image" src="https://user-images.githubusercontent.com/9086983/198887485-12eaa0fe-3473-4d89-af00-d7ba3ddfe1d3.png">

As shown on screenshot PR check was failed which is correct, but when trying to submit comment it fails.

**Comment by orta** [comment]
I'd recommend digging into the source code for this, hard to say if this is a vm thing because I've never seen it before

**Comment by oleghalin** [comment]
Issue was related to cloudflare waf
