### ISSUE TITLE
[BUG] Duplicate report coments on GitHub actions if we use a custom CI bot token

### ISSUE THREAD

**Issue by snitin315** [danger/danger-js#1347]
**Describe the bug**

Github-actions[bot] user id is hardcoded in the codebase:

https://github.com/danger/danger-js/blob/47dfcfa1bb454199452ab021bcbd594eb1efa8f1/source/platforms/github/GitHubAPI.ts#L133-L139

So if we do not use Github-actions[bot] on CI we get duplicate comments as the following condition is always false:
https://github.com/danger/danger-js/blob/47dfcfa1bb454199452ab021bcbd594eb1efa8f1/source/platforms/github/GitHubAPI.ts#L93

As a result, we get duplicate comments on the PR.

We have a separate bot account on GitHub which we use to perform all the automation via GitHub actions, hence not using the default `secrets.GITHUB_TOKEN` on CI.

**To Reproduce**

Run dangerJS on GitHub actions with a token other than `secrets.GITHUB_TOKEN`

**Expected behavior**

It should edit the previous comment.

**Screenshots**

<img width="1008" alt="Screenshot 2023-01-09 at 8 31 24 AM" src="https://user-images.githubusercontent.com/46647141/211234640-bd9c8ff3-df95-4db3-aa5f-1f473ea63091.png">

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.2.1 |
| node             | 18 |
| npm              | 8 |
| Operating System | |

**Additional context**

Allow a new env variable `USE_CUSTOM_CI_TOKEN` or something similar.

**Comment by orta** [comment]
I agree that your logic is pretty sound, but the thing that doesn't fit for me is that almost everywhere I use danger it's GitHub Actions + a custom token - for example here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63851#issuecomment-1375044192

I think it's likely you're not using `DANGER_GITHUB_API_TOKEN` which takes priority at a guess

**Comment by snitin315** [comment]
@orta So earlier I was using `GITHUB_TOKEN: custom-token` which I updated to `DANGER_GITHUB_API_TOKEN: custom-token` and I'm still seeing duplicate comments.

In the example you showed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63851#issuecomment-1375044192, it seems to be using danger v10.1.1 whereas the above logic was introduced later. I updated the danger-js package on CI and was able to reproduce:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63854#issuecomment-1375387521
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63854#issuecomment-1375389305

<img width="986" alt="Screenshot 2023-01-09 at 3 51 41 PM" src="https://user-images.githubusercontent.com/46647141/211286514-9b3b1e88-77f7-48f1-a1a9-833a3e17466e.png">

**Comment by mrclrchtr** [comment]
We have the same problem. We updated today from 11.1.4 to 11.2.1 and since then the bot writes new comments instead of editing old ones.

**Comment by orta** [comment]
https://github.com/danger/danger-js/pull/1337 feels like the culprit to me

**Comment by snitin315** [comment]
@orta Should we revert the PR then?

**Comment by martinerko** [comment]
@orta I am experiencing the same issue, is there any plan to revert the problematic commit?

**Comment by orta** [comment]
I figured someone would have a think and see if my guess was correct - but I'm fine with just reverting it

**Comment by orta** [comment]
Alright, that's shipped

**Comment by snitin315** [comment]
@orta Thanks. I just updated to v11.2.2 and it has fixed the issue.
