### ISSUE TITLE
Opinion time: Test file naming

### ISSUE THREAD

**Issue by orta** [danger/danger-js#135]
Hello there, in [Peril](https://github.com/danger/peril) I started adding an underscore before the name of a test file so that it shows lower in the file browser when doing an open quickly

![screen shot 2017-01-31 at 9 53 10 am](https://cloud.githubusercontent.com/assets/49038/22469771/17b5f41e-e79b-11e6-9b29-2552460086dd.png)

Was thinking of making this change in Danger (and making a rule in the Dangerfile), anyone got opinions on better ideas or think as-is is 👍 ?

**Comment by orta** [comment]
Related, I keep calling my new test files `*.tests.ts` :D

**Comment by tivac** [comment]
I'm 100% behind `*.tests.<ext>`, I think leading underscores are a little ugly but that's very subjective.

**Comment by macklinu** [comment]
I also am not big on the leading underscores, but that's just my opinion.

In the end, though, I prefer consistency and what works for the people building the software as a whole rather than just my personal opinion, so if we can come to something we agree on and perhaps enforce it with a Danger rule, I'm for it 100%. ❤️

**Comment by macklinu** [comment]
It looks like the codebase is using the following convention for the most part:

- Tests live in a subdirectory called `_tests` located in the same directory as its source file. Example: `source/ci_source/providers/Drone.ts` and `source/ci_source/providers/_tests/_drone.test.ts`
- Test file names begin with an underscore
- Test file names have the file extension `.test.ts`

Are we up for standardizing on that? Perhaps we could add documentation to the README and a danger rule to conform to that?

**Comment by orta** [comment]
Yep - and great ideas 👍
