### ISSUE TITLE
[BUG] substr is deprecated

### ISSUE THREAD

**Issue by david-allan-jones** [danger/danger-js#1400]
**Describe the bug**
There is a call to the deprecated `String.prototype.substr` inside of github issue template file.

`/source/runner/templates/githubIssueTemplate.ts`

**To Reproduce**
I'm currently not aware of any runtime that doesn't still support this function, but it would be wise to remove it in case support gets dropped on some runtimes.

**Expected behavior**

This should be replaced with a different function like `String.prototype.substring`.

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11
| node             | 18
| npm              | n/a
| Operating System | Ubuntu

**Comment by orta** [comment]
Seems reasonable, you're welcome to take a look at it

**Comment by david-allan-jones** [comment]
PR: https://github.com/danger/danger-js/pull/1401

**Comment by igorkamyshev** [comment]
Should it be closed since #1401 is merged? 🤔

**Comment by fbartho** [comment]
Thanks @igorkamyshev
