### ISSUE TITLE
[BUG] Danger posting separate comment for each warning on GitHub

### ISSUE THREAD

**Issue by renspoesse** [danger/danger-js#1413]
**Describe the bug**
When calling `warn()` with the `file` and `line` parameters, Danger posts an inline PR comment for each violation, even though the reference documentation suggests that `warn()` outputs warnings in a single HTML table.

I'd like to get all warnings displayed in a single comment, where each warning still links to the file and line number it affects.

**To Reproduce**
1. `warn("Something's not right", "src/TEST.md", 5);`
2. `warn("Something's not right", "src/TEST.md", 6);`
3. `warn("Something's not right", "src/TEST.md", 7);`

This generates 3 comments on the GitHub PR.

**Expected behavior**

According to https://danger.systems/js/reference, it should show a single HTML table. Something like this (taken from the Ruby version of Danger we use in another repository):

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          4 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/org/repo/blob/hash/path-to-file.swift#L211">path-to-file.swift#L211</a> - 'CGFloat.contentWidthFactor' is deprecated. Use the '.contentWidthFactor()' method on your view controller.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/org/repo/blob/hash/path-to-file.swift#L212">path-to-file.swift#L212</a> - 'CGFloat.contentWidthFactor' is deprecated. Use the '.contentWidthFactor()' method on your view controller.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/org/repo/blob/hash/path-to-file.swift#L213">path-to-file.swift#L213</a> - 'CGFloat.contentWidthFactor' is deprecated. Use the '.contentWidthFactor()' method on your view controller.</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><a href="https://github.com/org/repo/blob/hash/path-to-file.swift#L214">path-to-file.swift#L214</a> - 'CGFloat.contentWidthFactor' is deprecated. Use the '.contentWidthFactor()' method on your view controller.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_linter">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

If not generating a table is the expected behavior, what steps could I take to do generate a table?

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 11.3.0
| node             | 18.16.0
| npm              | 9.5.1
| Operating System | macOS 14.1.1

**Comment by orta** [comment]
I'd bake the link into your messages and not use the file + line syntax, I don't think there's an argument for disabling the inline commenting  built into the sustem

**Comment by fbartho** [comment]
The inline commenting was added later so that might explain why these docs are a bit out-of-date, or at least don't mention that case.

Additionally, if the file/line is not present in a PR, then it will bundle those messages into a table.

Just for my reasoning on why this works this way: For many projects, an inline comment is much more actionable. You can even provide a triple-backtick `suggestion` and use GitHub's browser interface to commit a change.

Anyhow: I agree with @orta re: resolution of no behavior change!
