### ISSUE TITLE
GHCR publishing is broken

### ISSUE THREAD

**Issue by vaind** [danger/danger-js#1414]
There hasn't been an image pushed to ghcr.io since 11.2.7, see https://github.com/danger/danger-js/actions/workflows/publish_package.yml

The build log indicates a permission issue: `buildx failed with: ERROR: denied: permission_denied: write_package`

From what I've gathered in https://github.com/orgs/community/discussions/32184 and https://stackoverflow.com/a/72585915/2386130, you may need to set permissions on the package itself.

**Comment by orta** [comment]
good spot, I don't really use that feature - I've set it on based on the settings and we'll see on the next deploy 👍🏻

**Comment by orta** [comment]
Looks fixed to me, thanks - https://github.com/danger/danger-js/actions/runs/7131622609/job/19420525245

**Comment by vaind** [comment]
yes, works fine now, thanks
