### ISSUE TITLE
[BUG] Can you push updated images to dockerhub?

### ISSUE THREAD

**Issue by jaymzh** [danger/danger-js#1422]
**Describe the bug**
The `dangersystems` org on dockerhub has a [danger-js image from 5 years ago](https://hub.docker.com/r/dangersystems/danger-js).

The default mechanism for including danger-js to a GH runner causes the GH runner to build the entire image, which adds several minutes to CI. I'd like to be able instead to just use an existing image. Any chance of getting that updated? Thanks!

**Comment by orta** [comment]
We post to GHE, which I think should be what you need here: https://github.com/danger/danger-js/pkgs/container/danger-js

**Comment by jaymzh** [comment]
Oh brilliant, thanks!

Is that linked from anywhere? It's not under GH releases and I don't see it linked from the README.  Wondering if I just missed it. If not perhaps add that to the README?

**Comment by orta** [comment]
It doesn't look like it! Release support came from a contributor, and it's not something I really understand or use

After I read your issue I enabled in GitHub environments which at least shows it in the packages section down here: 
![image](https://github.com/danger/danger-js/assets/49038/b36eea74-ef04-448f-bdc7-ce2cb983a927)

**Comment by jaymzh** [comment]
Looks good, thanks. I can confirm I was able to use that image successfully.
