### ISSUE TITLE
[BUG] Danger doesn't work with App tokens anymore

### ISSUE THREAD

**Issue by jaymzh** [danger/danger-js#1433]
**Describe the bug**
This [changelog line](https://github.com/danger/danger-js/blob/81645a6a7f37534d156ad495c639c914bf7053e1/CHANGELOG.md?plain=1#L1462) from version `0.21.1` claims:

```
- Add support for GithHub Apps API (no GET /user) - clintam
```

But that doesn't seem to be true anymore as when we try to use a token from an App, we get:

```
Request failed [403]: https://api.github.com/user
Response: {
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/users/users#get-the-authenticated-user"
}
```

Doing a naive grep through he codebase, I only see `/user` referenced in tests (or non-GH platforms), so I'm not quite clear where it's coming from.

**To Reproduce**
1. Use an App

**Expected behavior**

**Screenshots**

**Your Environment**

```
        # This is 11.3.1
        uses: docker://ghcr.io/danger/danger-js@sha256:24bec136a7129fa421fa4591aae7cc76ca60180ecea9d239c680c2fba338b2e9
```

GitHub Actions

**Additional context**

**Comment by jaymzh** [comment]
@orta - Can you weigh in on if this is expected? I'm not bugging you for a fix, necessarily, I know this is all volunteer-time OSS, and I'm very grateful for it. But just knowing if this is expected or not would be super helpful. Thanks!

**Comment by fbartho** [comment]
@jaymzh this 403 error log isn't necessarily a direct indicator that App Tokens will never work.

It's a bit of a confusing log message, but basically, when DangerJS gets the token, it doesn't know what *kind* of token it is. It hits a series of APIs to figure that out, and this error log pops out in several conditions, but it's not a direct concern (alone). I believe the log is being generated inside of Github's API stack despite the error condition being handled in DangerJS.

Most of the projects I've used DangerJS for have that error log message despite Danger working fine. That said, I haven't used App Tokens except for one hello-world project years ago. I mostly use the built-in token, followed by a bot-account token.

**Comment by fbartho** [comment]
There are some examples of expected 403 errors in the tests here, though I haven't verified if they're exactly the same as your case!

https://github.com/danger/danger-js/blob/81645a6a7f37534d156ad495c639c914bf7053e1/source/platforms/github/_tests/_github_api.test.ts#L363

**Comment by jaymzh** [comment]
Huh, that's an interesting observation. OK, I'll test a bit more deeply, and see if I can validate it's actually functioning completely. Thanks!

**Comment by jaymzh** [comment]
OK after some testing, the problem is that when it can't determine its user, it fails to update existing comments and makes new ones. So this definitely impacts functionality.

**Comment by fbartho** [comment]
@jaymzh are you sure that your token has permission to edit/remove comments?

I don't fully remember, but when using the built-in Github Token (configured via permissions in the workflow), you could easily get into that state unless you added the right permission scope. Similarly, I had this issue when I first created a User Token for this, but it didn't have sufficient read + write / edit permissions.

DangerJS is used by so many people in so many ways, that behaving like this is actually an intentional feature. Indeed, some people/projects absolutely never want a comment to be edited or removed, and some CI providers don't even allow such edits -- even though edit/replace on comments is one of the top reasons that some people chose to use DangerJS.

So DangerJS needs to support multiple outcomes depending on how you configure it -- it's unfortunate that for your case, a configuration error (for your needs) is interpreted as a "valid" configuration for someone else's needs.

**Comment by jaymzh** [comment]
Yeah I wasn't claiming it was invalid, I totally see it as a valid possible config. I'll double check the perms on the app. Thanks.

**Comment by jaymzh** [comment]
It definitely has access (read-write to comments)

<img width="618" alt="image" src="https://github.com/danger/danger-js/assets/938467/dc950aa9-cf23-4ad1-809e-3d10228327fb">

**Comment by orta** [comment]
Sorry - on a company onsite - I feel like it was not possible to find out the account of the app which was posting _a very long time ago_ when I added support for app tokens as a GitHub app was new then. 

Maybe I fixed it by doing some hardcoding the postee in Peril, but it does seem reasonable to either see if that's possible or I'm not against the idea of having app based tokens force Danger is simply look for its own comment to update via the post body?

**Comment by jaymzh** [comment]
I have an action that looks for it's own comments by a magic string (an HTML comment) in the body, and it works well. It's a much much simpler action than Danger, and JS isn't a strong language of mine, so I haven't quite been able to follow Danger's code well enough to make the change, but I think it'd be a reasonable solution.

**Comment by fbartho** [comment]
I'm tempted to suggest that we close this ticket, and instead delete the App Token method of using DangerJS, but perhaps I'm missing a valid use-case. (Peril covers some, while user-tokens cover others!) -- Because of the security sensitivity of a tool like DangerJS, I'm not sure we should offer a public App Token.

Sounds like this isn't a blocker for anyone right now. If somebody else comes along and is motivated, I'd be happy to help review solutions.

**Comment by jaymzh** [comment]
@fbartho - GH support is requiring me to use an App, actually. Here's the details:

* We were getting lots of "you requested too many files" errors, after much debugging we realized it happened if a PR touched several workflow files. You can trigger this reliably if you touch > 8, but it often happens at even 2 or 3. We opened a support request with GitHub and they said this was a known issue and the solution is to request the `workflow` permission. But you cannot do this on the dynamic per-PR token! SO they told us to make a PAT.
* So then we moved Danger to a PAT, which is sub-optimal, but OK. Then we started getting mass-failures due to reaching API limits as we had too many in-flight PRs. We once again went back to GitHub who said there's no way to change these limits and instead we should use an App as they have 10x higher API limits.
* So now I'm attempting to use an App.

**Comment by jaymzh** [comment]
No I think I wasn't clear or you misunderstood.

The workflow is not editing a workflow.

Make a PR like this:
```
for f in .github/workflows/*; do
  echo '#test' >> .github/workflows/$f
done
```

When anythign requests the list of files in the PR, you'll get an error of `too many files`, even if that was only 9 files.

**Comment by jaymzh** [comment]
(it's quite common for us to modify several workflow files in a single PR - and SEVERAL of our checks fail, and we're trying to move them all to an App now because of this)

**Comment by jaymzh** [comment]
so I _think_ this is only done in GitHubAPI.ts and only to find Danger's comments. And since there's a magic string in all of Danger's comments, I'm pretty sure it's not needed.

**Comment by jaymzh** [comment]
Well in `getDangerCommentIDs` we [call getUserID()](https://github.com/danger/danger-js/blob/main/source/platforms/github/GitHubAPI.ts#L86) so that we can use it in the [filtering](https://github.com/danger/danger-js/blob/main/source/platforms/github/GitHubAPI.ts#L93).

However, it's not necessary as we already check to make sure the body includes a check for the magic string `DangerID: danger-id-Danger;` we put in every comment [in this filter](https://github.com/danger/danger-js/blob/main/source/platforms/github/GitHubAPI.ts#L92). That combined with the filters [to make sure it looks like a Danger comment in other ways](https://github.com/danger/danger-js/blob/main/source/platforms/github/GitHubAPI.ts#L94) should be sufficient.

**Comment by orta** [comment]
Yeah, dropping the user check seems reasonable to me

**Comment by orta** [comment]
I've done this in #1435

**Comment by jaymzh** [comment]
I've rolled this out and all works well. Thanks!
