### ISSUE TITLE
[BUG] 12.3.2 requires changes to TS dangerfiles

### ISSUE THREAD

**Issue by cjpearson** [danger/danger-js#1457]
**Describe the bug**

When updating to 12.3.2 the danger job fails with the error `SyntaxError: Cannot use import statement outside a module`. Renaming the file to `.mts` does not fix the issue.

**To Reproduce**
1. Create a `dangerfile.ts`
2. Use the `import { x, y, z } from './scripts/utils'` syntax in the file
3. Upgrade to 12.3.2

**Expected behavior**

12.6.2 should continue to work with existing dangerfiles.

**Your Environment**

 | software         | version
| ---------------- | -------
| danger.js          | 12.3.2
| node             |  20.13.1
| npm              | yarnv1
| Operating System |  alpine linux 3.18

**Comment by matthewh** [comment]
Fixed by https://github.com/danger/danger-js/pull/1456

**Comment by cjpearson** [comment]
12.3.3 works. Thanks for the quick fix!
