### ISSUE TITLE
[BUG] Outdated documentation to help to navigate the source code

### ISSUE THREAD

**Issue by alessandro308** [danger/danger-js#1461]
I know there is an hack, as described in the code 
```
throw `
Hey there, it looks like you're trying to import the danger module. Turns out
that the code you write in a Dangerfile.js is actually a bit of a sneaky hack. 

When running Danger, the import or require for Danger is removed before the code
is evaluated. Instead all of the imports are added to the global runtime, so if
you are importing Danger to use one of it's functions - you should instead just
use the global object for the root DSL elements.

There is a spectrum thread for discussion here:
  - https://spectrum.chat/?t=0a005b56-31ec-4919-9a28-ced623949d4d
`
```
but the link is outdated and I cannot figure out where the global functions are defined (e.g. warn(..) ).

Any help?

**Comment by fbartho** [comment]
@alessandro308 I had some relevant comments & questions I posed in #1459

**Comment by alessandro308** [comment]
I don't have this error. I'm trying to read the code to understand if another behaviour I experimented is right or not. 
Reading the code I've found that snippet that is referencing an unreachable url.

I need an help to understand where I can found the implementation of the warn function, the global function exposed there

**Comment by fbartho** [comment]
@alessandro308 here you go: https://github.com/danger/danger-js/blob/92d2525fe338bff16ae7d42794d0a835e2d27473/source/runner/Dangerfile.ts#L99-L149

**Comment by alessandro308** [comment]
It was easy! Thanks! I search it for a while!
