### ISSUE TITLE
Allow access to the issue behind a PR

### ISSUE THREAD

**Issue by deecewan** [danger/danger-js#154]
Every Github PR has an issue behind it, and the issues contains the reference to the labels.  This is useful to enforce a label being used on each PR.

[Github Issues Docs](https://developer.github.com/v3/issues/)
[Current Github DSL](https://github.com/danger/danger-js/blob/master/source/dsl/GitHubDSL.ts)

Proposal: Add `danger.github.issue` that contains a reference to the issue behind this PR.

**Comment by orta** [comment]
Agree 👍
