### ISSUE TITLE
Support Danger.ts files 

### ISSUE THREAD

**Issue by orta** [danger/danger-js#169]
As a lot of our Artsy JS projects are moving/moved to TypeScript, I think it makes sense to consider a `Dangerfile.ts` legit also. 

When you use TypeScript with jest, you declare a different transformer (ts-jest) so I wonder if this will work the same in Danger.

**Comment by deecewan** [comment]
interesting.  I haven't really used typescript enough, but with babel, you can `require('babel-core/register')`.  We could do a check on the file, and if it ends in `ts`, require the typescript runtime transformer (assuming it exists).

**Comment by orta** [comment]
Added in https://github.com/danger/danger-js/pull/172
