### ISSUE TITLE
Explore changing the danger import handler to use the Jest runtime env

### ISSUE THREAD

**Issue by orta** [danger/danger-js#179]
Currently we string replace any `import` or `require` of Danger into a comment, before `eval` then replace it back after. 

Now that we're using Jest's runtime system, we might be  just mock the danger module with an empty object. However, I wonder if this could overwrite our injected globals? 

Perhaps we could use the Jest mock modules to do the importing without the need for the global runtime changes at all?

Worth an exploration.

**Comment by macklinu** [comment]
Is this still something we want to explore now that we're moving to vm2 in danger-js@2.0.0?

**Comment by orta** [comment]
No - thanks. I thought about this and came to the conclusion it wouldn't work for something.
