### ISSUE TITLE
If Dangerfile fails to eval, post a message on the PR with a stack trace.

### ISSUE THREAD

**Issue by orta** [danger/danger-js#185]
Just because the eval part fails doesn't mean we can't provide meaningful errors.

E.g. a Dangerfile like this:

```js
const a = 1
a = 2
```

should already be failing the build, but we are probably able to post to the CI provider, so we can provide feedback (and recommend `danger pr [pr_url]` at the end too.

**Comment by macklinu** [comment]
That's a great idea - definitely worth adding. 👍
