### ISSUE TITLE
Proposal: Get only the content that has changed on modified_files for a PR

### ISSUE THREAD

**Issue by alex3165** [danger/danger-js#197]
Sometimes I might have just changed only some bits of a modified file but `modified_files` return the file path, would it be possible to get only the content of the file that has changed on the PR in order to be able to do some more accurate checks ?

**Comment by orta** [comment]
Yep, this is already in: https://github.com/danger/danger-js/blob/master/changelog.md#064

```js
// Politely ask for their name on the entry too
const changelogDiff = danger.git.diffForFile("changelog.md")
const contributorName = danger.github.pr.user.login
if (changelogDiff && changelogDiff.indexOf(contributorName) === -1) {
  warn("Please add your GitHub name to the changelog entry, so we can attribute you.")
}
```

**Comment by alex3165** [comment]
Ah yes thanks, I will use it
