### ISSUE TITLE
Move to prettier

### ISSUE THREAD

**Issue by orta** [danger/danger-js#208]
TypeScript support is really close to working in [prettier](https://github.com/prettier/prettier) and when it is, we should get in on that. I've heard great things about it from the jest team.

https://github.com/prettier/prettier/pull/1068
https://github.com/prettier/prettier/pull/915

**Comment by macklinu** [comment]
TypeScript support shipped in Pretter 1.4.x! 👍  https://github.com/prettier/prettier/issues/13#issuecomment-284242453

We can integrate it by running prettier on staged files (similar to how we run TSLint on staged files). We could also do a pass through the codebase and run prettier on everything.

Thoughts?

**Comment by orta** [comment]
Def - I just did it on https://github.com/artsy/emission/pull/567

Still figuring out a bit of issues with tslint - but it might not be the same on here

**Comment by orta** [comment]
Fixed in #277
