### ISSUE TITLE
Support opening danger PR into a REPL 

### ISSUE THREAD

**Issue by orta** [danger/danger-js#21]
This provides an easy way to understand what's going on

**Comment by orta** [comment]
The REPL is pretty bad in node though.

**Comment by orta** [comment]
https://nodejs.org/api/repl.html

**Comment by macklinu** [comment]
What would this command look like, out of curiosity?

```
danger pr https://github.com/danger/danger-js/pull/97 --repl
danger repl https://github.com/danger/danger-js/pull/97
```

**Comment by orta** [comment]
I think `--repl` ( this makes it consistent with the Ruby version (which does `--pry`) )

**Comment by macklinu** [comment]
I'm taking a quick stab at this. Will push up a branch / open a PR with my findings this evening.
