### ISSUE TITLE
Use a structured format for textual diffs?

### ISSUE THREAD

**Issue by namuol** [danger/danger-js#221]
Currently when using `danger.git.JSONDiffForFile`, you get a data structure like this:

```ts
/** All JSON diff values will be this shape */
export interface JSONDiffValue {
  /** The value before the PR's applied changes */
  before: any
  /** The value after the PR's applied changes */
  after: any
  /** If both before & after are arrays, then you optionally get what is added. Emprty is no additional objects. */
  added?: any[],
  /** If both before & after are arrays, then you optionally get what is removed. Emprty is no removed objects. */
  removed?: any[]
}
```

However, `danger.git.diffForFile` returns a simple `diff` string:

```diff
     "chai": "3.5.0",
     "chokidar": "1.6.0",
     "chromedriver": "2.28.0",
+    "danger": "0.16.0",
     "docker-lambda": "0.9.1",
     "electron": "1.4.4",
     "enzyme": "2.8.0",
```

I'd propose changing the result to match the shape of `JSONDiffValue`:

```ts
/** All Text diff values will be this shape */
export interface TextDiffValue {
  /** The value before the PR's applied changes */
  before: string
  /** The value after the PR's applied changes */
  after: string,
  added?: string[],
  removed?: string[],
  normal?: string[],
  diff: string,
}
```

As it is currently, you'd need to `fs.readFile` the contents of the changed file, and apply the reverse of the `diff` provided by `danger.git.diffForFile` to get the `before` and `after` values of a file. It's doable, but not pretty.

Thoughts?

**Comment by orta** [comment]
Yep, I'm into this.

Ideally everything goes through the GH API (so trade the `fs.readFile` with `github.api.getContents` ) and it becomes much easier. The PR definitely has enough information for us to be able to grab the before file directly by asking for the file at the right repo/branch 👍

**Comment by orta** [comment]
As we're still pre-1.0, the breaking change is also cool, as long as it's written up in the CHANGELOG

**Comment by namuol** [comment]
Awesome -- I'll work on a PR :tada:
