### ISSUE TITLE
danger pr failing in windows

### ISSUE THREAD

**Issue by tivac** [danger/danger-js#224]
```bash
> node -v
v7.7.3
> npm ls danger
mithril@1.0.1 C:\Users\Patrick\Documents\Code\mithril.js
`-- danger@0.16.0
> set DEBUG=*
> npm-run danger pr --verbose --repl https://github.com/tivac/mithril.js/pull/3

 danger:runner argv: C:\Program Files\nodejs\node.exe,C:\Users\Patrick\Documents\Code\mithril.js\node_modules\danger\distribution\commands\danger.js,pr,--verbose,--repl,https://github.com/tivac/mithril.js/pull/3 +0ms
  danger:pr executing dangerfile at dangerfile.js +0ms
```

and then it never goes anywhere. I traced it through the code as far as a I could, it makes it to [this line](https://github.com/danger/danger-js/blob/e670d43c29994da05f57260a9b8d3d30ee31935e/source/runner/DangerfileRunner.ts#L35) in `DangerfileRunner.ts` and never continues. The process just stops after a bit.

`--verbose` and `--repl` do nothing since it presumably is dying without continuing.

**Comment by orta** [comment]
ouch, interesting, this came from an update to the jest dependencies https://github.com/danger/danger-js/commit/aea102d7706e26952b6d18e4e024aa3175a3952f ( in 0.14.2 I started seeing issues with the tests around this, so it can be re-produced ) 

Perhaps it could be this? https://github.com/facebook/jest/issues/3079

I wonder if we can try set the no watchman

**Comment by tivac** [comment]
I'll try to dig into jest and see where it falls apart I guess.

**Comment by tivac** [comment]
I changed my local copy of `./node_modules/danger` to set the `useWatchman` option to false when creating the `HasteMap`, no luck.

As far as I can tell the transpiled async function never returns the constructed `HasteMap`, for some reason. I verified that the `HasteMap` constructor *is* running, but output gets lost after that.

It's been very difficult to get a debugger able to actually step through any of this though 😞

**Comment by tivac** [comment]
This is still broken in `0.18.0`, fwiw.

**Comment by orta** [comment]
Aye, aye, definitely still a blocker on 1.0 - current guess is for me to go through the exact options Jest sets to the haste map and see where danger differentiates.

**Comment by orta** [comment]
Also, it's possible that jest 20 comes out and fixes it :D
