### ISSUE TITLE
Can't send message to github using diffForFile

### ISSUE THREAD

**Issue by alex3165** [danger/danger-js#238]
As `diffForFile` return a Promise, when I wait for the promise to be resolved I already can see this log: `No issues or messages were sent. Removing any existing messages.` Then the message I am sending using `warn` is ignored.

Is there any way to use asynchronous actions in my dangerfile ?

`diffForFile` need to return a Promise only for the `before` and `after`, I am not sure exactly what these props are for.

**Comment by orta** [comment]
You can use [`schedule` ](http://danger.systems/js/guides/the_dangerfile.html#async) to set up the async function, it's inelegant, yes, and I don't think there is a way to be able to eval a script and keep track of how many separate threads/ticks are running based on the script being eval'd - so this gives Danger the chance to tie up all loose ends.

**Comment by alex3165** [comment]
@orta Ah ok I get it thanks for the help 👍
