### ISSUE TITLE
Investigate the usage of greenkeeper.io

### ISSUE THREAD

**Issue by romankl** [danger/danger-js#24]
(This is not meant as some kind of advertisement, just an idea)

Should greenkeeper (https://greenkeeper.io) help to keep the dependencies up-to-date? Right now, there aren't a lot of normal npm- `dependencies`, but it could help to keep them somehow on the latest version. 

The bot sends a PR if there's a new version of a dependency and increments the version.

**Comment by orta** [comment]
Sure, I'm optimistic, hopefully we shouldn't need too much more. Keeping on top of the existing ones sounds like. a good idea. You're welcome to set it up :

**Comment by macklinu** [comment]
@orta I'm not sure if members of this organization have the ability to install this integration.

When I visit https://github.com/integration/greenkeeper and click **Install**, I don't see the danger organization in the list of orgs available. This may be a task for an admin of the danger org if this is something we'd like to have.

**Comment by orta** [comment]
Ah, the UI didn't imply you could scroll. I've added it to both danger-js and peril 👍
