### ISSUE TITLE
Render markdown inside violations

### ISSUE THREAD

**Issue by orta** [danger/danger-js#240]
Ideally I should be able to write:

```js
import {message} from "danger"

message("*b* _i_ [link](https://github.com/artsy/emission/pull/505/)") 
```

And get:

> *b* _i_ [link](https://github.com/artsy/emission/pull/505/)

**Comment by orta** [comment]
I think if we leave a space between the table and user's content we get it for free. 

E.g

```
<table>
...
<tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/components/artist/artworks/__tests__/index-tests.tsx`
- `src/lib/components/artwork_grids/__tests__/infinite_scroll_grid-tests.tsx`
- `src/lib/containers/__tests__/works_for_you-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".</td>
    </tr>
  </tbody>
</table>
```

<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>Missing Test Files:

- `src/lib/components/artist/artworks/__tests__/index-tests.tsx`
- `src/lib/components/artwork_grids/__tests__/infinite_scroll_grid-tests.tsx`
- `src/lib/containers/__tests__/works_for_you-tests.tsx`

If these files are supposed to not exist, please update your PR body to include "Skip New Tests".</td>
    </tr>
  </tbody>
</table>

**Comment by macklinu** [comment]
Would it make sense to use a module like [marked](https://github.com/chjj/marked) to convert each message from markdown to HTML instead of adding spaces? I tried out the spaces on a Danger comment in an internal repo at work, but in order to get the markdown to render, I had to add a couple of new lines before and after the message, which just added unnecessary whitespace to the danger table.

I'm going to open a PR for this for discussion. 👍

**Comment by macklinu** [comment]
I played around with marked for a bit. I think it would work well for most cases expect for highlighted code blocks.

I modified a Danger comment made with danger-js@0.18.0 to add spaces like you suggested, @orta. The only way I could get code blocks to render properly was to add a couple newlines after the opening `<td>` element. Take the following HTML (ignore that `\` before the last set of backticks - it was required for GitHub to display the HTML in the codeblock):

```
<!--
  0 failure: 
  2 warning:  Please add the JI..., Changes were made...
  
  
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

Please add the JIRA issue key to the PR title (e.g. ABC-123)
</td>
    </tr>
  
<tr>
      <td>:warning:</td>
    <td>

```ts
function add(a: number, b: number): number {
    return a + b
}
\```
</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>
```

This results in




<table>

  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

Please add the JIRA issue key to the PR title (e.g. ABC-123)
</td>
    </tr>
  
<tr>
      <td>:warning:</td>
    <td>

```ts
function add(a: number, b: number): number {
    return a + b
}
```
</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

This seems to add a little bit of extra whitespace at the bottom of each table cell:

![image](https://cloud.githubusercontent.com/assets/2344137/26336348/ec38c42c-3f3f-11e7-93b3-6758b4fc06b4.png)

But if that's me being nitpicky (it very well may be 😄), leaving space between the `<td>` and user's comments is a simple solution that gets the job done. 👍 

Thoughts?
