### ISSUE TITLE
'danger' NPM module includes broken typings

### ISSUE THREAD

**Issue by icopp** [danger/danger-js#253]
```
./node_modules/danger/distribution/danger.d.ts:227:8 
TS2304: Cannot find name 'GitHub'. 
```

It looks like that `d.ts` file is referencing types from the `github` package without actually importing them.

**Comment by macklinu** [comment]
Thanks for the report!

From what I can tell, it looks like we included it in https://github.com/danger/danger-js/commit/df9b85902d1e783cfea2938da81a0f4395b34dfc, but this commit hasn't been published to npm yet. @orta, are we good to publish 0.18.1 / 0.19.0? Anything blocking this?

**Comment by orta** [comment]
Nah - nothing blocking that 👍

**Comment by orta** [comment]
Pushed 0.19.0 👍
