### ISSUE TITLE
danger pr throwing "Cannot find module 'package.json'"

### ISSUE THREAD

**Issue by kanaabe** [danger/danger-js#261]
👋  I'm currently trying to add danger to my [project](https://github.com/artsy/positron). I've set up my dangerfile.js as so:

```
const { danger, fail } = require('danger')

const someoneAssigned = danger.github.pr.assignee
if (someoneAssigned === null) {
  fail("Please assign someone to merge this PR, and optionally include people who should review.")
}

```
and if I run `danger pr` I get back an error:
```
> danger pr https://github.com/artsy/positron/pull/1
(node:97283) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Cannot find module 'package.json'
(node:97283) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have danger installed both globally and to my project repo. My local version of Node is v7.10.0. Any thoughts?

**Comment by frozegnome** [comment]
I am also having the same issue during my CI build on my application after greenkeeper updated danger to the latest version (0.19)

+1

**Comment by kwonoj** [comment]
check https://github.com/facebook/jest/pull/3723, this seems `babel-jest` side issue.

**Comment by orta** [comment]
Thanks @kwonoj :D

**Comment by threeve** [comment]
This really bummed me out just now trying to set up danger on our project finally. Until the new version of Jest is released it seems that a simple workaround is to ensure you have a `.babelrc` file in your project containing simply an empty json object `{}`. With that in place I'm able to get danger working both on jenkins and locally with `danger pr` 👍

**Comment by orta** [comment]
We ended up working around this in Artsy by moving to Peril - https://github.com/danger/peril

**Comment by hramos** [comment]
I've been running into this as well. Looks like this is fixed in jest#master, and the fix is available in Jest 20.1.0-alpha.3. I'm guessing we won't want to move Danger to an alpha release just yet, so we'll need to wait for the final Jest 20.1.0 release to become available.

**Comment by hawkrives** [comment]
I'm running in to this error when I'm just running danger in TravisCI – should I just wait for a release that includes Jest 20.1?

**Comment by kwonoj** [comment]
https://github.com/danger/danger-js/issues/261#issuecomment-308561728 is well working workaround. example : https://github.com/ReactiveX/rxjs/blob/d2a32f9a18ebbf65bea798f558364571c91a9d79/.travis.yml#L32

**Comment by hawkrives** [comment]
@kwonoj I'll try that, thanks!

**Comment by macklinu** [comment]
I was going to suggest adding solutions to the [troubleshooting](https://github.com/danger/danger-js/blob/master/docs/guides/troubleshooting.html.md) guide, but I believe this won't be a problem with danger 2.0, since we're moving away from Jest as the Dangerfile evaluator. Is this your understanding as well, @orta?

**Comment by hawkrives** [comment]
(@macklinu I should note that I no longer encounter any problems since upgrading to the danger@2 prereleases.)

**Comment by orta** [comment]
Yes, this shouldn't be a problem then 👍

**Comment by orta** [comment]
OK, I'm going to call this as sorted since Danger doesn't use jest under the hood anymore. 👍
