### ISSUE TITLE
Error: Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by macklinu** [danger/danger-js#262]
Greenkeeper is reporting failures (#252, #259, #260) for updated dependencies, but I believe this is an unrelated issue. Looks like running `yarn docs` is causing a `Error: Cannot find module 'highlight.js'` error - check an example log [here](https://travis-ci.org/danger/danger-js/jobs/235668363#L587).

**Comment by macklinu** [comment]
I tried running `yarn docs` locally on Node 7 and can't reproduce - has anyone seen this error locally or have any insight into why Travis builds keep failing?

**Comment by orta** [comment]
I feel like you fixed this?

**Comment by macklinu** [comment]
Not knowingly 😂  we can close this if we aren't seeing any more issues. You think #271 fixed this somehow?

**Comment by orta** [comment]
I've not seen it, and I've been doing danger stuff all weekend. /shrug?

**Comment by macklinu** [comment]
Haven't seen this lately. Let's close and reopen if we start seeing it again. 🤷‍♂️
