### ISSUE TITLE
unique identifier for danger-written comments?

### ISSUE THREAD

**Issue by kwonoj** [danger/danger-js#269]
Due to private repo's limitation, I am currently using myself's github token to run danger instance (which post comments under my user). Which makes if I leave a comment before danger finishes run, danger will remove those comment and replace it into danger's results. 

Is there way to make danger validate comments (like having some prefix in comments?) to avoid these cases?

**Comment by orta** [comment]
There is always the "posted by danger" - could verify that that exists inside the comment before declaring it as one posted by the tool?

**Comment by orta** [comment]
Also HTML stays inside the text comment (even if it's not rendered by markdown) so adding a useful `<!-- thing -->` is also an option.

**Comment by kwonoj** [comment]
> There is always the "posted by danger" - could verify that that exists inside the comment before declaring it as one posted by the tool?

I guess this can be used, question is more about locating comment ID logics (https://github.com/danger/danger-js/blob/d80b7553f528833231b9310c2c63d50d661f0b26/source/platforms/github/GitHubAPI.ts#L75) which currently just compares userID directly, if there's configurable way (or even fixed way by validating those).

**Comment by orta** [comment]
Perhaps then I think a mix of same user and a specific hidden marker which can be added into every comment from danger is optimal.

**Comment by kwonoj** [comment]
@orta I'd 👍 with those idea.
