### ISSUE TITLE
Post status to github rather than breaking the build

### ISSUE THREAD

**Issue by shilman** [danger/danger-js#279]
## why

Currently when there are any `fail` messages, Danger breaks the build:

https://github.com/danger/danger-js/blob/a45ad2f9dc20cd32a316c8aa161a49ee30afe8fb/source/runner/Executor.ts#L156

If the token has PR access, it should post a build status instead rather than completely breaking the build.

## what
Try to post the status, set exitCode to 1 if this fails

**Comment by macklinu** [comment]
Status posting has been shipped in danger@0.21.0 - @shilman, please update and let us know what you think!

Here's an example from a private repo at work where Danger found one warning and no failures, which marks the PR with a "success" status and the there-are-fixable-things message. 🙂 

![image](https://user-images.githubusercontent.com/2344137/27061710-1f42dc5c-4fb4-11e7-80f7-c40f72641d57.png)

Let's keep this issue open to add some more tests around this feature. 👍

**Comment by shilman** [comment]
That was fast—thanks for the fast turnaround! And it works like a charm: https://github.com/storybooks/storybook/pull/1251

<img width="710" alt="add_danger_to_start_automating_some_code_review_tasks_by_shilman_ _pull_request__1251_ _storybooks_storybook_" src="https://user-images.githubusercontent.com/488689/27062833-09c87920-5042-11e7-9308-08ac8fa3b5ce.png">
