### ISSUE TITLE
Adding labels to a GitHub PR

### ISSUE THREAD

**Issue by taiidani** [danger/danger-js#305]
I'm having a devil of a time trying to figure out how to add labels to a GitHub PR with Danger-JS. I believe the `danger.github.issue.labels` property is read-only so I've been attempting to understand how Danger expects calls using `danger.github.api` to be formatted.

Is there documentation and/or code samples available to lead me in the right direction on this?

**Comment by orta** [comment]
Syntax wise it would look something like:

```js
  danger.github.api.issues.addLabels({ owner: "danger", repo: "danger-js", number: danger.github.pr.number, labels: ["Failed"] })
```

Which you can short-cut to:

```js
github.api.issues.addLabels({ ...github.thisPR, labels: ["Danger Passed"] })
```

I believe. These are async functions, so I'd recommend wrapping them in a schedule:

```js
schedule(async ()=> {
  await github.api.issues.addLabels({ ...github.thisPR, labels: ["Danger Passed"] })
})
```

I'd like to add this and some more examples to the usage section, maybe under an article called cookbook

**Comment by orta** [comment]
API is just an instance of https://github.com/mikedeboer/node-github - which is why I've not got it doc'd in the site too much

**Comment by taiidani** [comment]
Hmm, well I'm trying to match that. I must be doing something else wrong though. I've got it trimmed all the way down to:

```js
import { danger, github } from "danger";
import { includes } from "lodash";

schedule(async ()=> {
    await github.api.issues.addLabels({ ...github.thisPR, labels: ["change/environment"] });
});
```

But I receive this error when trying to run it with a `danger pr`:
```
(node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: /danger/dangerfile.js: Unexpected token (5:40)
(node:12) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I admit I'm quite behind on my NodeJS so I'm sure it's on my side. Will keep researching but I'd love help if you can spot what's wrong!

**Comment by taiidani** [comment]
(it's running in a `node:8.1` Docker container, if that helps)

**Comment by taiidani** [comment]
Hmm, well I got it to work with the expanded syntax!

```
schedule(async ()=> {
        await github.api.issues.addLabels({ owner: github.thisPR.owner, repo: github.thisPR.repo, number: github.thisPR.number, labels: ["change/environment"] });
    });
```

[Rumor has it](https://stackoverflow.com/questions/40066731/node-v6-failing-on-object-spread) that that spread operator doesn't work yet for objects?

**Comment by orta** [comment]
I use TypeScript - so I gave code that's expected to transpile, don't think plain ole JS supports that syntax no 👍

**Comment by taiidani** [comment]
Ah, that makes sense. Well then, I think this solution works for me! Thanks for your help!
