### ISSUE TITLE
Awesome list of plugins/uses

### ISSUE THREAD

**Issue by TAQ2** [danger/danger-js#307]
Hello, I was wondering if there is a curated list of all danger plugins or examples of interesting uses of danger.

Just to give you some reference, I am trying to create a feature where danger will warn if a pull request has not been rebased onto master first (to warn of merge conflicts). As a novice this seems like a big job, so it would be a nice feature to have some sort of extensive list as a reference for people like me (if it doesn't exist).

Thanks!

**Comment by orta** [comment]
Not yet, I'll be moving that into the website, which is what we do on the Ruby version:

![screen shot 2017-07-20 at 11 15 22](https://user-images.githubusercontent.com/49038/28424875-bd23191e-6d3c-11e7-8d6b-28ad88651f23.png)

Once there's a couple more on NPM: https://www.npmjs.com/browse/keyword/danger-plugin

So basically right now, chances are, anything you build will be the first plugin of its ilk.

**Comment by TAQ2** [comment]
Thanks for your reply. Yes that would be a cool feature.

Hopefully, I'll come back with a plugin for my problem soon!

**Comment by orta** [comment]
This is now on the front-page of the danger JS site, it's note quite as comprehensive, but it can be built upon.
