### ISSUE TITLE
dtslint shouldn’t be in runtime dependencies

### ISSUE THREAD

**Issue by sapegin** [danger/danger-js#319]
Because it depends on tsutils which requires a TypeScript peer dependency:

> npm WARN tsutils@1.9.1 requires a peer of typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >= 2.4.0-dev but none was installed.

**Comment by orta** [comment]
Yep - definitely a bug

**Comment by sapegin** [comment]
It’s now in `optionalDependencies` but I’m not sure what’s the reason to have it here. Is it save to move it to `devDependencies`?

**Comment by orta** [comment]
Yep 👍 I probably didn't understand what optionalDependencies are, still not sure I do 🍡

**Comment by sapegin** [comment]
I think it mainly used for platform specific packages — it won’t fail the whole this if the package can’t be installed. I’ll send a PR to move dtslint to `devDependencies`.

**Comment by macklinu** [comment]
I think this was resolved in 1.2.0. Closing; please reopen if this is still an issue.
