### ISSUE TITLE
Getting "Skipping Danger due to not this run not executing on a PR." on PR builds on CircleCI

### ISSUE THREAD

**Issue by sean-clayton** [danger/danger-js#326]
Links:
CircleCI Build: https://circleci.com/gh/smartprocure/futil-js/436
Git Repo at time of the build: https://github.com/smartprocure/futil-js/tree/323333f54d3d67de47ede209d83c80c3006cd30a

[We have a pretty standard `danger.js` file](https://github.com/smartprocure/futil-js/blob/323333f54d3d67de47ede209d83c80c3006cd30a/dangerfile.js) and we have everything set up in Circle for Danger, but we keep getting this error when opening PRs. It's fixed when we hit the "rebuild" button, but I don't think that's an intended (or desired) effect.

**Comment by orta** [comment]
Alas, this is a long-running issue with Circle, see http://danger.systems/guides/troubleshooting.html#circle-ci-doesnt-run-my-build-consistently which we can't fix on Danger's side (without moving to Peril)

You can force Circle to run PRs only. I think which might improve your chances.

**Comment by macklinu** [comment]
Is this something we need to add to the danger-js docs before closing this issue?

**Comment by orta** [comment]
IMO< yeah, should be on the JS FAQ as well as on Ruby's

**Comment by deecewan** [comment]
@orta @sean-clayton is this now complete? can we close this?

**Comment by orta** [comment]
Yes, I think so 👍
