### ISSUE TITLE
Make @DangerSystems tweet when a new release comes out

### ISSUE THREAD

**Issue by orta** [danger/danger-js#332]
Maybe this would make a better web service that can work of web hooks (maybe even a peril one?) - but it'd be nice to have the official twitter sending out a tweet for releases.

**Comment by daedalus28** [comment]
Very interested in seeing how you do this because this is a great idea! We'd love to do that with our libs as well.

**Comment by ashfurrow** [comment]
Had some fun playing with Typescript this weekend and built this: https://github.com/ashfurrow/twelease It's an Express app that tweets when new tags are pushed to the repo, uses Mustache. Feedback welcome 👍

**Comment by orta** [comment]
This now works: https://twitter.com/DangerSystems/status/926870253556109313
