### ISSUE TITLE
GitDSL: Diffs for added and removed files

### ISSUE THREAD

**Issue by bdotdub** [danger/danger-js#368]
Calling `diffForFile` unexpectedly returned `null` for me for a file that was added. It looks like expected behavior per these lines:

https://github.com/danger/danger-js/blob/72b7c6c7f85672d1982347dd83b8b4a5e48b17d5/source/platforms/github/GitHubGit.ts#L50
https://github.com/danger/danger-js/blob/72b7c6c7f85672d1982347dd83b8b4a5e48b17d5/source/platforms/github/GitHubGit.ts#L150

----------------

It was initially unclear to me why `diffForFile` would strictly return the diffs for modified files only. I can understand why we would want this conceptually (diffs are a byproduct of a _change_ of a file), but there is definitely utility in being able to get a diff for created and removed files.

I'd like to propose that `diffForFile` return a `TextDiff` object for added & removed files. For added files, `added` will be the whole file and removed would be empty, and vice versa for removed files.

It would make getting all changes in the whole PR much easier, rather than calling diff on some, and `fileContents` on others:

```js
danger.git.created_files
      .concat(danger.git.modified_files)
      .concat(danger.git.deleted_files)
      .map(p => danger.git.diffForFile(p))

// vs.

danger.git.modified_files
      .map(p => danger.git.diffForFile(p))

const pr = danger.github.pr;
danger.git.created_files
      .map(p => danger.github.utils.fileContents(p, pr.head.repo.full_name, pr.head.sha));
danger.git.deleted_files
      .map(p => danger.github.utils.fileContents(p, pr.base.repo.full_name, pr.base.sha));
```

(The above code also isn't working for me because of #367)

This change would extend to `JSONDiffForFile` and `JSONPatchForFile`.

----------

Barring that, the documentation should be more explicit in communicating this.

Happy to do the work but wanted to get some thoughts!

**Comment by orta** [comment]
Yeah, I think this behaviour is a great call 👍  - I think your expectations there are what I'd imagine too

**Comment by orta** [comment]
This is in 👍
