### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by danielepolencic** [danger/danger-js#374]
There're missing pages in the following guide http://danger.systems/js/guides/getting_started.html

- _Create either an empty JavaScript or TypeScript file named Dangerfile. Either Dangerfile.js or Dangerfile.ts will be picked up automatically._
  Later in the documentation the name of the file is referenced as `dangerfile.ts` (all lowercase).
- _To get yourself started, try this as your Dangerfile:_ [empty]
- _For a deeper understanding of using a Dangerfile, see the guide [The Dangerfile][dangerfile]_ broken link

If someone can point me to the code, I could have a quick look and see if I can fix it.

At the moment is really hard to figure out how I should integrate danger-js with my project.

**Comment by orta** [comment]
Great awesome - thanks for the issue, I've updated the docs (looks like it was missing a chunk of the guide too) and fixed the links - [here](https://gitlab.com/danger-systems/danger.systems/commit/1a27e4a791fff0b2d757bddc7d0330b476f08949). It usually takes about 15-20m to deploy, which you can [check here](https://gitlab.com/danger-systems/danger.systems/pipelines/11840748) 👍
