### ISSUE TITLE
Getting "Skipping Danger due to not this run not executing on a PR." on PR builds on Jenkins using multi branch pipeline jobs

### ISSUE THREAD

**Issue by sgtcoolguy** [danger/danger-js#379]
Looks like the implementation assumes usage of the Github Pull Request Builder, which is a handy plugin for legacy builds. I think the push now is to move to pipeline jobs, specifically to things like Github Organization Folders which scan github orgs for matching repos using a regexp and generating multi branch pipeline jobs underneath it.

In that scheme, there's no `ghprbPullId` and `ghprbGhRepository` env variables as looked for here: https://github.com/danger/danger-js/blob/09dcbd74e1b5df3e1a4a2058b716eb993181a25c/source/ci_source/providers/Jenkins.ts#L40-L42

Personally, I hacked a workaround in my `Jenkinsfile` like so:
```groovy
withEnv(['ghprbGhRepository=organization/reponame',"ghprbPullId=${env.CHANGE_ID}"]) {
  sh 'npx danger'
}
```

So I think `CHANGE_ID` and `ghprbPullId` are equivalents, but I don't think there's an exact equivalent of `ghprbGhRepository ` produced, though I believe you could parse it out of `CHANGE_URL`.

**Comment by orta** [comment]
I don't really know too much about this, (as I don't use Jenkins anywhere) happy to have any changes that make it easier to use whatever is the recommended way to use jenkins though :D

**Comment by orta** [comment]
I just ported over the code from Danger Ruby  💯

**Comment by Sega-Zero** [comment]
Having the same issue in danger-swift

**Comment by TejasQ** [comment]
+1

**Comment by azz** [comment]
Having the same issue with Jenkins + BitBucket server. Should be straight forward to parse the `CHANGE_URL`. 

```
CHANGE_ID=244
CHANGE_URL=https://bitbucket.server/projects/PROJ/repos/REPO/pull-requests/123/overview
```

**Comment by orta** [comment]
It looks like the [current setup](https://github.com/danger/danger-js/blob/master/source/ci_source/providers/Jenkins.ts) requires you to format your bitbucket env vars like  githubs. Definitely open to changing that 👍
