### ISSUE TITLE
Using DangerJS with GitLab/BitBucket

### ISSUE THREAD

**Issue by k15a** [danger/danger-js#396]
Hey,

is there a way how I can use DangerJS for GitLab with the GitLab CI. Otherwise, is it possible to add support for GitLab and GitLab CI and where could I start to implement it?

**Comment by orta** [comment]
Can't use it for GitLab today.

However, I built Danger JS with the same abstractions used in Danger Ruby, which does. Though, I'd wait till #395 lands before starting though, it's a massive PR.

So the general TODO:

* Add support for new [ENV vars](https://github.com/danger/danger/blob/master/lib/danger/request_sources/gitlab.rb#L14-L20)
* Create a new object which [conforms to Platform](https://github.com/danger/danger-js/blob/master/source/platforms/platform.ts)
* `getPlatformForEnv` will need to figure out whether it's GH/GL project
* Let a CI source determine if they can work [with GitLab](https://github.com/danger/danger/blob/master/lib/danger/ci_source/jenkins.rb#L59) (I think there's already something in there )
* Extend `DangerJSONDSL` / `DangerDSL` with a GitLab DSL
* Cover this stuff in tests, as this repo runs on GitHub and it's possible we could accidentally break it 
* Note: The markdown rendering is different in [Danger Ruby GitLab](https://github.com/danger/danger/blob/master/lib/danger/comment_generators/gitlab.md.erb) 
* Lots of other context in https://github.com/danger/danger/pull/299

**Comment by orta** [comment]
#395 is now merged 👍

**Comment by jchv** [comment]
Just FYI, I'm interested in working on this. Not 100% sure how far I'll get.

**Comment by k15a** [comment]
@jchv Nice that you want to give it a shot. Maybe some useful information I figured out:
- GitLab doesn't have the concept of merge requests for now so you have to be a little bit hacky and figure out the corresponding merge request to a pipeline on your own. Take a look at the ruby integration and copy the logic from there.
- Otherwise, the codebases are really close to each other so you can figure a lot of things out when you watch the Danger Ruby PR.

**Comment by jchv** [comment]
Yeah, luckily I have some of the background in mind already. I think working backwards to get the MR is fine; GitLab will probably eventually add CI events for MRs, at which point we can do this properly. Until then, there was a hack that someone mentioned in a Danger Ruby thread that filled the gap using build triggers such that Danger didn't have to be modified; that way, we can at least make sure MRs always get hit until the CI itself supports MR events.

**Comment by LukeSheard** [comment]
Anyone got any idea how much effort it would be here to abstract it enough to support BitBucket server / hosted? Happy to lend some hours.

**Comment by orta** [comment]
Abstraction wise it should be just as much work to support GitLab as it is for BitBucket - the original Danger Ruby PRs for that are https://github.com/danger/danger/pull/481 and https://github.com/danger/danger/pull/496

**Comment by orta** [comment]
I've got some more work coming up which makes this easier as it decouples the git DSL from the github platform also

**Comment by orta** [comment]
That work got merged two days ago: https://github.com/danger/danger-js/pull/473

**Comment by keplersj** [comment]
I'm interested in pursuing this. Are there any blockers still before this can be done?

**Comment by orta** [comment]
Nope, no blockers

**Comment by keplersj** [comment]
So is the big thing to write the DSL for GitLab that gives access to the GitLab API?

**Comment by orta** [comment]
Yeah, that's a good place to get started - I'd advise starting by finding a good npm module for the GitLab API then making something which conforms to [Platform](https://github.com/danger/danger-js/blob/master/source/platforms/platform.ts) from that

**Comment by orta** [comment]
DSL wise, I'd ideally like to feel like the [GitHub DSL](http://danger.systems/js/reference.html#GitHubDSL) e.g. the minimum is:

```js
danger.gitlab.mr = exactly the MR JSON from the API
danger.gitlab.utils = util funcs 
danger.gitlab.commits = commits from the GitLab API
```

After that you can expand it however makes sense

**Comment by peterjgrainger** [comment]
@keplersj Can I give you a hand with this?  It's kind of blocking us at the minute and can take over from where you left off if you don't have the time?

**Comment by keplersj** [comment]
Please take it over. I never got to this and I'm about to leave the project I needed this for.

**Comment by peterjgrainger** [comment]
OK, thanks @keplersj I'll have a look

**Comment by kaoDev** [comment]
hey @peterjgrainger did you have some time working on the gitlab integration?

**Comment by peterjgrainger** [comment]
unfortunately not, something more pressing came up at work.

Happy for someone else to take it on.

**Comment by gurpreet-hanjra** [comment]
Hello @orta I recently came to know about DangerJS while working on some issues for GatsbyJS. I want to use it with my professional project which uses Gitlab. I would like to look into DangerJS usage with Gitlab, could you guide me in this? Thank you.

**Comment by orta** [comment]
Sure, my comments above 
https://github.com/danger/danger-js/issues/396#issuecomment-337295471 will teach you how to add support for GitLab to Danger JS 👍

**Comment by bigkraig** [comment]
@gurpreet-hanjra, as far as I can tell, @stigi started to look into this and had created some TODOs at https://github.com/stigi/danger-js/pull/1. @stigi did you get anywhere?

**Comment by stigi** [comment]
@bigkraig Nope, sorry. No progress on my end.

**Comment by bigkraig** [comment]
I'm starting to poke around at this on https://github.com/bigkraig/danger-js/tree/gitlab during my flight. It's not a whole lot more than some file copies and /Lab/Hub/ replacements at this point though. I'm far from experienced with TS. As far as I can tell the gitlab client module is a heavy WIP and undergoing some changes in 5.0.0.

**Comment by notjosh** [comment]
fyi, I've made decent progress while experimenting today over at https://github.com/notjosh/danger-js/tree/feature/gitlab. It's at a point where a `Dangerfile` can create(/update/delete) comments (inline & general).

i.e. a simple `Dangerfile.ts`:

```js
export default async () => {
  if (!danger.gitlab) {
    console.log("gitlab not found, bailing");
    return;
  }

  console.log("running gitlab");

  const timestamp = new Date().toISOString();

  warn(`foo @ ${timestamp}`);

  // pluck the first file for inline comments
  const f = danger.git.modified_files.length > 0 ? danger.git.modified_files[0] : null;
  if (f) {
    warn(`bar @ ${timestamp}`, f, 3);
    warn(`baz @ ${timestamp}`, f, 4);
  }
};
```

It _seems_ reasonably stable for the basics, but it's still missing most of the DSL utils (y'know, the stuff that makes Danger interesting 😉 - diffs, etc). We'll (probably) end up using it at work, so I'll keep chipping away at it. I'll open a PR when the tests are in a more useful state.

**Comment by orta** [comment]
nice one - so long as it's green and well scoped, I'll take incremental PRs too (and we can skip documenting until it's ready for prime time)

**Comment by bigkraig** [comment]
@notjosh I sent a PR your way to add support for running inside of GitLab CI.

If you could merge that and send a PR over to here so we could get a release I think we could start to use this.

**Comment by bigkraig** [comment]
> @notjosh I sent a PR your way to add support for running inside of GitLab CI.
> 
> If you could merge that and send a PR over to here so we could get a release I think we could start to use this.

Nevermind, I rebased your branch, got the inline comments working, and got #855 opened up 🎉

**Comment by jamime** [comment]
* BitBucket added in #516 
* GitLab added in #855

**Comment by goodhoko** [comment]
looking at https://danger.systems/js/guides/getting_started.html it states that

> Currently Danger JS only supports communication on GitHub and BitBucket Server. If you’re interested in GitLab support, PRs are welcome, or look at the Ruby version of Danger.

Does that still hold since this issue is closed?

**Comment by orta** [comment]
Nope, that can definitely changed 👍

**Comment by goodhoko** [comment]
@orta ok! Gimme a while to send a PR.

**Comment by goodhoko** [comment]
@orta I submitted a [MR](https://gitlab.com/danger-systems/danger.systems/-/merge_requests/196) updating the docs.

**Comment by orta** [comment]
<3 thanks! That's deployed
