### ISSUE TITLE
So...Why the new file format?

### ISSUE THREAD

**Issue by hulkish** [danger/danger-js#397]
I really like what I see with the goals of this tool... But, I have to say I just don't understand the benefit of introducing a new file format at all - not to mention a Javascript subset. (Did we learn nothing from Coffeescript?)

Wouldn't it be better just to let js be js? At least as an option?

A quote from your docs: 
> We’ve not found the perfect pattern for handling different patterns of asynchronous behavior inside a Dangerfile. Here are some patterns for handling them.

Aren't you just introducing a problem that is solved by not abstracting js in the first place?

**Comment by orta** [comment]
a Dangerfile is just is plain JavaScript with some globals, it's just that evaluating a file requires passing out async behavior to the host app so that it can wait for the promises to resolve.

**Comment by hulkish** [comment]
is it next to process the dangerfile in a vn?

**Comment by orta** [comment]
Nope, see #373
