### ISSUE TITLE
Support not adding status line

### ISSUE THREAD

**Issue by keith** [danger/danger-js#409]
We run danger in our Jenkins CI setup, from there we determine if it failed based on Danger's output / status code, and fail the jenkins job. It would be nice if Danger didn't also add a custom status line because clicking details there just takes users to Danger's site, where clicking details for our jenkins build would take them to the log instead.

Thoughts?

**Comment by orta** [comment]
I was thinking earlier that it might be better to make it link to the comment that it just posted instead, it will probably just jump up the page but I know I've seen people miss it and say "why did danger failed this?"

**Comment by orta** [comment]
Fixed in 2.1.5
