### ISSUE TITLE
Github Enterprise Support?

### ISSUE THREAD

**Issue by rudolfolah** [danger/danger-js#412]
Is it possible to use Danger with Github Enterprise edition?

**Comment by orta** [comment]
Yep, you can use the `DANGER_GITHUB_API_BASE_URL` to set the GH url, it doesn't look like this is documented, so I'll leave this open to remind peeps.

**Comment by omouse** [comment]
awesome, thanks for the answer!

**Comment by orta** [comment]
This should be documented by now
