### ISSUE TITLE
Faked imports make the Dangerfile look like it's transpiling from ES6 when it's not

### ISSUE THREAD

**Issue by neil-morrison44** [danger/danger-js#425]
Hi,
Just spent longer than I'm willing to admit to going down the rabbit-hole of trying to work out why the import statements in one Dangerfile (for danger itself, warn, message etc) were working fine but another Dangerfile's import statements (for my own code) weren't.

I'm not sure what problem having faked imports solves?

Alternately, catching the `Unexpected token import` error & providing an explanation might help save others from having to dig around to find where the danger imports are being removed?

**Comment by orta** [comment]
Ah yeah, that makes sense - they're there for tooling support. If you have babel or typescript set up for your project it should be transpiling your dangerfile and linked code though.

**Comment by neil-morrison44** [comment]
We do have Babel setup, but it’s in a different way than Danger can detect - we have lots of projects which share a common build / test pipeline and Babel sits embedded within it.

I’d think that having non-standard Babel setup is reasonably common in “frontend” repos & that people would expect imports to work if they see what looks like one working.

I get that not having that would mean losing the nice typescript tooling & having a real import would mean people would need to setup dependencies and transforms to see the Hello world work.

Would be nice to catch & explain the error, I think.

**Comment by orta** [comment]
This makes sense, most of my projects are react-native which generally has a common setup - I think exporting the same set of functions from the index and including a message about what's going on is a good step here 👍

**Comment by orta** [comment]
Alright, I've had it catching the import for ~a year and no-one else has made a note about the hacks required to pull this off (in other threads either) so I'm going too call this good 👍
