### ISSUE TITLE
Unable to make use of environment variables

### ISSUE THREAD

**Issue by sgtcoolguy** [danger/danger-js#427]
Danger should be able to refer to environment variables set when running the `danger run` process. However, process.env is empty. I suspect that since this is actually now running `danger process` as a subprocess, the environment variables aren't getting passed along.

As a result I can't access meaningful env variables Jenkins sets like BUILD_URL, and need to resort to writing files alongside the danger file that I can then read to pass along env vars or data about the build.

**Comment by orta** [comment]
Yeah, that does sound like a bug - we should pass along all of the process env vars in `danger run` 👍
