### ISSUE TITLE
Grammar in readme

### ISSUE THREAD

**Issue by chipit24** [danger/danger-js#433]
From the `readme`:
> This provides another logical step in your process, **through this Danger** can help lint your rote tasks in daily code review.

The issue is with the bolded text. "This", in the bolded phrase, appears to function as a determiner ("this Danger"), and is nonsensical ("... through this Danger can help ..."). A pronoun should be used to make things more clear:

> This provides another logical step in your process, through **which** Danger can help lint your rote tasks in daily code review.

**Comment by orta** [comment]
I agree, PR sent 👍

**Comment by orta** [comment]
Thanks!
