### ISSUE TITLE
tsconfig.json comments not supported

### ISSUE THREAD

**Issue by GantMan** [danger/danger-js#454]
#### Hello!
So Danger works with `dangerfile.ts` but since TS is using [JSON 5](http://json5.org/) which supports awesome things like comments.  Unfortunately, when danger-js tries to read my `tsconfig.json` it errors on the comments.  

#### Easy fix
We switch `JSON.parse` into using `JSON5.parse` with including https://github.com/json5/json5 (as TypeScript uses)

Possible culprit spot:  https://github.com/danger/danger-js/blob/44ea792de31b0b6b25e29356af79869a5ec1db3e/source/commands/danger-runner.ts#L34

Let me know if PRs would be accepted, and I'll give this one a go.

**Comment by orta** [comment]
Yep 👍
