### ISSUE TITLE
[Chore] [Blocked]: "github" dependency renamed to "@octokit/rest"

### ISSUE THREAD

**Issue by fbartho** [danger/danger-js#482]
I noticed in the terminal on package install the following warning
```shell
$ yarn install
…
warning danger > github@13.1.0: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
…
```

Looking at the release page: https://github.com/octokit/rest.js/releases/tag/v14.0.0 I see:
>there are no functional changes in the public APIs compared to github@13.

I'll submit a PR shortly after find-replacing everything & running the tests.

**Comment by orta** [comment]
Wow, that was quick, that release was 4 hours ago :D

**Comment by fbartho** [comment]
@orta haha, I got excited to help when I saw the warning :P

Maybe too excited… I unfortunately got stuck when trying to push. The typescript compiler is grumpy:

```
source/dsl/GitHubDSL.ts(2,25): error TS7016: Could not find a declaration file for module '@octokit/rest'. '/Users/fbarthelemy/Code/danger-js/node_modules/@octokit/rest/index.js' implicitly has an 'any' type.
  Try `npm install @types/@octokit/rest` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/rest';`

2 import * as GitHub from "@octokit/rest"
// ...(repeat a bunch)
   ```
When I add
```typescript
declare module "@octokit/rest"
``` to `ambient.d.ts`

Then I get:
```
source/dsl/GitHubDSL.ts(2,13): error TS6133: 'GitHub' is declared but its value is never read.

2 import * as GitHub from "@octokit/rest"
// ...(repeat a bunch)
```

**Comment by orta** [comment]
Ah yeah, definitely typed needs to be updated with the new module.

**Comment by orta** [comment]
Or not, will have a look

**Comment by fbartho** [comment]
Looking at: https://www.npmjs.com/package/@types/github -- no types should be needed.

**Comment by fbartho** [comment]
Should I force the branch up so you can start from passing tests with all the find-replaces complete?

**Comment by orta** [comment]
Perfect, yeah

**Comment by fbartho** [comment]
https://github.com/danger/danger-js/tree/fb/update_github_rest_dependency

**Comment by orta** [comment]
Yeah, they're accidentally not shipping the types

<img width="283" alt="screen shot 2018-01-17 at 7 11 55 pm" src="https://user-images.githubusercontent.com/49038/35074108-51b6a954-fbba-11e7-814c-571377ae9411.png">

Should be a `index.d.ts`.

**Comment by fbartho** [comment]
Nice catch. I'm new to typescript & module namespaces, so I didn't know what I should be looking for. I can file a bug with them.

**Comment by orta** [comment]
No worries, it's definitely something you learn with time 👍
