### ISSUE TITLE
Broken Dangerfile did not fail the CI

### ISSUE THREAD

**Issue by orta** [danger/danger-js#50]
I vote this was not "All Good."

![screen shot 2016-12-14 at 5 11 30 pm](https://cloud.githubusercontent.com/assets/49038/21203439/6f189a4a-c220-11e6-8968-026d7c1413a6.png)

**Comment by macklinu** [comment]
It looks like `Dangerfile.run()` is [logging an error](https://github.com/danger/danger-js/blob/51dcc1550412c72cc07a853fd31e724c22c4f9ea/source/runner/Dangerfile.js#L121) when running the script fails, which I believe is what you're seeing with your screenshot. Would it be appropriate to just rethrow that caught error here?

**Comment by orta** [comment]
Yeah, I think so - maybe someday in the future this can be formalized but I think throwing is a better experience for now 👍

**Comment by macklinu** [comment]
I believe this has been resolved with #54.

**Comment by orta** [comment]
I kept the check in to keep the PR on topic, I think we need to add `process.exitCode = 1` inside the catch [for this](https://github.com/danger/danger-js/blob/master/source/commands/danger-run.js#L40-L45), or to remove the try catch entirely

**Comment by macklinu** [comment]
I will take a look at adding `process.exitCode = 1` and adding a test for that tonight.
