### ISSUE TITLE
Error: Cannot find module '/var/lib/jenkins/workspace/elc-frontend-components-runner/node_modules/danger/distribution/commands/danger-runner.js'

### ISSUE THREAD

**Issue by ionutmiftode** [danger/danger-js#522]
The current path where danger-js should look in should be
'/var/lib/jenkins/workspace/**elc-frontend-components-pr**/node_modules/danger/distribution/commands/danger-runner.js'
instead of 
'/var/lib/jenkins/workspace/**elc-frontend-components-runner**/node_modules/danger/distribution/commands/danger-runner.js'

this is due the fact that `dangerRunToRunnerCLI` does 
`newJSFile_1 = newJSFile_1.replace("-" + name, "-runner");`
so if the path to the project contains **-pr, -local or -ci** will cause this kind of error.
the fix should be something like
`newJSFile_1 = newJSFile_1.replace("danger-" + name, "danger-runner");`

**Comment by orta** [comment]
Sure, would you like to send a PR for this?

**Comment by ionutmiftode** [comment]
sure!

**Comment by ionutmiftode** [comment]
https://github.com/danger/danger-js/pull/523
