### ISSUE TITLE
diffForFile produces unexpected result if PR is made from fork

### ISSUE THREAD

**Issue by chris48s** [danger/danger-js#531]
Hello. I think I have hit a bug while I'm trying to write a `dangerfile` which uses the `diffForFile()` method. I've reduced the problem to a minimal example:

danger version: 3.1.7

dangerfile.js:

```js
const { danger, fail, message, warn } = require('danger');

danger.git.diffForFile('README.md').then(function(diff) {
  message(JSON.stringify(diff));
});
```

If I run this dangerfile against a PR like https://github.com/danger/danger-js/pull/434 where the head branch and base branch are in the same repo this behaves as expected. For example:

```
$ npm run danger pr "https://github.com/danger/danger-js/pull/434"

> test-app@ danger [path]
> danger "pr" "https://github.com/danger/danger-js/pull/434"

Starting Danger PR on danger/danger-js#434
## Messages
{
  "before": "...",
  "diff": "...,
  "added": "...",
  "removed": "..."
}
Danger: Passed, found only messages.
```

(I've truncated the object to keep the snippet short, but you get the point)

However, if I take a PR where the head branch is on a fork like https://github.com/danger/danger-js/pull/420 this does not work as I would expect:

```
$ npm run danger pr "https://github.com/danger/danger-js/pull/420"

> test-app@ danger [path]
> danger "pr" "https://github.com/danger/danger-js/pull/420"

Starting Danger PR on danger/danger-js#420
Request failed [500]: https://api.github.com/repos/mxstbr/danger-js/pulls/420

Response: {
  "message": "Server Error",
  "documentation_url": "https://developer.github.com/v3/pulls/#get-a-single-pull-request"
}

## Messages
null
Danger: Passed, found only messages.
```

**Comment by orta** [comment]
Ah, I bet this is using head instead of base somewhere in the related code (I work in branches, so I  won't have spotted this. )

**Comment by chris48s** [comment]
Not sure which release introduced the fix but I'm going to close this because I installed the latest release and this bug is now gone. :+1:

**Comment by sunshinejr** [comment]
Oh yeah we fixed it in inline mode 👍🏻 glad it’s working for you now!
