### ISSUE TITLE
Every page at http://danger.systems is a 404

### ISSUE THREAD

**Issue by JamieMason** [danger/danger-js#544]
At least for me, every page at http://danger.systems is returning a 404 at the moment.

![screen shot 2018-03-26 at 09 40 57](https://user-images.githubusercontent.com/320492/37895631-cae63a7a-30d9-11e8-9780-0d3ee83c08d5.png)

**Comment by orta** [comment]
Interesting, everything seems fine on the last deploy 

<img width="747" alt="screen shot 2018-03-26 at 10 20 57 am" src="https://user-images.githubusercontent.com/49038/37911964-6485b250-30df-11e8-8550-e5861f76b1be.png">

Will re-trigger just in case. Might be a good case to consider looking at moving to netlify one of these days

**Comment by JamieMason** [comment]
(FYI this seems to be the same after your trigger earlier)

**Comment by orta** [comment]
Yeah, I got a build on netlify ( http://danger.netlify.com ) but I need to get it deploying from CI before I can look at DNS switching

**Comment by orta** [comment]
Fixed, and DNS is working
