### ISSUE TITLE
[BitBucketServer] reviewers are ids of user

### ISSUE THREAD

**Issue by zdenektopic** [danger/danger-js#546]
Reviewers are ids of the users which are hard to get in BitBucket Server. We have them mapped in URLs and everywhere by username which is also a preferred way to check it. Or it should contain user object with all the information about reviewer.

What I was trying to achieve basically:
```js
const required_reviewers = [
    "zdenek",
    "andrej",
    "luca"
]

required_reviewers.forEach(r => {
    if (!pr.reviewers.includes(r)) {
        fail(`PR is missing \`${ r }\` reviewer`)
    }
})
```

**Comment by orta** [comment]
I'm open to this 👍

**Comment by HannesT117** [comment]
If I understand you correctly, you try to do something like this:
```
const listed_reviewers = danger.bitbucket_server.pr.reviewers.map(
  reviewer => reviewer.user.name
);
required_reviewers.forEach(reviewer => {
  if (!listed_reviewers.includes(reviewer)) {
    fail(`PR is missing \`${ r }\` reviewer`)
  }
});
```
The code above is already working - was this already fixed somewhere somehow?

**Comment by HannesT117** [comment]
@zdenektopic, is this issue still relevant?
