### ISSUE TITLE
[BitBucketServer] Always updates the comment

### ISSUE THREAD

**Issue by zdnk** [danger/danger-js#547]
Seems like the danger is always updating the one comment in the PR instead of deleting it and adding another.
When it is just updated, it is easy to miss.

**Comment by orta** [comment]
That is the correct behavior for Danger, pretty there's a flag on Ruby Danger to always make a new comment each time. You're welcome to port it over if you want that behavior.

**Comment by kasperstorgaard** [comment]
Any idea where the docs for this option would be in ruby (looked around a bit without any luck)

**Comment by orta** [comment]
In the CLI took probably
