### ISSUE TITLE
[BitbucketServer] Add inline mode.

### ISSUE THREAD

**Issue by sunshinejr** [danger/danger-js#549]
So the inline mode was finished (#529), but unfortunately only for GitHub. I would do it as well, butI don't really have an access to BitbucketServer to test it. **BUT**, I can provide guidelines on how to implement this. And I'm gonna try to give as much details as possible, so this task might be a good started for someone that wants to get involved in Danger JS or in Typescript in general.

If you want to figure it all by yourself, just don't read the rest of this issue 😅

## API
First of all, there is the API. Docs for Bitbucket Server are [here](https://docs.atlassian.com/bitbucket-server/rest/5.9.0/bitbucket-rest.html) I believe. So, in [BitBucketServerAPI](https://github.com/danger/danger-js/blob/master/source/platforms/bitbucket_server/BitBucketServerAPI.ts) you would need to add few functions that handle:

- positing inline comments to a pull request, [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L147-L166)
- update inline comments to a pull request, [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L168-L183)
- delete inline comment in a pull request,  [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L117-L123)
- get inline comments in a pull request, [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L273-L282)

## Platform
All of the above will be used in `BitBucket` platform. The most important function in `BitBucket` platform is `supportsInlineComments` function, [here](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L93-L95). Basically `Executor`, the guy that does all the logic for commenting based on platform info, checks if the platform supports inline comments and if not, it will just post all inline comments in the main comment. Right now this function returns `false` in `BitbucketServer`, but after switching it to `true` you also need to make sure that all of the following are implemented:

- [createInlineComment](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L111), [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/GitHub.ts#L132-L142)
- [updateInlineComment](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L120), [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/GitHub.ts#L150-L157)
- [deleteInlineComment](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L129), [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/GitHub.ts#L222)
- [getInlineComments](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L33), [GitHub version](https://github.com/danger/danger-js/blob/master/source/platforms/GitHub.ts#L48)

As you can see, apart from `createInlineComment`, it's just calling the API and returning the Promise to the `Executor`. This function is kinda complicated, at least in GitHub, because based on a line you need to find a "position" in the diff. But, from the API docs, it seems like it's easier on BitBucket as you pass the `line` to the API, instead of calculating the position.

## Templates
In #529 I've already added templates for BitBucket as well, even with tests, so you would just need to test if the template for inline comments is all right. The source file for templates is [here](https://github.com/danger/danger-js/blob/master/source/runner/templates/bitbucketServerTemplate.ts).

## Tests
I already mentioned tests above, so yeah, you would need to test it as well. But, it's a good thing. By using tests you almost don't need to wait on CI to tell you that everything is cool. So, what do we test?

- API. In API we test if the executed function resolves into correct set of parameters for the request. See [this example for GitHub inline comment posting](https://github.com/danger/danger-js/blob/master/source/platforms/github/_tests/_github_api.test.ts#L101-L130).
- Platform. In Platform we test if with given mocked API it returns correct data. See [this example for getting GitHub inline comments parsed](https://github.com/danger/danger-js/blob/master/source/platforms/_tests/_github.test.ts#L102-L107)

## Testing environment
You would also need a testing PR that would verify if your setup works after all. You can see the CI setup on Harvey, for Travis, [here](https://github.com/Moya/Harvey/blob/b4ddd52384b9df0269e749774dc0a952b9a9c7f2/circle.yml).

## Development
Make sure to use `yarn build` and `yarn test` after your changes (or just use Orta's plugin for vscode-jest). `yarn declarations` after the PR as well.

I think this is all the info I needed beforehand, if you spot something there @orta, don't hesitate to edit this post 😅

**Comment by orta** [comment]
Or try the trial of https://wallabyjs.com 🍡

**Comment by codestergit** [comment]
@orta @sunshinejr  I am working on this. I have completed basic RnD.

Bitbucket server rest api provides file inline comments. I will implement it next couple of days.

I will let you know if I needed some help. 

Thanks @sunshinejr  for writing the detailed explanation.

**Comment by sunshinejr** [comment]
I believe that this was implemented in #560, so I'm closing this one 👍
