### ISSUE TITLE
Add debug/verbose mode

### ISSUE THREAD

**Issue by macklinu** [danger/danger-js#55]
Via https://github.com/danger/danger-js/issues/52#issuecomment-268594213, it would be nice to log network requests/responses and other important information in a `--debug` or `--verbose` mode. When a bug report is submitted, having this information would be helpful in debugging via GitHub issues. :octocat:

**Comment by orta** [comment]
I've ported my node-fetch to CURL work from Peril into Danger in #58 - no way to access it yet from CLI

**Comment by kwonoj** [comment]
relates to https://github.com/danger/danger-js/pull/91 .

**Comment by orta** [comment]
https://github.com/danger/danger-js/pull/94 includes this in a few more places

**Comment by orta** [comment]
`DEBUG="*" yarn danger ci` would include a *lot* of debug info now
