### ISSUE TITLE
Danger printed mistaken error message

### ISSUE THREAD

**Issue by stevethomp** [danger/danger-js#554]
In [danger-js/source/runner/Executor.ts, line 200](https://github.com/danger/danger-js/blob/2418999ccc596460ccf64321cf5adce87f1b5bd9/source/runner/Executor.ts#L200), it checks for verbose in the options but logs an error whether or not the commit status was actually set. 

This was confusing during our set up, since the PR passed the dangerfile, but we saw this message in the logs so assumed it had failed.

```
    if (this.options.verbose) {
      console.log("Could not add a commit status, the GitHub token for Danger does not have access rights.")
      console.log("If the build fails, then danger will use a failing exit code.")
    }
```

**Comment by sunshinejr** [comment]
Hey @stevethomp, thanks again for the issue! There is a PR already with the fix 😉
