### ISSUE TITLE
It is overly difficult to debug Dangerfiles

### ISSUE THREAD

**Issue by deecewan** [danger/danger-js#583]
Today, I had some mad issues with a Dangerfile. I eventually narrowed it down to the `diffForFile` crashing on a file that had been removed (that's another, separate issue).

Problems include cryptic error messages, no line numbers to debug with, and, worst of all, apparently no `console.log`? Any time I tried to use `console.log`, it would usually not work.

I'm not really sure why this is the case.

I know it's a pretty massive departure in architecture, and may have been covered before, but:

What is `dangerfile` just exported a function with the following signature:

```js
module.exports = function dangerfile({
  danger,
  warn,
  fail,
  message,
  schedule,
  markdown,
}) {

}
```

Then, danger can just require the dangerfile, and inject in all the things it needs to. That would remove the need to essentially just `eval` the code, give people more control, allow `console.log`, and, most importantly, show line numbers in error messages.

**Comment by orta** [comment]
The scope of non-trivial things danger supports, for example peril and `danger process` basically makes the core architecture complex - see [the architecture doc](https://github.com/danger/danger-js/blob/master/docs/architecture.md), at the trade-off of being able to pull off really big ideas.

I couldn't realistically pass the ownership of evaluation context back to the user and keep those features without their being a second way to run all dangerfiles, and that's a documentation/support nightmare.

**Comment by deecewan** [comment]
yeah that's completely understandable.

is there a simple reason that `console.log` doesn't work? That would solve most debugging. Another thing that Fastlane does is tell you the line number your config crashed on, which would be helpful (I'm pretty sure it does a similar `eval` thing, despite being ruby).

**Comment by orta** [comment]
IMO that's bug - it should work - `console.log`s should get caught by this code: https://github.com/danger/danger-js/blob/master/source/commands/utils/runDangerSubprocess.ts#L50-L55

**Comment by deecewan** [comment]
Alright, let me see if I can put together a MWE.

**Comment by alessbell** [comment]
I'm also trying to figure out why `console.log` doesn't work, wondering if anyone has had success here.

**Comment by fbartho** [comment]
It seems to be working these days. Thoughts on closing this?

**Comment by orta** [comment]
Surre
