### ISSUE TITLE
Installing dangerjs fails behind a firewall because of vm2 dependency

### ISSUE THREAD

**Issue by michaeljacobdavis** [danger/danger-js#591]
I ran into danger failing on install because it looks like https://github.com/danger/danger-js/blob/master/package.json#L139 is referencing https://github.com/patriksimek/vm2/tree/custom_files and sadly, the project I was adding it to is being built behind a firewall (access to npme but not public github).

I saw https://github.com/patriksimek/vm2/pull/92 is open, but doesn't look like that will be merged. I'd be happy to take a crack at a PR if you have any guidance on how to move forward.

Thanks!

**Comment by orta** [comment]
I have merge access, so I've merged a lot of the simpler PRs with this - I don't have access on NPM to ship it though. So my recommendation is to make a request for a new version on vm2 👍

**Comment by michaeljacobdavis** [comment]
🙌Thanks for the really fast response! Commented on that PR.

**Comment by michaeljacobdavis** [comment]
@orta looks like you have publish access now 🎉https://github.com/patriksimek/vm2/pull/92#issuecomment-388349695

Mind publishing and adding the dep to dangerjs whenever you have some time?

**Comment by orta** [comment]
OK, it's in the new version of danger 3.6.6
