### ISSUE TITLE
Fails if many warnings

### ISSUE THREAD

**Issue by LarsJK** [danger/danger-js#604]
It seems like the json between the processes can grow to large.

if I run something like this:

```js
import { warn } from "danger";

for (let i = 0; i < 200; i++) {
    warn('Some warning!');
}
```

It fails with this error:
`Error:  Error: Results passed to Danger JS did not include fails.`

Looks like the JSON is cut of and parsed to {}

**Comment by orta** [comment]
This is likely a dupe of #603

**Comment by LarsJK** [comment]
Yes it's a dupe. I'll close this and follow 603 instead!
