### ISSUE TITLE
wrong result returned by JSONDiffForFile on danger ci

### ISSUE THREAD

**Issue by ionutmiftode** [danger/danger-js#609]
Hello,

so I have a checkYarnLock function that is pretty standard, something like 
```
const checkYarnLock = modifiedFiles => {
        const packageChanged = modifiedFiles.includes('package.json');
        const lockfileChanged = modifiedFiles.includes('yarn.lock');
        danger.git.JSONDiffForFile('package.json').then(packageDiff => {
            const hasDependencyChanges = !!(
                packageDiff.dependencies || packageDiff.devDependencies
            );
            if (hasDependencyChanges) {
                if (!lockfileChanged) {
                    fail('There are "package.json" dependency changes with no "yarn.lock" changes');
                }
            }
        });
    };
```
I have a commit integrated in master (danger passed with no problems) where I deleted some devDependencies from package.json.
However, now when danger runs on a new PR on jenkins danger fails with 
`There are "package.json" dependency changes with no "yarn.lock" changes` 
because `JSONDiffForFile` returns the changes that are already in master (the removed dependencies), so when I `console.log(packageDiff.devDependencies)` it shows something like
```
{ after: { ... },
  before: { ... },
  added: [],
  removed: [ '@types/grid-styled', 'lint-staged', 'react-hot-loader' ] }
```
Stranger is that when running `yarn danger local` there is no error
```
10:32 $ yarn danger local
yarn run v1.7.0
$ /home/ionut.miftode/work/elc-frontend-components/node_modules/.bin/danger local
Danger: ✓ passed review, received no feedback.
```
Also the new commit/PR is made from windows while the rest from ubuntu, if is relevant.

Any thoughts on this?

**Comment by orta** [comment]
Yeah, this looks weird, I've been running this on artsy for maybe a year via [danger-plugin-yarn](https://github.com/orta/danger-plugin-yarn/blob/master/src/index.ts#L226) and I don't think we've seen something like this

**Comment by orta** [comment]
Any chance you can let me (and potential others coming along later) know why you closed this? 

Just because it is working for me, doesn't mean it's perfect 🍡

**Comment by ionutmiftode** [comment]
yes indeed, it works also for me except one PR. It is a really strange/edge case so I just upgraded a package to modify yarn.lock also :)
