### ISSUE TITLE
`danger pr` and `danger ci` crash with lodash import error

### ISSUE THREAD

**Issue by wearhere** [danger/danger-js#629]
When I:
1. Install `danger@3.7.20` (using npm 6.0.0 fwiw)
2. Create a Dangerfile
3. Add an npm script `"danger": "danger pr"`,
4. Run `env DANGER_GITHUB_API_TOKEN=<redacted> npm run danger <PR URL>`

danger crashes with the following:

```sh
Error:  TypeError: lodash_1.includes is not a function
    at /node_modules/danger/distribution/platforms/git/diffToGitJSONDSL.js:13:77
```

And, looking at that file, I'm not sure why it _wouldn't_ do that: it [runs](https://github.com/danger/danger-js/blob/f7ecf6fa516831e5e1e0945614e2658cef267e1b/source/platforms/git/diffToGitJSONDSL.ts#L2)
`import { includes } from "lodash"`, but this package does not install `lodash`. Instead it installs [`lodash.includes`](https://github.com/danger/danger-js/blob/f7ecf6fa516831e5e1e0945614e2658cef267e1b/package.json#L126). And it looks like [all other places in the code](https://github.com/danger/danger-js/search?q=lodash&unscoped_q=lodash) `import includes from "lodash.includes"` instead. So, should `diffToGitJSONDSL.js` also do that? And how is danger not crashing for y'all?

**Comment by wearhere** [comment]
Also happens with `danger ci` fwiw.

**Comment by orta** [comment]
Huh, yeah hah good point, how does this even work?

I guess for everyone else `lodash` is a transitive dependency of something else in the stack and so node resolves it fine, but yeah, that needs to move to `lodash.includes` :D

**Comment by wearhere** [comment]
Thanks @orta !
