### ISSUE TITLE
Allow the use with Bitbucket but without Jira/Issues

### ISSUE THREAD

**Issue by orieken** [danger/danger-js#632]
Should I create a PR for ...
 Allowing Danger to be used without Jira/Issues

currently this gets called when the [server starts up](https://github.com/danger/danger-js/blob/master/source/platforms/BitBucketServer.ts#L79)
`const issues = await this.api.getIssues()`

```
  getIssues = async (): Promise<JIRAIssue[]> => {
    const path = `${this.getPRBasePath("jira")}/issues`
    const res = await this.get(path)
    throwIfNotOk(res)
    return await res.json()
  }
```
[here](https://github.com/danger/danger-js/blob/master/source/platforms/bitbucket_server/BitBucketServerAPI.ts#L115-L120)

but sadly where i am we have a bitbucket server but do not have jira/issues integration
I was thinking of just putting in a guard something like
```
    if (process.env.NO_BITBUCKET_JIRA) {
      return [] as JIRAIssue[];
    }
```
LMK if this is cool ill submit a pr if not any suggestions are appreciated

**Comment by orta** [comment]
Yep, sure this makes sense 👍

**Comment by orieken** [comment]
should be covered by #911

**Comment by platan** [comment]
I guess we can close this issue now.

**Comment by orta** [comment]
ace
