### ISSUE TITLE
[BitbucketServer] com.atlassian.bitbucket.DataStoreException when posting danger output

### ISSUE THREAD

**Issue by acecilia** [danger/danger-js#634]
Node v10.6.0.
Danger 3.7.20.
Danger-swift cloned from master (most recent version).

I am running the following:

```
export DANGER_FAKE_CI="YEP"
export DANGER_TEST_REPO='repo'
export DANGER_TEST_PR='123'
export DEBUG="*"
danger process danger-swift
```

Everything works well, and danger is properly executed until the last moment. I even see what danger-swift returns to process, which seems fine (does not seem to be a danger-swift issue):
<img width="542" alt="screen shot 2018-07-17 at 05 51 58" src="https://user-images.githubusercontent.com/7938671/42795629-9cea5494-8985-11e8-8108-fdd8828e54bf.png">

 But just some lines after, when it is doing the post of the "no CHANGELOG entry added" comment to the Bitbucket API it fails with error 500:

```
Response: {
  "errors": [
    {
      "context": null,
      "message": "A database error has occurred.",
      "exceptionName": "com.atlassian.bitbucket.DataStoreException"
    }
  ]
}
```

I was pretty sure that was an issue with my bitbucket configuration, but after testing with curl and using the same POST request, the comment appeared in the PR successfully in all my tests.

Maybe an encoding issue?

I already spent several hours with this, and I run out of ideas. Any insight would be very much welcome. Thanks :)

**Comment by orta** [comment]
Sorry, I have no clue, I don't use bitbucket. 

These are all the API calls Danger is making when posting the comment: https://github.com/danger/danger-js/blob/master/source/platforms/bitbucket_server/BitBucketServerAPI.ts#L122-L238

**Comment by acecilia** [comment]
Okey, I found the issue. The emojis are causing it :(

**Comment by orta** [comment]
Hah, well, that at least should be fixable somehow in Danger JS

**Comment by acecilia** [comment]
@orta is there an option to stop using emojis?

**Comment by orta** [comment]
Not really, but ideally we don't have an option like that - I mean, bitbucket supports emojis in comments, so I'm not sure why using the API it fails in your case, maybe try check out their API docs to see if there's some special setting around content types?

**Comment by acecilia** [comment]
@orta I can not confirm if they support emoji or not. In my bitbucket server setup, commenting on web with any emoji (copy pasted) results in a database error.

From: https://jira.atlassian.com/browse/BSERV-3069

> Bitbucket 5.0 has been released with Emoji support. It supports the standard smileys, the twemoji set of emojis and Hipchat emojis (including custom emojis) if Hipchat is integrated with Bitbucket Server. 

Is there any way I can pipe danger output to remove emoji before the comment request?

**Comment by acecilia** [comment]
@orta Sorry to insist, but if somebody know its you ;P Is there any way I can pipe danger output to remove emoji before the comment request?

**Comment by orta** [comment]
Be wary, danger is just a spare time project for me, over a day is very reasonable for me to get back to you.

However, no, not without writing code I'm afraid.
