### ISSUE TITLE
Creates only one inline comment at the time

### ISSUE THREAD

**Issue by stefanbuck** [danger/danger-js#656]
Hi, today I added danger to a repository at work where I encountered a strange behaviour. My dangerfile is reading eslint errors from a json file. In my example Pull Request I have four eslint errors. I'm use `fail(message, filePath, line)` to get inline 

Running the CI for the first time was adding a single comment on the PR, where I expected to see four inline comments. A second run was adding one inline comment and added the remaining three issues to a single comment. Guess what happened after running the CI again, it added another inline comment (so two inline comments in total) added the other two as a single comment.

I checked your documentation and I couldn't find any information about any inline comment limits. Everything was good, GitHub API rate limit wise.

Since I'm able to reproduce this issue, I think this is a bug.

**Comment by stefanbuck** [comment]
Was able to reproduce it here as well  https://github.com/OctoLinker/OctoLinker/pull/503

**Comment by orta** [comment]
Interesting - we've not seen this at Artsy, I'd recommend running danger with the debug turned on to see if anything pops out at you:

```sh
DEBUG="*" yarn danger ci
```

**Comment by orta** [comment]
Ah, no this is just a constraint on how GitHub's inline comments work - you can't comment on something that isn't in the PR's diff - those comments get added back into the main comment instead of not appearing in the diff at all. This works as expected. 👍

**Comment by stefanbuck** [comment]
but all of them are part of the PR diff

- [packages/core/app.js#L4](https://github.com/OctoLinker/OctoLinker/pull/503/files#diff-a57da3c75d34357f0ffc1e605fe99e66R4)
- [packages/helper-grammar-regex-collection/index.js#L5 ](https://github.com/OctoLinker/OctoLinker/pull/503/files#diff-2fa1357b553548285d1b816e5aba40efR5)

Also they become inline comments one by one when running the CI job over and over again.

**Comment by orta** [comment]
Ah, yeah, that sounds like a legit bug then, I don't really use inline messages myself - so I'm leaving this free for someone to fix 👍

**Comment by shubhodeep9** [comment]
@orta I am interested to fix this.
I'd like to know what is the desired result.
Cheers

**Comment by stefanbuck** [comment]
This issue has been fixed already https://github.com/danger/danger-js/pull/663
