### ISSUE TITLE
Could not find the type of CI for Danger to run on.

### ISSUE THREAD

**Issue by muuvmuuv** [danger/danger-js#657]
Hey, I've set up danger through this guide here: https://danger.systems/guides/getting_started.html and got stopped by this error:

```
→ bundle exec danger
Could not find the type of CI for Danger to run on.
```

I'm using a privately hosted GitLab server and therefore I setup my env variables in my `.bash_profile` like this:

```
export DANGER_GITLAB_HOST=https://git.XXX.de/
export DANGER_GITLAB_API_BASE_URL=https://git.XXX.de/api/v4
```

and created an environment variable in GitLan for my project where the bot has access to.

I have also created a Dangerfile through the `bundle exec danger init` and installed `danger-gitlab` with bundler. Here are my bundle and Dangerfile:

```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'danger-gitlab'
```

```
message("HEY")
```

System OS: Mac OS 10.14 Beta (18A371a)
Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Bundler: Bundler version 1.16.4
Danger (global): 5.6.4

**Comment by orta** [comment]
Hey there, this is the repo for Danger JS (which doesn't support gitlab ) I'd recommend closing this and recreating it on danger/danger where you're more likely to get a response from someone who has set up gitlab support before

**Comment by muuvmuuv** [comment]
@orta alright thanks, didn't know that!
