### ISSUE TITLE
Problem with babel config

### ISSUE THREAD

**Issue by sibelius** [danger/danger-js#664]
this is my babel.config.js
```
module.exports = {
  presets: [
    '@babel/preset-react',
    '@babel/preset-flow',
    [
      '@babel/preset-env',
      {
        modules: false,
      },
    ],
  ],
  plugins: [
    'react-hot-loader/babel',
    'loadable-components/babel',
    'babel-plugin-styled-components',
    [
      'relay',
      {
        schema: 'data/schema.json',
      },
    ],
    'material-ui',
    'lodash',
    '@babel/plugin-proposal-object-rest-spread',
    '@babel/plugin-proposal-class-properties',
    '@babel/plugin-proposal-export-default-from',
    '@babel/plugin-proposal-export-namespace-from',
  ],
  overrides: [
    {
      test: ['./src/**/*.ts'],
      presets: [
        '@babel/preset-typescript',
        [
          '@babel/preset-env',
          {
            modules: false,
          },
        ],
        '@babel/preset-react',
      ],
    },
  ],
  env: {
    test: {
      presets: ['@babel/preset-flow', '@babel/preset-env', '@babel/preset-react'],
      plugins: [
        '@babel/plugin-transform-runtime',
        'dynamic-import-node',
        '@babel/plugin-syntax-dynamic-import',
        '@babel/plugin-proposal-object-rest-spread',
        '@babel/plugin-proposal-class-properties',
        '@babel/plugin-proposal-export-default-from',
        '@babel/plugin-proposal-export-namespace-from',
      ],
    },
  },
};
```

it throws the following error

`Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel`

because of overrides syntax that needs to accept a filename

I've solved this passing `filename` to babel transform:

```jsx
const code = babel.transformSync(preprocess(cmd), {
    presets: [...]
    plugins: [...]
    filename: './babel.config.js', // hacky to make overrides works
  }).code;
```

**Comment by orta** [comment]
Interesting, we're definitely [passing the filename](
https://github.com/danger/danger-js/blob/master/source/runner/runners/utils/transpiler.ts#L78-L97) in at transform - I wonder if it's needed for the get options beforehand?

**Comment by orta** [comment]
Maybe we need to set `sourceFilename`?

**Comment by milesj** [comment]
Running into this also now. Is babel/ts transpilation really necessary? This definitely feels like something that shouldn't exist.

**Comment by afenton90** [comment]
I narrowed this down to having a pattern in something like an `ignore` field for example a config file like this `babel.config.js` caused the error:
```js
module.exports = {
  plugins: [...],
  presets: [...],
  ignore: ['**/public/*.js']
};
```

For me I realised I didn't need this particular ignore.
I couldn't find the magic combination of options for `babel.transform` to get it to work.
Hope that gets this issue a step closer.

**Comment by orta** [comment]
Maybe danger can override the ignore with something empty in the config?
