### ISSUE TITLE
Stream of NPM releases

### ISSUE THREAD

**Issue by hanneskaeufler** [danger/danger-js#681]
My greenkeeper bot is spamming me with multiple daily updates to danger, as can also be seen on npm: https://www.npmjs.com/package/danger

But the repo itself here has not seen any more tags/releases or code changes. Does anyone know what's up and who is pushing the npm releases?

**Comment by orta** [comment]
Ah, nah - I guess I need to move to shipping betas instead

Some of my current work can only happen in a production venue
