### ISSUE TITLE
Port codebase to TypeScript

### ISSUE THREAD

**Issue by macklinu** [danger/danger-js#76]
Via https://github.com/danger/danger-js/pull/71#issuecomment-269869256

Is this something we'd like to move forward with? I personally enjoy writing TS. Haven't converted Flow to TS before, so I'm not sure if it's something we could do incrementally or maybe doing it all in one shot isn't a difficult task. 

Any thoughts? /cc @orta @kwonoj

**Comment by kwonoj** [comment]
Most of syntax between flowtype and Typescript are compatible, so it won't be too hard enough to convert existing codebases into Typescript if needed. I also personally way prefer to use typescript in general, only concern is setting up pipelines while migrating / and troubleshoot possible issues I can't think of as I don't have full visibility of codebase yet.

Migration itself should be incremental, probably can use TypeScript's `allowJS` compiler config to consume JS as is while it's happening.

**Comment by orta** [comment]
I'm happy for it to happen, it generally can be pretty incremental, considering we already have typed javascript. 

The tricky bit will be making sure all the interfaces work fine ( Flow: `?Thing`, TS: `Thing | null` ) sort of stuff, but there's not many of those.

**Comment by orta** [comment]
I'm definitely fine to handle all edge cases around deployment, tooling etc if someone gets something working 🍡

**Comment by kwonoj** [comment]
I'll try to see if I can introduce gradual migration process. Can't say it'll be soon though since holidays are over :)

**Comment by macklinu** [comment]
I'll try to get something started this week, maybe introducing a `tsconfig.json` (will reference the Peril codebase) and migrating over a couple files to see what it's like. Will follow up here if I get a branch pushed up @kwonoj 😄
