### ISSUE TITLE
Posting GitHub comments instead of populating Checks page?

### ISSUE THREAD

**Issue by hawkrives** [danger/danger-js#765]
(I saw https://github.com/danger/danger-js/issues/592, which might actually be closable now. Anyway, I think this is distinct from it.)

Is it possible to flip a switch and have Danger post comments in the PR thread again, instead of hiding them away in the GitHub checks page? I know Danger posts the comment saying "hey, go check out the checks page! You have N warnings and N failures.", but I really liked the old (months-old) behavior of posting in the thread.

(If the solution is "write your own GitHub#comment wrapper", well, I can do that too 😸 – just thought I'd check beforehand.)

**Comment by orta** [comment]
There’s a not user facing option for this, which peril uses to disable it, I’m happy to make “use checks” be an option in the cli and default to issues only now. It’d be a major semver change, but I’m gsme

**Comment by hawkrives** [comment]
Cool 😎

**Comment by hawkrives** [comment]
Thanks, @orta and @cysp!
