### ISSUE TITLE
local mode don't work without credentials

### ISSUE THREAD

**Issue by langovoi** [danger/danger-js#767]
When I try to use `danger local` without BitBucket or GitHub credentials i got error on [this line](https://github.com/danger/danger-js/blob/master/source/commands/danger-runner.ts#L51)

```sh
The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST environmental variable is missing
```

**Comment by orta** [comment]
Ah yeah, this is likely an oversight because I have `DANGER_GITHUB_API_TOKEN` in my ENV, it should be passing in the FakeCI env vars from the command
