### ISSUE TITLE
`JSONPatchForFile` is broken

### ISSUE THREAD

**Issue by langovoi** [danger/danger-js#772]
When I try to use `JSONPatchForFile` with `danger local` or on CI with Bitbucket Server I got error [here](https://github.com/danger/danger-js/blob/0afefa839097466744aa3551dbdda539f3a3b5f8/source/platforms/git/gitJSONToGitDSL.ts#L70).

```Error:  { SyntaxError: JSON5: invalid character 'i' at 1:1```

**Comment by langovoi** [comment]
Maybe because `LocalGit` and `BitBucketServer` return content of file (string) in `getFileContents`?

I don't know what returns GitHub, but by code it not looks like content of file.

**Comment by orta** [comment]
Yeah, GitHub returns an object with a  base64'd version of the code - I think I added `getFileContents` so that there would be a consistent "url" -> "code" function across them all, maybe I didn't use it in there?

**Comment by langovoi** [comment]
Oh, sorry, I iterating by array with filenames, but not all of these are json. Closed :-)
