### ISSUE TITLE
`message` not outputting rendered markdown anymore

### ISSUE THREAD

**Issue by hanneskaeufler** [danger/danger-js#776]
I have a plugin [danger-plugin-mentor](https://github.com/hanneskaeufler/danger-plugin-mentor) that randomly adds a tip to any open PR. It uses `message` to add a message to a PR. Up until a while ago, this properly rendered a link in markdown. Now however, the link is added as a raw message.

## Before

<img width="771" alt="bildschirmfoto 2018-11-27 um 21 11 27" src="https://user-images.githubusercontent.com/68024/49108691-1c0f3480-f289-11e8-8fd8-eb831e5d870c.png">

## Now

<img width="772" alt="bildschirmfoto 2018-11-27 um 21 11 47" src="https://user-images.githubusercontent.com/68024/49108705-25000600-f289-11e8-9810-d2ae549d68d3.png">

My plugin is using e.g. `message("Hi there [hello](https://www.hello.com)")`. Does that intentionally not work anymore? Am I using a wrong assumption here?

I pinned danger to `6.0.0` to see when this broke and `6.0.0` is still good. Could [this](https://github.com/danger/danger-js/pull/754) be a cause?

**Comment by orta** [comment]
Good point, I think we should look in the message for any indicators of a markdown message e.g. 

```
` [ ( _ *
```

and revert to the original behavior from before #754 for those messages
