### ISSUE TITLE
DangerJS fails in github actions

### ISSUE THREAD

**Issue by mattyfresh** [danger/danger-js#782]
Hello!  Trying to figure out the best way to run danger via GitHub actions.  I have gotten to the point of the action running and finding my dangerfile no problem, but the `danger.github` API is coming back `null`.

I have seen this happen when I run the `danger local` command as well, where the other namespaces (eg `danger.git`) are fine, but clearly there is no PR to reference so the `danger.github` response being `null` makes sense to me.

Here is that config:
```
workflow "Dangerfile JS Eval" {
  on = "pull_request"
  resolves = "Danger JS"
}

action "Danger JS" {
  uses = "danger/danger-js@master"
  secrets = ["GITHUB_TOKEN"]
  args = "--dangerfile ./dangerfile.ts"
}
```

I have also tried just running a typical bash script via github actions (just following the docs, with a `Dockerfile` and an `entrypoint.sh`).  I can run the following script and have the same issue:

```bash
#!/bin/sh -l

set -eu

export DANGER_GITHUB_API_TOKEN="$GITHUB_TOKEN"
yarn global add danger

# Run danger
danger --dangerfile="./dangerfile.ts" ci
```
This yields a `null` value for `danger.github` as well.

My last attempt was to use the `--external-ci-provider "GitHubActions"` and I got this response:
`could not load CI provider at GitHubActions due to Error: ENOENT: no such file or directory, stat '/github/workspace/GitHubActions'`

Again, I can run the `danger pr https://github/path/to/pr` and it runs fine, and that bash script currently works on our `CircleCi`.

Any information/links/examples for Github Actions you can provide would be really helpful!  If there is someway I can help document/contribute let me know.

Thanks!

**Comment by orta** [comment]
I'm not sure, I know I did get it working back doing the closed beta but I don't have any private repos to test it on - it's possible that some of the settings and env vars that were used back then have changed as they've got closer to production. Once public repos can be used, I'll be getting it running on this repo and running with every update etc, but until then I've been pretty hands off

I'd recommend comparing the current docs to - [ci_source/providers/GitHubActions.ts](https://github.com/danger/danger-js/blob/master/source/ci_source/providers/GitHubActions.ts) to see if it all still matches up

**Comment by fbartho** [comment]
I'm exhibiting a similar issue with Github Actions where `danger.github.pr` is absent. -- I'm directly running danger from my node_modules on a `pull_request`-initiated-workflow. I've logged out the /github/workflow/event.json file, but everything seems fine, and it does have the PR Data. Any ideas?

**Comment by fbartho** [comment]
I concur that the linked PR fixed my issue!

**Comment by mattyfresh** [comment]
Ah ok, looks like running the commands manually inside of my `entrypoint.sh` file (as per the [Github Actions docs](https://developer.github.com/actions/creating-github-actions/creating-a-new-action/)) works 👍

**Comment by mcpengelly** [comment]
@threadbot can you post your sample? Still having trouble myself...

**Comment by mcpengelly** [comment]
@mattyfresh what exactly did you end up using?

**Comment by mcpengelly** [comment]
For those that come after me. I'll provide what i got working based on @mattyfresh advice:

<project root>/run-danger/Dockerfile
```
FROM node:8

LABEL "com.github.actions.name"="dangerjs"
LABEL "com.github.actions.description"="run dangerjs pr checks"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="purple"

ADD entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

<project root>/run-danger/entrypoint.sh
```
#!/bin/sh -l

# Install danger cli on the machine
yarn global add danger

# install needed dependencies
yarn

# Run danger
danger --dangerfile "./dangerfile.js" ci
```


<project root>/.github/main.workflow
```
workflow "Dangerfile JS Eval" {
  on = "pull_request"
  resolves = "Danger JS"
}
action "Danger JS" {
  uses = "./run-danger/"
  secrets = ["GITHUB_TOKEN"]
}
```

Hope this helps someone.
