### ISSUE TITLE
jest-environment-node missing

### ISSUE THREAD

**Issue by dblock** [danger/danger-js#83]
Trying to add to https://github.com/artsy/elderfield/pull/42

```

> elderfield@0.0.1 danger /home/travis/build/artsy/elderfield
> danger
module.js:327
    throw err;
    ^
Error: Cannot find module 'jest-environment-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/artsy/elderfield/node_modules/danger/distribution/runner/DangerfileRunner.js:131:28)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by orta** [comment]
Just tested on a blank project (admittedly using yarn so I can get a lock file ) and this is _looking_ fine  ATM, will test it on CI ( https://github.com/PerilTest/PerilPRTester/commit/7142a7130dd32363024aed443eaf8fa98b29ceda )

**Comment by orta** [comment]
[Added CI to the repo](https://travis-ci.org/PerilTest/PerilPRTester/builds/189604923), and still not able to reproduce. Gonna see if npm is different here.

**Comment by orta** [comment]
That's fine too, I wonder if there's specific to the babel setup that requires it, will have to test on that project.

**Comment by yannickcr** [comment]
`jest-environment-node` is missing in the `package.json` but is present in the `yarn.lock`.

So if you try to install danger with `npm install` then `jest-environment-node` will not be installed.

**Comment by orta** [comment]
Ah! Alright, so we should add `jest-environment-node` to the Package.json then?

**Comment by orta** [comment]
I'm pretty surprised that yarn takes yarn.lock files into account

**Comment by tivac** [comment]
I installed `danger` just now & it included `jest-environment-node`.

```
> npm i danger
modular-css@2.0.2 C:\Users\Patrick\Documents\Code\modular-css
`-- danger@0.9.0
  +-- jest-runtime@18.1.0
  | +-- jest-config@18.1.0
  | | +-- jest-environment-node@18.1.0
```

npm install output edited a bit for brevity, but it's definitely there on windows at least.

**Comment by macklinu** [comment]
I was able to install and run danger v0.9.0 on Jenkins CI yesterday by running `yarn add danger --dev` and adding a `"danger": "danger"` npm script per the README. I didn't run into this issue.

We [do require `jest-environment-node` here](https://github.com/danger/danger-js/blob/20ef51a41ef611a7c2d45e768398c6b7d8d7449f/source/runner/DangerfileRunner.ts#L2), so maybe it'd be good practice to add it to danger's `package.json`? Just throwing that out there, not sure if that matters one way or another.

**Comment by orta** [comment]
Yeah, I think that's fair, it's not being used as a transitory dep. So I'm 👍 for adding it to the package.json

**Comment by macklinu** [comment]
👍  I will open a PR shortly

**Comment by orta** [comment]
Hah, I was just doing this now

**Comment by macklinu** [comment]
Ok, you can do it since I haven't started yet if you're already doing it haha

**Comment by macklinu** [comment]
![Giphy](http://media0.giphy.com/media/1HPzxMBCTvjMs/giphy.gif)

Team work!
