### ISSUE TITLE
Running Danger in two separate CI builds only outputs one status

### ISSUE THREAD

**Issue by randak** [danger/danger-js#839]
In order to optimize our PR build speeds, we decided to split our builds in two, one which runs our build and one which runs our tests.

Based on past issues, I saw that it should be possible to run danger in each of these builds and have them report back to the PR. I was able to accomplish this by setting the `dangerId` flag.

This was working great for a few days, but today we discovered that while Danger posts two separate comments, it doesn't post two separate build statuses. If my tests run faster, and they have issues, but my build does not, Danger will briefly reflect the right status (failed), and then when the build finishes, it'll update this to a success.

This is obviously not desirable, as it means Danger is now incorrectly indicating that the build is passing. 

I would like the dangerId to be reflected in the name of the Github statuses, or at the very least enable opting out of Danger posting its own status altogether and just letting it fail the build. We run most things in our build through danger anyway, so having the build pass when Danger finds an issue is sort of weird.

I started poking around at Github's status APIs to see if there was an easy way to do this, but I'm not yet familiar enough with either them or Danger's codebase to figure it out tonight. I'm hoping it's as simple as piping the dangerId through to an API somewhere but it wasn't immediately clear to me how Github determines whether to create a new status or update an existing one.

Can you help me figure out how to enable the functionality we need? Thanks in advance!

**Comment by orta** [comment]
I think you'd need to add the Danger ID to the context of the [commit status](https://developer.github.com/v3/repos/statuses/#create-a-status) - I don't think we ever do an update, only create new ones which overwrite the only one

**Comment by fbartho** [comment]
@randak I'd love to do this myself so I can have a Github comment that dynamically gets updated when new builds pop out of our CI. -- We're running our primary dangerfile & unit-tests using Github-actions.

If you have a gist of how you accomplished this, I'd be thrilled. I'd also be happy to help get this working & tested & even to help write docs. I have no special understanding about how this part of Danger-JS works, however!

**Comment by randak** [comment]
@orta I've opened a PR to provide this functionality, let me know what you think!

@fbartho FYI, see #840. In the meantime, we are working around this issue by doing the following.

For multiple comments, you just need to set an ID in the CLI such as: `danger ci --id Danger/Build`. The ID should be different for each separate danger configuration, but it should be the same every run or danger won't be able to update its comments.

The unsupported feature currently is the status. To work around that, I've wrapped `fail` from Danger in a helper function which tracks whether there are any fails. If there are fails, I exit the process. So we explicitly fail the build and ignore the Danger status report. This is fine for now but it's not great to have a status you can't trust, so hopefully we can get my PR in quickly to solve it.

**Comment by randak** [comment]
<img width="784" alt="Screenshot 2019-03-14 18 50 58" src="https://user-images.githubusercontent.com/2506770/54354816-231c5000-468a-11e9-97a7-fa5d9253c42a.png">

Just tested it out on our codebase; it works 👍 

@fbartho FYI, you can use the functionality now in `7.0.15`.
