### ISSUE TITLE
create a dummy test repo and run it against every new release

### ISSUE THREAD

**Issue by dblock** [danger/danger-js#84]
For issues like https://github.com/danger/danger-js/issues/83 it would be good to have a test repo that maybe makes a version update on a trigger for every new danger.js release.

**Comment by kwonoj** [comment]
Or maybe this repo's PR run danger twice, one for latest stable release from npm, one for linked from given PR to verify regression & sanity.

**Comment by orta** [comment]
We do have CircleCI running a separate build, I think it would be 👍 to move that to use the latest stable build instead of master which Travis runs.

**Comment by orta** [comment]
Fixed by https://github.com/danger/danger-js/pull/172
