### ISSUE TITLE
Markdown rendered out of order

### ISSUE THREAD

**Issue by chrisjaure** [danger/danger-js#845]
Since upgrading from `3.3.0` to any version above `3.4.6` (for babel 7 compat), our calls to `markdown` have been rendering out of order in github pr comments.

I've verified in CI that the `markdowns` array is in the correct order, but when the comment is rendered, it's out of order. The order seems to be consistent though, and it will not change between subsequent pushes to the pr. The order did change, however, when I enabled debugging.

Using babel with or without presets makes no difference, but this is what I have now:
```
['@babel/preset-env', { targets: { node: 'current' } }]
```

Node version: `v9.6.1`

Let me know if there's any other info you need to debug the info.

**Comment by orta** [comment]
Sounds like a bug yeah, I can't think of anything offhand which change which could make it indeterminate but never know with these types of things

**Comment by jamime** [comment]
I've noticed multiple calls to markdown are rendered in reverse order too.
