### ISSUE TITLE
`danger.d.ts` references Chainsmoker but doesn't import it

### ISSUE THREAD

**Issue by paulmelnikow** [danger/danger-js#852]
`danger.d.ts` references `Chainsmoker`:

https://github.com/danger/danger-js/blob/b64b42ad93fa364532de9b44a9efb60bce63c465/source/danger.d.ts#L707

but it's not imported.

1. What's the best way to fix this? Should `danger.d.ts` import `Chainsmoker` from `chainsmoker.ts`?

2. Would it be worth adding a step that runs `danger.d.ts` – or better yet some code that imports and uses it – through `tsc` (a la DefinitelyTyped) to catch issues like this in the future?

**Comment by orta** [comment]
I thought I used to do this on CI (though it might just be the flowtypes defs, which also should have failed... Hrm.)

Anyway, I think the key here is to get it auto-imported into the main `danger.d.ts` via the generation script - if I get some time today, I'll make sure to include it and see about making it run dtslint on the CI -thanks!

**Comment by paulmelnikow** [comment]
Think this is sorted.
