### ISSUE TITLE
Danger uses name "default" instead of "Danger" for GitHub API status

### ISSUE THREAD

**Issue by sgtcoolguy** [danger/danger-js#853]
This looks to a be a result of merging #840 

I see that there's an attempt to use "Danger" by default here: https://github.com/danger/danger-js/commit/69b41986c3adaa872811e74bb515a33d613b55d3#diff-b77e13a15617a77791367e0df9de18c7R363

I assume that one of these is the root cause:
- https://github.com/danger/danger-js/blob/8e886f52983283b3fe855a4aa12c0ba46def2017/source/commands/ci/runner.ts#L65
- https://github.com/danger/danger-js/blob/8e886f52983283b3fe855a4aa12c0ba46def2017/source/commands/danger-process.ts#L93

**Comment by orta** [comment]
Nice spot, yeah, I think the fallback here should probably be "Danger" instead of default then!

**Comment by milesj** [comment]
Noticed this as well. Nice to know its a bug here and I wasn't going crazy!

**Comment by orta** [comment]
That got shipped
