### ISSUE TITLE
Is Danger always making a new comment?

### ISSUE THREAD

**Issue by orta** [danger/danger-js#856]
I keep seeing notifications in Slack about new comments by Danger, when they should be being edited.

**Comment by jmenestr** [comment]
I am also seeing this. I'm using `9.2.2` and currently see a new comment.

I can inspect each comment's markdown and see the same `dangerid` for each comment.

I was also under the impression that it should search all the comments for ones with the same `dangerid` and update them, rather than create a new one.

**Comment by tamlenguyen** [comment]
Same for me, adding a new comment every time

**Comment by nick28** [comment]
Same for me in Bitbucket Cloud, any updates or any leads how can we solve this?

**Comment by orta** [comment]
Each platform has a `updateOrCreateComment` which must not be doing what we expect

- https://github.com/danger/danger-js/blob/6ae125dca11f88c270da0f15a16c91785d2304a7/source/platforms/BitBucketCloud.ts#L100
- https://github.com/danger/danger-js/blob/6ae125dca11f88c270da0f15a16c91785d2304a7/source/platforms/github/comms/issueCommenter.ts#L133

**Comment by HelloCore** [comment]
> Same for me in Bitbucket Cloud, any updates or any leads how can we solve this?

For `Bitbucket Cloud`, we need `DANGER_BITBUCKETCLOUD_UUID` to detect the owner of the comment.
Could you check your UUID?
It has to be this format `{zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz}`. (38 characters including brackets).

**Comment by orta** [comment]
That doesn't feel right to me - the bot should be able to ask for it's own user ID via the API and it likely does

**Comment by HelloCore** [comment]
Yes, that's right, I've never thought about that before. 
I'm going to work on this.

**Comment by nick28** [comment]
> > Same for me in Bitbucket Cloud, any updates or any leads how can we solve this?
> 
> For `Bitbucket Cloud`, we need `DANGER_BITBUCKETCLOUD_UUID` to detect the owner of the comment.
> Could you check your UUID?
> It has to be this format `{zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz}`. (38 characters including brackets).

I had set it as mentioned in the documentation. And yes it is in the format as mentioned by you

**Comment by HelloCore** [comment]
> > > Same for me in Bitbucket Cloud, any updates or any leads how can we solve this?
> > 
> > 
> > For `Bitbucket Cloud`, we need `DANGER_BITBUCKETCLOUD_UUID` to detect the owner of the comment.
> > Could you check your UUID?
> > It has to be this format `{zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz}`. (38 characters including brackets).
> 
> I had set it as mentioned in the documentation. And yes it is in the format as mentioned by you

We've just released version 9.2.9, could you remove `DANGER_BITBUCKETCLOUD_UUID` and try this version?
You might need to create the new credentials with `Read Pull requests` and `Read Account`.

I suspect that this issue would have something to do with brackets, some CI might encode it. At 9.2.9, we fetch UUID from Bitbucket Cloud Instead, and it works fine for me.

**Comment by nick28** [comment]
> > > > Same for me in Bitbucket Cloud, any updates or any leads how can we solve this?
> > > 
> > > 
> > > For `Bitbucket Cloud`, we need `DANGER_BITBUCKETCLOUD_UUID` to detect the owner of the comment.
> > > Could you check your UUID?
> > > It has to be this format `{zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz}`. (38 characters including brackets).
> > 
> > 
> > I had set it as mentioned in the documentation. And yes it is in the format as mentioned by you
> 
> We've just released version 9.2.9, could you remove `DANGER_BITBUCKETCLOUD_UUID` and try this version?
> You might need to create the new credentials with `Read Pull requests` and `Read Account`.
> 
> I suspect that this issue would have something to do with brackets, some CI might encode it. At 9.2.9, we fetch UUID from Bitbucket Cloud Instead, and it works fine for me.

Seems to be fixed and danger is now updating the comments in bitbucket cloud. Tested with `DANGER_FAKE_CI="YEP"`

**Comment by zhongliangwang** [comment]
It still creates new comments on Github

**Comment by mokagio** [comment]
Same as @zhongliangwang, I'm seeing new comments on GitHub as well.

<img width="944" alt="Screen Shot 2020-02-07 at 21 34 57" src="https://user-images.githubusercontent.com/1218433/74022602-fbe11680-49f1-11ea-8540-62fd7815a867.png">

I made a dedicated repo to reproduce 👉 https://github.com/mokagio/danger-new-comments-example/pull/3.

I [tried to fetch Danger JS from `master`](https://github.com/mokagio/danger-new-comments-example/pull/4) but I [couldn't get it to work](https://github.com/mokagio/danger-new-comments-example/pull/4#issuecomment-583331800).

**Comment by mokagio** [comment]
I made a new test, with a `Dangerfile` looking like this, to remove any kind of custom logic that could have resulted in the issue.

```ts
import {warn} from "danger";

warn("This demo warning was generated on " + new Date());
```

Same result.

![screencapture-github-mokagio-danger-new-comments-example-pull-5-2020-02-08-10_24_27](https://user-images.githubusercontent.com/1218433/74073143-5a8faa00-4a5d-11ea-899d-bd7ee55bd45a.png)

**Comment by mokagio** [comment]
FWIW, the Ruby version doesn't have this issue. See https://github.com/mokagio/danger-new-comments-example/pull/6.

<img width="979" alt="Screen Shot 2020-02-08 at 10 47 08" src="https://user-images.githubusercontent.com/1218433/74073994-6e88db00-4a60-11ea-9e77-ad918879c709.png">

**Comment by mokagio** [comment]
I did a bit more investigation, and saw that [Danger JS also makes multiple comments  when given `file` and `line`](https://github.com/mokagio/danger-new-comments-example/pull/7).

<img width="1266" alt="Screen Shot 2020-02-10 at 12 39 17" src="https://user-images.githubusercontent.com/1218433/74115262-80a27f00-4c02-11ea-9017-16684d1b14a9.png">

**Comment by orta** [comment]
Interesting! Yeah, that check and update code was done before inline comments were added, and it makes sense why I rarely see it (I don't use multiline anywhere)

My bet? the check to find the existing main comment might be hitting these and thinking there isn't an issue to update

**Comment by f-meloni** [comment]
I think the reason why is doing multiple comments is that you are using 

```swift
 GITHUB_TOKEN: ${{ secrets.MOKAGIO_BOT_GITHUB_TOKEN }}
```

Try

```swift
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Actions doesn't allow you to call `https://api.github.com/user`, that is what danger-js uses to get the current user.

(this is the response you get)
```
Request failed [403]: https://api.github.com/user
Response: {
 "message": "Resource not accessible by integration",
 "documentation_url": "https://developer.github.com/v3/users/#get-the-authenticated-user"
}
```
This is why the user id is hardcoded, then if you don't use the actions user danger can not understand which comment is the danger comment and edit it.
I wonder how danger ruby does this.

**Comment by mokagio** [comment]
Hey @f-meloni, you're spot on! Once I [changed the action `GITHUB_TOKEN` value to `secrets.GITHUB_TOKEN`](https://github.com/mokagio/danger-new-comments-example/commit/1be3041b12e1ea8cae5ddc7242b8a9975d99c7a8) it worked as expected. 🎉 🎉 Thanks a lot! 🙏 

<img width="957" alt="Screen Shot 2020-02-11 at 13 01 31" src="https://user-images.githubusercontent.com/1218433/74206286-d3496d00-4cce-11ea-97e6-595b549e16eb.png">

<img width="991" alt="Screen Shot 2020-02-11 at 13 11 09" src="https://user-images.githubusercontent.com/1218433/74206546-fd4f5f00-4ccf-11ea-8247-ee8de643be8c.png">

Clearly, my understanding of what that token should have been was wrong. Or rather, I didn't spend enough time reading the docs. I though that the `GITHUB_TOKEN` we talk about in the Danger + GitHub Action guide was just the arbitrary name used to pass [the token one has to generate if they want to use Danger](https://danger.systems/js/guides/getting_started.html#setting-up-an-access-token). But actually, `GITHUB_TOKEN` refers to [the token GitHub provides a token that you can use to authenticate on behalf of GitHub Actions](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). 🤦‍♂️

What I might do is open a PR to add the link to the `GITHUB_TOKEN` documentation in the Danger + GitHub Actions section. This way future me won't make the same mistake again. 🤞 

Thanks again folks! ❤️

**Comment by mokagio** [comment]
Hey @f-meloni, in [your comment](https://github.com/danger/danger-js/issues/856#issuecomment-584085043) you mention

> This is why the user id is hardcoded

When you have time, could you point me to where in the code this happens? I don't understand how it ends up that even if I pass an `--id`, the default `Danger` value is used. Thanks ❤️ .

**Comment by f-meloni** [comment]
What is hardcoded is the user id, not the danger id.
I use `--id` often, then I think that works well, how are you setting it?

**Comment by f-meloni** [comment]
Anyway, this is the code

https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L133-L136

**Comment by mokagio** [comment]
> What is hardcoded is the user id, not the danger id.
Oh gotcha. That's why I couldn't find it. Makes sense.

> I use --id often, then I think that works well, how are you setting it?

I use the `--id` parameter too.

It works well if I have Danger locally, but I'm having troubles with the GitHub Action.

I've been experimenting with this yesterday. I'm probably doing something wrong, but it seems to me the Danger GitHub Action doesn't read the id.

See [this PR here for example](https://github.com/mokagio/WordPress-iOS/pull/19). I'm calling `danger ci` in the workflow like [this](https://github.com/mokagio/WordPress-iOS/pull/19/files#diff-aa836af17b1a07acf857ae723de4f003R13-R20):

```yml
- name: Run Consistency Checks
  uses: danger/danger-js@9.1.8
  with:
    args: |
      --dangerfile Automattic/peril-settings/org/pr/ios-macos.ts \
      --id danger_id_same
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

But the resulting Danger comment has id `danger-id-Danger`.

**Comment by orta** [comment]
Looks to me like the docker image for an action isn't respecting the args?

```
Step 9/10 : RUN cd /usr/src/danger &&   yarn &&   yarn run build:fast &&   chmod +x distribution/commands/danger.js &&   ln -s $(pwd)/distribution/commands/danger.js /usr/bin/danger
```

Was it definitely calling your dangerfile?

**Comment by mokagio** [comment]
> Was it definitely calling your dangerfile?

Yes, it was. I made a commit to trigger a failure comment from Danger, and [Danger posted it](https://github.com/mokagio/WordPress-iOS/pull/19#issuecomment-586188702).

**Comment by rohit-gohri** [comment]
There are 2 ways one can provide Github Token to danger when using it on Github Actions:

1. GITHUB_TOKEN: Temporary bot token generated by Github (https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token)
2. DANGER_GITHUB_API_TOKEN: Personal access token for a user, manually added to secrets

When updating/deleting comments only the 1st case is being considered in the Github Actions env and the userId is never considered, instead a hardcoded ID is returned.

https://github.com/danger/danger-js/blob/5ad5fd9a0b064c4f967366f120d2b4fe80810c93/source/platforms/github/GitHubAPI.ts#L133-L136

I think we should do that only if both the conditions are true, i.e.:
- CI is Github Actions (env.GITHUB_WORKFLOW is set)
- Token is in GITHUB_TOKEN and not in DANGER_GITHUB_API_TOKEN

This would allow people to use method 2. (for whatever reasons) and it would still work properly.

There would still be one case where it will fail and we probably can't detect it, just probably mention in docs not to use it this way 

> ```
>  GITHUB_TOKEN: ${{ secrets.MOKAGIO_BOT_GITHUB_TOKEN }}
> ```

@f-meloni @orta

**Comment by orta** [comment]
Yep, seems reasonable
