### ISSUE TITLE
Add App Center support for danger-js

### ISSUE THREAD

**Issue by mrndjo** [danger/danger-js#865]
I need to configure Danger with my iOS project on Visual Studio App Center. 
Ruby version already supports App Center, but I don't see that danger-js supports it.
Is there some other way to configure danger on App Center?

Ruby version:
**https://github.com/danger/danger/blob/master/lib/danger/ci_source/appcenter.rb**

**Comment by mrndjo** [comment]
I noticed that neither App Center and Codeship don't have pull request id, but you support CodeShip.
I hope you can manage to support App Center also.

**Comment by orta** [comment]
Yeah, if it can work on one it can work on the other - happy to accept a PR adding the same method that it works on the ruby implementation 👍

**Comment by mrndjo** [comment]
Here it is: https://github.com/danger/danger-js/pull/867

**Comment by ferdicus** [comment]
Can I piggyback on this, just because 
> Codeship don't have pull request id, but you support CodeShip

I'm trying to set this up for CodeShip as we speak and am stuck right at that point.

If I do not export any ENV variables of my own, as in
`export DANGER_TEST_REPO=user/repo`

It will simply use the `pulls/` without an id at the end

Ultimately failing with a 
```
Skipping Danger due to this run not executing on a PR.
```
message


I'm sorry if this is a known issue, however I couldn't find any for that yet.

**Comment by orta** [comment]
Good reminder that this issue should be closed, but ultimately I'd investigate what env vars are available and if danger can infer the number from the existing env vars

**Comment by ferdicus** [comment]
hey @orta, thanks - I did check and codeship indeed exposes the `CI_PR_NUMBER` as described in its [documentation](https://documentation.codeship.com/pro/builds-and-configuration/environment-variables/#default-environment-variables). However it also mentions "The pull request number associated with the build. This value is blank if the build was triggered on a commit, merge, or tag."

Kinda defeats the purpose if you ask me... 

Should I create a separate ticket for this?

**Comment by orta** [comment]
Maybe there needs to be some custom code to try look up a corresponding PR for commit/merges, it could be worth an issue and looking into it yourself 👍
