### ISSUE TITLE
structuredDiffForFile function returns incorrect results

### ISSUE THREAD

**Issue by pajapro** [danger/danger-js#866]
Hi there, I am using [`structuredDiffForFile`](https://danger.systems/js/reference.html#GitDSL)  method from `GitDSL`. I am using this function within the following code snippet:

```
function claimsToUpdateDocumentation() {
  let claimsToUpdateDocumentation = false
  danger.git.structuredDiffForFile(`${docsFolder}/CHANGEPLAN.md`)
    .then((diff) => {
      diff.chunks.forEach(chunk => {
        chunk.changes.forEach(change => {
          if (change.type === "add") {
            const offence = regexPattern.exec(change.content)
            if (offence) {
              claimsToUpdateDocumentation = true;
            }
          }
        })
      })
      return claimsToUpdateDocumentation;
    })
}
```

I got inspired about the usage of this method from [metaphysics dangerfile.ts](https://github.com/artsy/metaphysics/blob/0e1658cb735102ff53640a9e7c8ab4e54f61ce92/dangerfile.ts). Every-time danger is run on our CI (on premise BitBucket server) against a PR it gets the diff for `CHANGEPLAN.md` from _previous PR_. Example: 

```
danger pr https://company.merck.com/projects/foo/repos/boo/pull-requests/2607
```

[`structuredDiffForFile`](https://danger.systems/js/reference.html#GitDSL) returns me the diff of `CHANGEPLAN.md` from PR #2606 instead of returning diff from PR #2607.

Am I using [`structuredDiffForFile`](https://danger.systems/js/reference.html#GitDSL) incorrectly? Or is it a bug?

**Comment by orta** [comment]
Maybe try run with `env DEBUG=true` and double check what API calls it makes, seems real weird to be jumping to a different PR!

**Comment by pajapro** [comment]
Thanks for quick reply, executing:

`env DEBUG=true ./node_modules/.bin/danger pr https://company.merck.com/projects/foo/repos/boo/pull-requests/2607`

doesn't print any debug information

**Comment by osmestad** [comment]
I think you need to use DEBUG="*"

**Comment by osmestad** [comment]
As I was facing a similar issue (many of the Git API methods seem broken for Bitbucket Server), I did dig a bit more into this. The problem seems to be the two Git SHAs being switched in the API calls to get the diffs!
So in the `getStructuredDiffForFile` function in `source/platforms/bitbucket_server/BitBucketServerAPI.ts`, if I switch the `from` and `to` arguments on line 136:
```
const path = `rest/api/1.0/${repoSlug}/compare/diff/${filename}?withComments=false&from=${head}&to=${base}`
```
Then I get the expected behaviour. (Current code has: `from=${base}&to=${head}`.)
I'm not sure if this is the correct location to fix it though?

**Comment by osmestad** [comment]
Any input in this @orta, @langovoi or @azz ?
I can make a PR to change it, but I'd like to know if this is the correct location to attack the problem first :-)

**Comment by orta** [comment]
Seems reasonable to me, perhaps the API used to be bi-directional but isn't anymore?

**Comment by osmestad** [comment]
Cool I will make a PR with the change then

**Comment by azz** [comment]
> ```diff
> +from=${base}&to=${head}
> -from=${head}&to=${base}
> ```

Gosh that's so confusing...

**Comment by osmestad** [comment]
Very true :-P

**Comment by platan** [comment]
@pajapro Does version v9.2.1 with https://github.com/danger/danger-js/pull/871 solved the problem? Can we close this issue?

**Comment by pajapro** [comment]
@platan I tried v9.2.1 and it seems like a new problem has occurred:
![Untitled](https://user-images.githubusercontent.com/3673765/66295040-bcdb7100-e8ea-11e9-9986-4f0e3e7bf748.png)

The constructed URL seems incorrect, hence getting 500

**Comment by platan** [comment]
Version `9.2.1` (`node_modules/.bin/danger --version`: `9.2.1`) works properly with my simple project:
```
DANGER_BITBUCKETSERVER_HOST=http://localhost:7990/bitbucket DANGER_BITBUCKETSERVER_USERNAME=admin DANGER_BITBUCKETSERVER_TOKEN=ODIyNDUyOTIxMDAwOt5F4JwwCowf7nCX1ogkY9ybm+bd node_modules/.bin/danger pr http://localhost:7990/bitbucket/projects/PROJECT_1/repos/rep_1/pull-requests/2/overview
Starting Danger PR on projects/PROJECT_1/repos/rep_1#2
{ changes: 
   [ { type: 'normal',
       content: 'basic branching scenario',
       sourceLine: 1,
       destinationLine: 1 },
     { type: 'add',
       content: 'commit 1',
       sourceLine: 2,
       destinationLine: 2 },
     { type: 'add',
       content: 'commit 2',
       sourceLine: 2,
       destinationLine: 3 } ] }


Danger: ✓ passed review, received no feedback.
```
`dangerfile.js`:
```js
danger.git.modified_files.forEach(file =>
  danger.git.structuredDiffForFile(file).then(diff => {
    console.log(diff.chunks[0]);
  })
);
```
I will try to test it on an instance of Bitbucket in my company.

**Comment by platan** [comment]
I tested version 9.2.1 on a Bitbucket Server instance in my company and `danger.git.structuredDiffForFile` works properly.

**Comment by pajapro** [comment]
@platan I figured out that the problem was in our code 🤦‍♀️, so yes v9.2.1 with #871 solves the problem indeed! Sorry for confusion and thank you for help with resolving this issue
