### ISSUE TITLE
Add support for .env?

### ISSUE THREAD

**Issue by jamime** [danger/danger-js#868]
Would you be interested in a PR to add support for .env files?

**Comment by orta** [comment]
I'm not sure what that would do?

**Comment by jamime** [comment]
It would allow users to commit a `.env` file with any of the supported environment variables instead of providing them in the command or in the global system environment.

e.g. `DANGER_GITHUB_HOST`, `DANGER_BITBUCKETSERVER_HOST`, `DANGER_GITLAB_HOST`

For my use case, I have a custom gitlab host.

`DANGER_GITLAB_HOST=gitlab.com yarn run danger` would become
`yarn run danger`

https://www.npmjs.com/package/dotenv

**Comment by orta** [comment]
Hrm - that's a massive footgun with serious consequences in leaking app secrets.

Maybe if you can *only* support a custom filename like `.env.danger` and not accept the `.env` as a name, even then - that's an extra dependency for everyone else which not too much value.

**Comment by jamime** [comment]
It's possible to us the fs module and read process.env from a dangerfile. I'm not sure how this is any worse?

I'm happy to specify my env vars in my CI config but a .env file would make cross vendor compatibility easier.

I'll close for now.
