### ISSUE TITLE
https-proxy-agent vulnerability

### ISSUE THREAD

**Issue by vinhlh** [danger/danger-js#869]
![image](https://user-images.githubusercontent.com/261283/59001806-9d501100-8842-11e9-8ffa-55a78a9f9d23.png)
https://github.com/danger/danger-js/blob/master/package.json#L138

**Comment by orta** [comment]
Thanks for the issue, I'm fine with the notifications from GitHub 👍 

This is a CLI app, not a website so it is less important to keep these up to date
