### ISSUE TITLE
GitLab process does not exit

### ISSUE THREAD

**Issue by jamime** [danger/danger-js#875]
When using the GitLabAPI a [bug in `ky`](https://github.com/sindresorhus/ky/issues/138) prevents danger from exiting. Danger does not call `process.exit` but instead sets `process.exitCode`.

We can add [`process.exit`](https://nodejs.org/api/process.html#process_process_exit_code) in the commands to force an exit after `runRunner` has completed. This will still use the same exitCode and will prevent any future issues caused by leftover timeouts.

**Comment by jamime** [comment]
https://github.com/jdalrymple/node-gitlab/issues/348

**Comment by obartra** [comment]
I'm also hitting this issue, Danger comments on the PR but this adds a few minutes to the pipeline just waiting until it times out.

**Comment by jamime** [comment]
There is a fix in the works in the KY package
https://github.com/sindresorhus/ky/pull/145

This needs to be merged in, then node-gitlab needs to update their dependencies. Then we can increase the version of node-gitlab.
