### ISSUE TITLE
GitLab incorrect URL for `getMergeRequestNotes`

### ISSUE THREAD

**Issue by obartra** [danger/danger-js#876]
When running danger@8.0.0 using GitLab as CI I get an error that looks like the following:

```
2019-06-11T12:31:56.678Z danger:GitLabAPI getMergeRequestNotes {{repoSlug}} {{prIID}}
Error:  { HTTPError: Not Found
    at {{stackTrace}}
  name: 'HTTPError',
  response: 
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [Object], disturbed: true, error: null },
     [Symbol(Response internals)]: 
      { url: '{{hostUrl}}/api/v4/projects/projects/{{repoSlug}}/merge_requests/{{prIID}}/notes?id={{repoSlug}}¬eable_id={{prIID}}&order_by=created_at&page=2&per_page=20&sort=desc',
        status: 404,
        statusText: 'Not Found',
        headers: [Object],
        counter: 0 } },
  description: '404 Not Found' }
```

Looks like `projects/` is listed twice in the url. If I make the same query locally but removing the extra `/projects` I get the expected results instead of the 404.

I've defined my environment variables to match the docs, they look like:

```
DANGER_GITLAB_HOST=corp.host.com
DANGER_GITLAB_API_TOKEN=xxxxxxxxxxx
DANGER_GITLAB_API_BASE_URL=https://corp.host.com/api/v4
CI_MERGE_REQUEST_IID={{prIID}}
```

The other HTTP calls seem to be going through without issue (e.g. `getUser` or `getMergeRequestCommits`).

gitlab version installed is 6.3.3:

```
$ npm ls gitlab
{{projectPath}}
└─┬ danger@8.0.0
  └── gitlab@6.3.3
```

**Comment by obartra** [comment]
I've alsovtried forcing the resolution of gitlab@6.3.2, 6.3.1 and 6.3.0 but got the same results. Previous versions caused different errors (I assumed ^6.3.x was needed)

**Comment by obartra** [comment]
Seems caused by https://github.com/jdalrymple/node-gitlab/issues/344. Setting resolutions to the following fixes it:

```json
{
  "resolutions": {
    "gitlab": "3.3.4"
  }
}
```

**Comment by awgeorge** [comment]
Getting the same error with Danger 9.1.0 - Looks like there has been a few releases of node-gitlab, would you accept a PR for an update to the latest version? Or is still using 6.x OK for now?

**Comment by orta** [comment]
I think those releases were problematic, we might need to wait a bit - you're welcome to research though

**Comment by awgeorge** [comment]
Updated gitlab in #903 to fix Ky exit issue.
