### ISSUE TITLE
Add option for custom icon/emoji for messages

### ISSUE THREAD

**Issue by rohit-smpx** [danger/danger-js#890]
Danger should be able to add custom emoji/icons to the message table. Something like:

![image](https://user-images.githubusercontent.com/31949290/60880509-687c1300-a261-11e9-8c13-20e33eab9824.png)

I think the function could be modified to accept an options object, and add existing opts there?:
```ts
message(message: MarkdownString, opts?: {file?: string, line?: number, emoji?: MarkdownString}): void
```

Willing to work on this, if someone can give me a few pointers :smiley:

**Comment by f-meloni** [comment]
Wouldn't be ok to just add it on the message?

**Comment by orta** [comment]
Yeah, I think I'm fine with this changing for just message - but I'd like it to have a check that it's a max of 2 chars, I'd rather not let people break the table :D

**Comment by orta** [comment]
I take it back. I think arbitrary text is fine, because you could use it to show an image.

**Comment by rohit-smpx** [comment]
> Wouldn't be ok to just add it on the message?
> 
> ```js
> fail("Test Failed!😡")
> ```

That's what I'm currently doing, but it is easier to distinguish messages at a glance if I can provide an image/emoji according to the type of message in a single column. 

I think my example was wrong, because that fits more in the `fail` or `warn` category. Better examples would be success/alert messages with different icons, examples :
- :speech_balloon: - PR metadata(description, labels) Filled correctly 
- :memo: - CHANGELOG added
- :bell: - Alerting a team about changes to some system

**Comment by rohit-smpx** [comment]
> I take it back. I think arbitrary text is fine, because you could use it to show an image.

Cool, I'll try my hand at this then
