### ISSUE TITLE
Danger message disappear after refresh the webpage

### ISSUE THREAD

**Issue by wrmswindmill** [danger/danger-js#900]
I use Dangerfile and Travis CI to build automation code review. but after I refreshed the [pr webpage](https://github.com/apache/incubator-weex/pull/2751) a few times, the message disappeared and it hasn't displayed anymore.

this is the webpage it should be:
![图片](https://user-images.githubusercontent.com/33521539/61880228-13115880-af27-11e9-9fe8-d2694a6c4038.png)

but here is the webpage now:
![image](https://user-images.githubusercontent.com/33521539/61880462-874bfc00-af27-11e9-84e9-1b257d187b8d.png)

I will be very appreciated if you solved this problem. thanks very much!

dangerfile:https://github.com/apache/incubator-weex/blob/master/dangerfile.js
travis.yml: https://github.com/apache/incubator-weex/blob/master/.travis.yml

**Comment by orta** [comment]
I'd recommend looking at your CI build logs during that time and seeing if it danger is outputting that it was deleting the messages because there were no errors. Deleting the message once it's not needed is a feature of danger.

**Comment by wrmswindmill** [comment]
Thanks for your reply, in the CI build log,I don't found deleting the message.

CI build log link:https://travis-ci.org/apache/incubator-weex/jobs/563546312

**Comment by wrmswindmill** [comment]
thanks for your reply.

what should I do if I want to keep the warning message without error?

**Comment by orta** [comment]
> Skipping Danger due to not this run not executing on a PR.

That run doesn't trigger Danger because it wasn't a PR run.

Maybe there's a CLI flag to not delete, someone else might have shipped that - check what the args are to `danger pr`  👍

**Comment by wrmswindmill** [comment]
I'm very very very sorry to paste a wrong build log link, 
this is the actual link: https://travis-ci.org/apache/incubator-weex/jobs/563546312

and the log indicates: Danger execute success!

**Comment by orta** [comment]
Yep, that should be posting! I'd recommend re-running the command with `env DEBUG="*"`. It's also possible that GitHub has declared your [bot as a bot](https://danger.systems/js/guides/faq.html#danger-is-not-posting-to-github-prs-but-everything-looks-fine) and made it so you can't see the posts

**Comment by wrmswindmill** [comment]
Thanks for detailed reply,I will try the method you offer.

**Comment by wrmswindmill** [comment]
I use DEBUG="*",but the output is too long so that Travis CI can't display the whole message.

in my case, I think my account has triggered the bot detection algorithm on GitHub because I test Travis CI too many times.(Danger message in the other's pr works well except mine)

Thanks for your help!!

**Comment by wrmswindmill** [comment]
I can't found  anything about bot detection algorithm on GitHub, What can I do to release trigger？

**Comment by orta** [comment]
Did you log into the account? There's a message in there

**Comment by wrmswindmill** [comment]
I have logged into my Github account and found nothing in there.

**Comment by wrmswindmill** [comment]
Thanks for your detailed reply, I finally find the reason.

the reason is the "danger version is too old"
