### ISSUE TITLE
How to run multiple dangerfiles without overwriting

### ISSUE THREAD

**Issue by wrmswindmill** [danger/danger-js#902]
I want to run multiple dangers for a PR on Travis CI.but it seems just keep messages that  the last Travis CI job output.What should I do?

I know in Danger, I can use `--danger_id` like:https://danger.systems/guides/faq.html#multiple-dangers. But in danger-js, the `--danger_id` is an unknown option for `danger run`.

I know you have done some works:https://github.com/danger/danger-js/issues/196, but by reading it, I can't get the solution.

I will be very appreciated if you can help me, thank you very much!

**Comment by orta** [comment]
Did you try running `danger ci --help` to look at the help? - that feature looks like it's [in the code](https://github.com/danger/danger-js/blob/master/source/runner/Executor.ts#L51-L52)

**Comment by wrmswindmill** [comment]
I'm trying to run `yarn danger ci --help` on my local machine, but it return the below messages and I don't receive anything about how to use `danger ci`.

```
➜  incubator-weex git:(filter-oclint-output) yarn danger ci --help
yarn run v1.17.3
$ danger ci --help
OK, everything looks good: Fake Testing CI on GitHub
checkMasterBranch
checkDocumentation
checkDemo
checkMileStone
Danger has errored
Error: ENOENT: no such file or directory, open 'lib/components/gene/about.js'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at dangerfile.js:110:30
    at Array.filter (<anonymous>)
    at Object.<anonymous> (dangerfile.js:99:29)
    at Runtime._execModule (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/jest-runtime/build/index.js:446:13)
    at Runtime.requireModule (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/jest-runtime/build/index.js:294:14)
    at /Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/runner/DangerfileRunner.js:136:33
    at ensureCleanDangerfile (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/runner/DangerfileRunner.js:176:5)
    at Object.<anonymous> (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/runner/DangerfileRunner.js:135:21) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'lib/components/gene/about.js'
}
Failing the build, there is 1 fail.
Request failed [403]: https://api.github.com/repos/artsy/emission/issues/327/comments
Response: {
  "message": "Unable to create comment because issue is locked.",
  "documentation_url": "https://help.github.com/articles/locking-conversations/"
}
Error:  Error: body used already for: https://api.github.com/repos/artsy/emission/issues/327/comments
    at Response.Body._decode (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/node-fetch/lib/body.js:88:30)
    at Response.Body.json (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/node-fetch/lib/body.js:44:14)
    at GitHubAPI.<anonymous> (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/platforms/github/GitHubAPI.js:183:51)
    at step (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/platforms/github/GitHubAPI.js:40:23)
    at Object.next (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/platforms/github/GitHubAPI.js:21:53)
    at fulfilled (/Users/wangrenmin/Desktop/Weex/fork-incubator/incubator-weex/node_modules/danger/distribution/platforms/github/GitHubAPI.js:12:58)
```

**Comment by wrmswindmill** [comment]
by the [link](https://github.com/danger/danger-js/blob/master/source/runner/Executor.ts#L51-L52) you give, I try to add `--dangerID=oclint`, but `--dangerID` is is an unknown option for `danger run`.

**Comment by orta** [comment]
```
orta@Perl ~/d/d/danger-js> node ./distribution/commands/danger.js ci --help
Usage: danger-ci [options]

Runs a Dangerfile in JavaScript or TypeScript.

Options:
  -v, --verbose                             Verbose output of files
  -t, --text-only                           Provide an STDOUT only interface, Danger will not post to your PR
  -d, --dangerfile [filePath | remote url]  Specify a custom dangerfile path, remote urls only work with github
  -i, --id [danger_id]                      Specify a unique Danger ID for the Danger run
  -b, --base [branch_name]                  Use a different base branch
  -c, --external-ci-provider [modulePath]   Specify custom CI provider
  -p, --process [command]                   [dev] Runs a custom sub-process instead of the Danger JS runtime
  -u, --passURLForDSL                       [dev] Use a custom URL to send the Danger DSL into the sub-process
  -f, --failOnErrors                        Fail if there are fails in the danger report
  --use-github-checks                       Use GitHub Checks
  -h, --help                                output usage information
```

Looks like it is `id`

**Comment by wrmswindmill** [comment]
thanks for your detailed reply, and by your comment，I notice that maybe danger version that the project use maybe outdate.  

after I update the danger, everything work well！

Thank you very very much !!!

**Comment by rashadatjou** [comment]
> ```
> orta@Perl ~/d/d/danger-js> node ./distribution/commands/danger.js ci --help
> Usage: danger-ci [options]
> 
> Runs a Dangerfile in JavaScript or TypeScript.
> 
> Options:
>   -v, --verbose                             Verbose output of files
>   -t, --text-only                           Provide an STDOUT only interface, Danger will not post to your PR
>   -d, --dangerfile [filePath | remote url]  Specify a custom dangerfile path, remote urls only work with github
>   -i, --id [danger_id]                      Specify a unique Danger ID for the Danger run
>   -b, --base [branch_name]                  Use a different base branch
>   -c, --external-ci-provider [modulePath]   Specify custom CI provider
>   -p, --process [command]                   [dev] Runs a custom sub-process instead of the Danger JS runtime
>   -u, --passURLForDSL                       [dev] Use a custom URL to send the Danger DSL into the sub-process
>   -f, --failOnErrors                        Fail if there are fails in the danger report
>   --use-github-checks                       Use GitHub Checks
>   -h, --help                                output usage information
> ```
> 
> Looks like it is `id`

I <3 @orta
