### ISSUE TITLE
Remove jsome dependency

### ISSUE THREAD

**Issue by mathiashoeld** [danger/danger-js#914]
The npm package `mem` is marked as security vulnerability by Github. The package is a dependency of `os-locale` which is a dependency of `yargs` which is a dependency of `jsome` which has not been updated for 2 years, i.e. it is not likely that the `yargs` dependency will be updated anytime soon. (See [this issue for reference](https://github.com/Javascipt/Jsome/issues/20))

To remove this security vulnerability it would be ideal to remove the dependency on jsome since it is probably only used only for styling the json output.

**Comment by orta** [comment]
https://github.com/rafeca/prettyjson could do it

**Comment by platan** [comment]
I think this issue was resolved by https://github.com/danger/danger-js/pull/920. Can we close it?

**Comment by orta** [comment]
Ace, sure
