### ISSUE TITLE
DangerJS in GitHub actions does not overwrite or delete previous comments

### ISSUE THREAD

**Issue by jmenestr** [danger/danger-js#936]
Like in other CI workflows, I would expect any dangerjs code run in github actions to correctly update/delete previous comments made by previous builds. This currently does not happen, resulting in a *new* comment being created for every run.

While not functionally blocking, it create a rather poor experience because it results in a lot of noise.

I think I've identified the issue at these lines:
https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L133-L136
It seems that the userID is hardcoded for github actions and always returns the same value rather than looking up the user associated with the current GITHUB_TOKEN.

As a result of the hardcoded id, when the API goes to look for previous comments that are created by danger to update/delete them, there's a check on the userid in a `filter` and because the hard coded will probably never match the actual userid, it never gets a list of comments to actually update/delete.

https://github.com/danger/danger-js/blob/master/source/platforms/github/GitHubAPI.ts#L85-L96

I'm mot sure if this behavior was intentional, or if it was just something that was missed.

**Comment by jmenestr** [comment]
PR is up at #935

**Comment by fbartho** [comment]
@jmenestr, my team isn’t seeing this behavior, and we are relatively up to date, and use danger with GitHub actions.

I guess if we’re missing something deeper?
