### ISSUE TITLE
TypeError: danger.git.modified_files.includes is not a function

### ISSUE THREAD

**Issue by dblock** [danger/danger-js#95]
Danger 0.8.0. What am I missing?

https://travis-ci.org/matt-kruse/alexa-app-server/builds/190989229

**Comment by orta** [comment]
I can't see the build but `includes` was added in node 5/6 I think, so 4 and below fail?

**Comment by dblock** [comment]
This was with 5.11, correct link https://travis-ci.org/alexa-js/alexa-app-server/builds/190989229, sorry about that.

**Comment by kwonoj** [comment]
If you're using `array.includes` and node is `5.11`, it's hidden behind `harmony` flag. http://node.green/#Array-prototype-includes

**Comment by macklinu** [comment]
I'm going to mark this as resolved, thanks for that info @kwonoj.
