### ISSUE TITLE
Allow not sending statuses to pull request

### ISSUE THREAD

**Issue by gzaripov** [danger/danger-js#959]
I want danger to have option `--no-publish-check` that will prevent danger from adding status to pull request because I have one already. This is restriction of our enterprise CI, and danger works fine there because it has option to pass external ci provider. 
There is another approach to this issue, we can allow client to provide custom platform through `--external-platform` option and it will a lot of user cases.
What do you think?

**Comment by orta** [comment]
I think that option makes sense 👍, I'd accept a PR for that

**Comment by gzaripov** [comment]
@orta have a look on this

**Comment by gzaripov** [comment]
@orta I'm glad that this PR was merged so fast, when are you going to release this feature?

**Comment by orta** [comment]
I usually wait for two PRs to get merged before making a release, you'll get a notification in the PR when it goes live 👍
