### ISSUE TITLE
danger local should consider uncommitted changes

### ISSUE THREAD

**Issue by sk-** [danger/danger-js#972]
`danger local` only computes the differences between commits and does not consider changes not yet committed.

If I modify a file, I'd like to be able to locally check it before committing it, so that my local commits are compliant.

**Comment by orta** [comment]
Yeah, I use it as a git commit hook - I'm open to a flag or to do some audits to decide if you want staged instead

**Comment by f-meloni** [comment]
I think there was an initial implementation of it, but was not finished https://github.com/danger/danger-js/blob/master/source/commands/danger-local.ts#L14

**Comment by sk-** [comment]
I think that getting staged and unstaged filed is fairly easy, we just need to run `git diff base` instead of `git diff base..HEAD`.

For untracked files, we would need to change the way the list of created files are computed. Currently they are only obtained from the diff. However, given that there's no diff for those files they will never be there, and we would need to use `git status`.

Also, I'm not sure what the implications would be if we add this unstaged or untracked files. as 
some other functions may fail.

WDYT?

**Comment by orta** [comment]
I think it is probably worth faking the diff for the new files before it goes into the DSL generation, so that code can be consistent with `danger  pr` and `danger local` (without `--staging`)

**Comment by Soyn** [comment]
@orta Did you mean when run `danger local`(with no flag from stdin), the uncommitted changes would be as the diff by default?

**Comment by orta** [comment]
yep

**Comment by Soyn** [comment]
I'm a little confused on your comment. You mean we should add the uncommitted diff in current function. https://github.com/danger/danger-js/blob/9ffa89ad76c553e8aff53a02baa37b9b8118e2ce/source/platforms/LocalGit.ts#L47

**Comment by Soyn** [comment]
I have sent a pull request about this issue. I wonder this solution is the right way you think. @orta
