### ISSUE TITLE
Add a Danger comment preview summary

### ISSUE THREAD

**Issue by kwonoj** [danger/danger-js#98]
Currently dangerfile support markdown via `markdown()` explicitly, while any other messages are using HTML template tables.

Case of HTML templates, notifications other than github page sometimes does not able to display full contents, by HTML tags takes most of texts and actual contents are being trimmed. For example, below is our current slack github hook notification - 

![image](https://cloud.githubusercontent.com/assets/1210596/21952496/5742306e-d9d3-11e6-8912-8a5bfc10bc9a.png)

can't see actual messages and have to open github page.

What about github template renders all contents via markdown by default, then introduce some configuration to select HTML based templates instead? In those cases, danger messages will behave 

1. if template's markdown
`message() === markdown()`, all other messages will be rendered to markdown as well

2. if template's html
`message() !== markdown()`, user selectively choose between message & markdown to render contents. All other messages will be rendered into HTML table.

**Comment by kwonoj** [comment]
or to not to break existing behavior, HTML by default and selective template (or custom template configuration).

**Comment by orta** [comment]
Gordian knot solution with less configuration: Make the first 5 lines a hidden summary in HTML, take the first ~140 chars if 1 of the types and summarize if more.

```
<!-- Danger report:
1 Fail: No Changelog added. You can find it at...
3 Warnings.
2 Markdown notices.
-->
<table>
  <thead>
```

Would make a better template for something like slack anyway, due to it being a nice summary too.

**Comment by orta** [comment]
The main reason for the HTML/markdown dance is that tables can be a consistent length - https://github.com/danger/danger/pull/65

**Comment by kwonoj** [comment]
Yeah, that seems feasible solution.

**Comment by kwonoj** [comment]
Updated title to reflect conclusion.
