### ISSUE TITLE
Upgrade micromatch to resolve vulnerabilities in transitive dependencies

### ISSUE THREAD

**Issue by simoneb** [danger/danger-js#980]
Danger 9.2.10 is referencing `micromatch` ^3.1.10, which transitively depends on versions of packages `mixin-deep` and `set-value` with known vulnerabilities, as reported in GitHub's security advisory:

![image](https://user-images.githubusercontent.com/20181/73380980-3e557580-42c5-11ea-868d-9a5cc6a1135c.png)

Danger should upgrade to a more recent version of `micromatch`, which apparently is not even using those packages anymore.

**Comment by orta** [comment]
Sure thing, happy to get them updated 👍

**Comment by simoneb** [comment]
Thanks!

**Comment by cxong** [comment]
This was addressed in https://github.com/danger/danger-js/commit/c74329c33eab4908120ed22032e57dee67d1dceb
Ok to close @orta ?

**Comment by orta** [comment]
Yep, thanks
